# Generated by Django 3.2.13 on 2022-06-30 07:16

import django.db.models.deletion
from django.db import migrations, models

import peachjam.models.attachments


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Judge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Judgment",
            fields=[
                (
                    "coredocument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="peachjam.coredocument",
                    ),
                ),
                ("headnote_holding", models.TextField(blank=True)),
                ("additional_citations", models.TextField(blank=True)),
                ("flynote", models.TextField(blank=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="peachjam.author",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
            bases=("peachjam.coredocument",),
        ),
        migrations.CreateModel(
            name="MatterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JudgmentMediaSummaryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=peachjam.models.attachments.file_location
                    ),
                ),
                ("size", models.IntegerField()),
                ("filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_summaries",
                        to="peachjam.judgment",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "filename"],
            },
        ),
        migrations.CreateModel(
            name="CaseNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("string", models.CharField(blank=True, max_length=1024, null=True)),
                ("number", models.PositiveIntegerField(blank=True, null=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_numbers",
                        to="peachjam.judgment",
                    ),
                ),
                (
                    "matter_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="peachjam.mattertype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bench",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="peachjam.judge",
                        verbose_name="judge",
                    ),
                ),
                (
                    "judgment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bench",
                        to="peachjam.judgment",
                        verbose_name="judgment",
                    ),
                ),
            ],
            options={
                "db_table": "peachjam_judgment_judges",
                "ordering": ("pk",),
                "unique_together": {("judgment", "judge")},
            },
        ),
        migrations.AddField(
            model_name="judgment",
            name="judges",
            field=models.ManyToManyField(
                through="peachjam.Bench", to="peachjam.Judge", verbose_name="judges"
            ),
        ),
    ]
