# Generated by Django 3.2.12 on 2022-04-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0002_auto_20220413_0827"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coredocument",
            name="work_frbr_uri",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
    ]
