# Generated by Django 3.2.12 on 2022-04-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0003_alter_coredocument_work_frbr_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="locality",
            name="code",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
