# Generated by Django 3.2.12 on 2022-04-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0003_alter_coredocument_work_frbr_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="coredocument",
            name="content_html_is_akn",
            field=models.BooleanField(default=False),
        ),
    ]
