# Generated by Django 3.2.13 on 2022-07-04 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0003_auto_20220630_0938"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="case_name",
            field=models.CharField(
                blank=True,
                help_text="Party names for use in title",
                max_length=4096,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="mnc",
            field=models.CharField(
                blank=True,
                help_text="Media neutral citation",
                max_length=4096,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="serial_number",
            field=models.IntegerField(
                help_text="Serial number for MNC, unique for a year and an author.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="peachjam.author"
            ),
        ),
    ]
