# Generated by Django 3.2.12 on 2022-04-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0004_add_akn_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="coredocument",
            name="toc_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
