# Generated by Django 3.2.13 on 2022-07-05 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0004_judgment_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericdocument",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="peachjam.author",
            ),
        ),
        migrations.AlterField(
            model_name="legalinstrument",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="peachjam.author",
            ),
        ),
    ]
