# Generated by Django 3.2.12 on 2022-04-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0005_coredocument_toc_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="locality",
            name="code",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
