# Generated by Django 3.2.13 on 2022-07-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0005_auto_20220705_1131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgment",
            name="case_name",
            field=models.CharField(
                help_text="Party names for use in title", max_length=4096
            ),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="mnc",
            field=models.CharField(help_text="Media neutral citation", max_length=4096),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="serial_number",
            field=models.IntegerField(
                help_text="Serial number for MNC, unique for a year and an author."
            ),
        ),
    ]
