# Generated by Django 3.2.13 on 2022-07-17 09:30

import django.core.validators
from django.db import migrations, models

import peachjam.frbr_uri


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0005_auto_20220705_1131"),
    ]

    operations = [
        migrations.AddField(
            model_name="coredocument",
            name="frbr_uri_actor",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9_-]$",
                        "Only lowercase letters, numbers, _ and - allowed",
                    )
                ],
                help_text="Originating actor. Lowercase letters, numbers _ and - only.",
            ),
        ),
        migrations.AddField(
            model_name="coredocument",
            name="frbr_uri_date",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[peachjam.frbr_uri.validate_frbr_uri_date],
                help_text="YYYY, YYYY-MM, or YYYY-MM-DD",
            ),
        ),
        migrations.AddField(
            model_name="coredocument",
            name="frbr_uri_doctype",
            field=models.CharField(
                choices=[
                    ("act", "act"),
                    ("judgment", "judgment"),
                    ("document", "document"),
                ],
                max_length=20,
                null=True,
                help_text="Document subtype. Lowercase letters, numbers _ and - only.",
            ),
        ),
        migrations.AddField(
            model_name="coredocument",
            name="frbr_uri_number",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9_-]$",
                        "Only lowercase letters, numbers, _ and - allowed",
                    )
                ],
                help_text="Unique number or short title identifying this work. Lowercase letters, numbers _ and - only.",
            ),
        ),
        migrations.AddField(
            model_name="coredocument",
            name="frbr_uri_subtype",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9_-]$",
                        "Only lowercase letters, numbers, _ and - allowed",
                    )
                ],
                help_text="Document subtype. Lowercase letters, numbers _ and - only.",
            ),
        ),
    ]
