# Generated by Django 3.2.13 on 2022-07-13 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0006_judgment_required_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="peachjam.coredocument",
            ),
        ),
        migrations.AlterField(
            model_name="sourcefile",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_file",
                to="peachjam.coredocument",
            ),
        ),
    ]
