# Generated by Django 3.2.13 on 2022-05-20 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0007_documenttopic_taxonomy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Predicate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("verb", models.CharField(max_length=100)),
                (
                    "reverse_verb",
                    models.CharField(
                        help_text="Reversed verbal form of the relationship",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_work_frbr_uri", models.CharField(max_length=1024)),
                ("object_work_frbr_uri", models.CharField(max_length=1024)),
                (
                    "predicate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="peachjam.predicate",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("subject_work_frbr_uri", "object_work_frbr_uri", "predicate")
                },
            },
        ),
    ]
