# Generated by Django 3.2.13 on 2022-05-24 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0007_documenttopic_taxonomy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            options={"ordering": ["title"]},
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frbr_uri", models.CharField(max_length=1024, unique=True)),
                ("title", models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name="coredocument",
            name="work",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="peachjam.work",
            ),
        ),
    ]
