# Generated by Django 3.2.12 on 2022-06-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0007_documenttopic_taxonomy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingestor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=2048)),
                ("token", models.CharField(max_length=2048)),
                (
                    "adapter",
                    models.CharField(
                        choices=[("indigo_adapter", "Indigo Adapter")], max_length=2048
                    ),
                ),
                ("last_refreshed_at", models.DateTimeField()),
            ],
        ),
    ]
