# Generated by Django 3.2.13 on 2022-05-24 19:29

from django.db import migrations


def forwards(apps, schema_editor):
    CoreDocument = apps.get_model("peachjam", "CoreDocument")
    Work = apps.get_model("peachjam", "Work")
    db_alias = schema_editor.connection.alias

    works = {w.frbr_uri: w for w in Work.objects.using(db_alias).all()}

    for doc in CoreDocument.objects.using(db_alias).all():
        if doc.work_frbr_uri not in works:
            works[doc.work_frbr_uri] = Work.objects.create(frbr_uri=doc.work_frbr_uri)
        doc.work = works[doc.work_frbr_uri]
        doc.save(update_fields=["work"])


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0008_work"),
    ]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop)]
