# Generated by Django 3.2.13 on 2022-06-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0008_ingestor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestor",
            name="last_refreshed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
