# Generated by Django 3.2.13 on 2022-05-24 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0009_backfill_works"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coredocument",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="peachjam.work",
            ),
        ),
    ]
