# Generated by Django 3.2.13 on 2022-05-24 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0010_alter_coredocument_work"),
    ]

    operations = [
        migrations.CreateModel(
            name="Predicate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("verb", models.CharField(max_length=100)),
                (
                    "reverse_verb",
                    models.CharField(
                        help_text="Reversed verbal form of the relationship",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_target_id",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "object_target_id",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "object_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="peachjam.work",
                    ),
                ),
                (
                    "predicate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="peachjam.predicate",
                    ),
                ),
                (
                    "subject_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="peachjam.work",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    (
                        "subject_work",
                        "subject_target_id",
                        "object_work",
                        "object_target_id",
                        "predicate",
                    )
                },
            },
        ),
    ]
