# Generated by Django 3.2.13 on 2022-07-18 08:03

import django.core.validators
from django.db import migrations, models

import peachjam.frbr_uri


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0010_backfill_frbr_uri_components"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coredocument",
            name="frbr_uri_actor",
            field=models.CharField(
                blank=True,
                help_text="Originating actor. Lowercase letters, numbers _ and - only.",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9_-]+$",
                        "Only lowercase letters, numbers, _ and - allowed",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="frbr_uri_date",
            field=models.CharField(
                help_text="YYYY, YYYY-MM, or YYYY-MM-DD",
                max_length=10,
                validators=[peachjam.frbr_uri.validate_frbr_uri_date],
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="frbr_uri_doctype",
            field=models.CharField(
                choices=[
                    ("act", "act"),
                    ("doc", "doc"),
                    ("judgment", "judgment"),
                    ("statement", "statement"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="frbr_uri_number",
            field=models.CharField(
                help_text="Unique number or short title identifying this work. Lowercase letters, numbers _ and - only.",
                max_length=1024,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9_-]+$",
                        "Only lowercase letters, numbers, _ and - allowed",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="frbr_uri_subtype",
            field=models.CharField(
                blank=True,
                help_text="Document subtype. Lowercase letters, numbers _ and - only.",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9_-]+$",
                        "Only lowercase letters, numbers, _ and - allowed",
                    )
                ],
            ),
        ),
    ]
