# Generated by Django 3.2.14 on 2022-08-10 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages_plus", "0004_auto_20171214_0004"),
        ("countries_plus", "0005_auto_20160224_1804"),
        ("peachjam", "0011_frbr_uri_required_components"),
    ]

    operations = [
        migrations.AddField(
            model_name="legislation",
            name="parent_work",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="peachjam.work",
            ),
        ),
        migrations.AddField(
            model_name="legislation",
            name="repealed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="peachjamsettings",
            name="document_jurisdictions",
            field=models.ManyToManyField(
                blank=True,
                related_name="_peachjam_peachjamsettings_document_jurisdictions_+",
                to="countries_plus.Country",
            ),
        ),
        migrations.AlterField(
            model_name="peachjamsettings",
            name="document_languages",
            field=models.ManyToManyField(
                blank=True,
                related_name="_peachjam_peachjamsettings_document_languages_+",
                to="languages_plus.Language",
            ),
        ),
    ]
