# Generated by Django 3.2.13 on 2022-07-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0012_auto_20220725_1956"),
        ("peachjam", "0012_auto_20220726_1101"),
    ]

    operations = []
