# Generated by Django 3.2.14 on 2022-08-08 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0013_merge_0012_auto_20220725_1956_0012_auto_20220726_1101"),
    ]

    operations = [
        migrations.AddField(
            model_name="legislation",
            name="parent_work",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="peachjam.work",
            ),
        ),
        migrations.AddField(
            model_name="legislation",
            name="repealed",
            field=models.BooleanField(default=False),
        ),
    ]
