# Generated by Django 3.2.15 on 2022-09-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0016_file_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxonomy",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
