# Generated by Django 3.2.15 on 2022-09-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0017_article_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(default="-", unique=True),
            preserve_default=False,
        ),
    ]
