# Generated by Django 3.2.15 on 2022-09-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0017_alter_taxonomy_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="casenumber",
            name="string_override",
            field=models.CharField(
                blank=True,
                help_text="Override for full case number string",
                max_length=1024,
                null=True,
            ),
        ),
    ]
