# Generated by Django 3.2.15 on 2022-09-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0018_article_slug"),
        ("peachjam", "0018_casenumber_string_override"),
    ]

    operations = []
