# Generated by Django 3.2.15 on 2022-09-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0017_article_userprofile"),
        ("peachjam", "0018_casenumber_string_override"),
    ]

    operations = []
