# Generated by Django 3.2.15 on 2022-09-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0019_article_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestor",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
