# Generated by Django 3.2.15 on 2022-09-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0019_merge_20220919_1511"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                default="", editable=False, max_length=1024, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="slug",
            field=models.SlugField(
                default="", editable=False, max_length=1024, unique=True
            ),
            preserve_default=False,
        ),
    ]
