# Generated by Django 3.2.14 on 2022-09-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0019_ingestor_enabled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="judgmentmediasummaryfile",
            old_name="mime_type",
            new_name="mimetype",
        ),
    ]
