# Generated by Django 3.2.15 on 2022-09-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0019_merge_20220916_1232"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="slug",
            field=models.SlugField(
                default="nick-mwangemi", max_length=1024, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=1024, unique=True),
        ),
    ]
