# Generated by Django 3.2.14 on 2022-09-23 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0020_rename_mime_type_judgmentmediasummaryfile_mimetype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgmentmediasummaryfile",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_summaries",
                to="peachjam.judgment",
            ),
        ),
        migrations.AlterField(
            model_name="judgmentmediasummaryfile",
            name="filename",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="judgmentmediasummaryfile",
            name="mimetype",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="judgmentmediasummaryfile",
            name="size",
            field=models.BigIntegerField(default=0),
        ),
    ]
