# Generated by Django 3.2.15 on 2022-09-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0019_article_userprofile"),
        ("peachjam", "0021_auto_20220923_1111"),
    ]

    operations = []
