# Generated by Django 3.2.15 on 2022-09-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0021_auto_20220923_1111"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="hearing_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
