# Generated by Django 3.2.14 on 2022-09-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0021_auto_20220923_1111"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="serial_number_override",
            field=models.CharField(
                blank=True,
                help_text="You can override the auto generated MNC serial number",
                max_length=1024,
                null=True,
            ),
        ),
    ]
