# Generated by Django 3.2.14 on 2022-09-28 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("peachjam", "0023_article_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genericdocument",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="legalinstrument",
            options={"base_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="coredocument",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_peachjam.coredocument_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
