# Generated by Django 3.2.14 on 2022-09-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0024_court_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgment",
            name="author",
        ),
    ]
