# Generated by Django 3.2.14 on 2022-09-28 13:57

from django.db import migrations


def backfill_polymorphic_content_types(apps, schema_editor):
    """Add the polymorphic content type to existing document models"""
    ContentType = apps.get_model("contenttypes", "ContentType")
    GenericDocument = apps.get_model("peachjam", "GenericDocument")
    Legislation = apps.get_model("peachjam", "Legislation")
    Judgment = apps.get_model("peachjam", "Judgment")

    generic_doc_ct = ContentType.objects.get_for_model(GenericDocument)
    GenericDocument.objects.filter(polymorphic_ctype__isnull=True).update(
        polymorphic_ctype=generic_doc_ct
    )

    legislation_ct = ContentType.objects.get_for_model(Legislation)
    Legislation.objects.filter(polymorphic_ctype__isnull=True).update(
        polymorphic_ctype=legislation_ct
    )

    judgment_ct = ContentType.objects.get_for_model(Judgment)
    Judgment.objects.filter(polymorphic_ctype__isnull=True).update(
        polymorphic_ctype=judgment_ct
    )


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0026_core_document_polymorphic"),
    ]

    operations = [
        migrations.RunPython(
            backfill_polymorphic_content_types, migrations.RunPython.noop
        ),
    ]
