# Generated by Django 3.2.15 on 2022-10-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0027_backfill_polymorphic_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="serial_number_override",
            field=models.IntegerField(
                blank=True,
                help_text="Specific MNC serial number assigned by the court.",
                null=True,
            ),
        ),
    ]
