# Generated by Django 3.2.15 on 2022-10-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0028_auto_20221004_1617"),
        ("peachjam", "0028_judgment_serial_number_override"),
    ]

    operations = []
