# Generated by Django 3.2.14 on 2022-10-20 04:42

from django.db import migrations, models

import peachjam.models.attachments


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0029_merge_20221012_0857"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachedfiles",
            options={"verbose_name_plural": "Attached Files"},
        ),
        migrations.AlterField(
            model_name="attachedfiles",
            name="file",
            field=models.FileField(
                max_length=1024,
                upload_to=peachjam.models.attachments.file_location,
            ),
        ),
    ]
