# Generated by Django 3.2.15 on 2022-10-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0030_attachement_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentnature",
            name="code",
            field=models.SlugField(max_length=1024, null=True),
        ),
    ]
