# Generated by Django 3.2.15 on 2022-10-21 13:01

from django.db import migrations
from django.utils.text import slugify


def add_nature_codes(apps, schema_editor):
    DocumentNature = apps.get_model("peachjam", "DocumentNature")
    for nature in DocumentNature.objects.filter(code=None):
        nature.code = slugify(nature.name)
        nature.save()


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0031_documentnature_code"),
    ]

    operations = [migrations.RunPython(add_nature_codes, migrations.RunPython.noop)]
