# Generated by Django 3.2.15 on 2022-10-27 13:30

from django.db import connection, migrations
from django.db.models import F, Value
from django.db.models.functions import Concat

from peachjam.storage import get_default_storage_prefix


def add_s3_bucket(apps, schema_editor):
    """add prefix to stored files -- s3:bucket: in production, file: in DEBUG"""
    for model_name in ["SourceFile", "AttachedFiles"]:
        model = apps.get_model("peachjam", model_name)
        prefix = get_default_storage_prefix(None, model(), None)
        model.objects.exclude(file__startswith="s3:").update(
            file=Concat(Value(prefix), F("file"))
        )


def remove_s3_bucket(apps, schema_editor):
    """strip the prefix from stored files"""
    for model_name in ["SourceFile", "AttachedFiles"]:
        model = apps.get_model("peachjam", model_name)

        with connection.cursor() as cursor:
            cursor.execute(
                f"""
UPDATE {model._meta.db_table}
SET file = SUBSTRING(file FROM 4 + POSITION(':' IN SUBSTRING(file FROM 4)))
WHERE file like 's3:%'
"""
            )

            cursor.execute(
                f"""
UPDATE {model._meta.db_table}
SET file = SUBSTRING(file FROM 6)
WHERE file like 'file:%'
"""
            )


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0033_alter_documentnature_code"),
    ]

    operations = [migrations.RunPython(add_s3_bucket, remove_s3_bucket)]
