# Generated by Django 3.2.16 on 2022-11-07 09:01

from django.db import migrations, models

import peachjam.models.attachments
import peachjam.storage


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0034_dynamic_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachedfiles",
            name="file",
            field=peachjam.storage.DynamicStorageFileField(
                max_length=1024,
                upload_to=peachjam.models.attachments.file_location,
            ),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="additional_citations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="flynote",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="headnote_holding",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sourcefile",
            name="file",
            field=peachjam.storage.DynamicStorageFileField(
                max_length=1024,
                upload_to=peachjam.models.attachments.file_location,
            ),
        ),
    ]
