# Generated by Django 3.2.14 on 2022-11-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0035_judgment_field_nulls"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlternativeName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1024)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternative_names",
                        to="peachjam.coredocument",
                    ),
                ),
            ],
        ),
    ]
