# Generated by Django 3.2.16 on 2022-11-22 09:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0036_doc_alternative_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=3), default=[], size=None
            ),
            preserve_default=False,
        ),
    ]
