# Generated by Django 3.2.14 on 2022-11-11 07:42

import django.db.models.deletion
from django.db import migrations, models

import peachjam.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("peachjam", "0036_doc_alternative_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_html", models.TextField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=peachjam.models.profile.entity_profile_photo_filename,
                    ),
                ),
                (
                    "background_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=peachjam.models.profile.entity_profile_photo_filename,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Profile",
                "unique_together": {("content_type", "object_id")},
            },
        ),
    ]
