# Generated by Django 3.2.16 on 2022-11-23 08:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0038_entity_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=3), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("core_document", "Core Document"),
                    ("gazette", "Gazette"),
                    ("generic_document", "Generic Document"),
                    ("judgment", "Judgment"),
                    ("legal_instrument", "Legal Instrument"),
                    ("legislation", "Legislation"),
                ],
                default="core_document",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="frbr_uri_doctype",
            field=models.CharField(
                choices=[
                    ("act", "act"),
                    ("doc", "doc"),
                    ("judgment", "judgment"),
                    ("statement", "statement"),
                    ("officialGazette", "officialGazette"),
                ],
                max_length=20,
            ),
        ),
    ]
