# Generated by Django 3.2.16 on 2022-11-23 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0038_entity_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "coredocument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="peachjam.coredocument",
                    ),
                ),
                ("publisher", models.CharField(max_length=2048)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("peachjam.coredocument",),
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "coredocument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="peachjam.coredocument",
                    ),
                ),
                ("publisher", models.CharField(max_length=2048)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("peachjam.coredocument",),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("core_document", "Core Document"),
                    ("gazette", "Gazette"),
                    ("generic_document", "Generic Document"),
                    ("judgment", "Judgment"),
                    ("legal_instrument", "Legal Instrument"),
                    ("legislation", "Legislation"),
                    ("book", "Book"),
                    ("journal", "Journal"),
                ],
                default="core_document",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="frbr_uri_doctype",
            field=models.CharField(
                choices=[
                    ("act", "act"),
                    ("doc", "doc"),
                    ("judgment", "judgment"),
                    ("statement", "statement"),
                    ("officialGazette", "officialGazette"),
                ],
                max_length=20,
            ),
        ),
    ]
