# Generated by Django 3.2.16 on 2022-12-05 10:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0039_books_journals"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=3), default=list, size=None
            ),
        ),
    ]
