# Generated by Django 3.2.16 on 2022-12-01 11:54

from django.db import migrations


def backfill_work_languages(apps, schema_editor):
    CoreDocument = apps.get_model("peachjam", "CoreDocument")
    for doc in CoreDocument.objects.all():
        Work = apps.get_model("peachjam", "Work")
        work = Work.objects.get(frbr_uri=doc.work_frbr_uri)
        if doc.language.iso_639_3 not in work.languages:
            work.languages.append(doc.language.iso_639_3)
            work.save()


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0039_auto_20221123_0821"),
    ]

    operations = [
        migrations.RunPython(backfill_work_languages, migrations.RunPython.noop),
    ]
