# Generated by Django 3.2.15 on 2022-12-05 10:49

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import peachjam.frbr_uri
import peachjam.models.article
import peachjam.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("countries_plus", "0005_auto_20160224_1804"),
        ("languages_plus", "0004_auto_20171214_0004"),
        ("peachjam", "0041_backfill_work_languages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alternativename",
            options={
                "verbose_name": "alternative name",
                "verbose_name_plural": "alternative names",
            },
        ),
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "article", "verbose_name_plural": "articles"},
        ),
        migrations.AlterModelOptions(
            name="attachedfilenature",
            options={
                "verbose_name": "attached file nature",
                "verbose_name_plural": "attached file natures",
            },
        ),
        migrations.AlterModelOptions(
            name="attachedfiles",
            options={
                "verbose_name": "attached file",
                "verbose_name_plural": "attached files",
            },
        ),
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ["name"],
                "verbose_name": "author",
                "verbose_name_plural": "authors",
            },
        ),
        migrations.AlterModelOptions(
            name="casenumber",
            options={
                "ordering": ["string"],
                "verbose_name": "case number",
                "verbose_name_plural": "case numbers",
            },
        ),
        migrations.AlterModelOptions(
            name="citationlink",
            options={
                "verbose_name": "citation link",
                "verbose_name_plural": "citation links",
            },
        ),
        migrations.AlterModelOptions(
            name="court",
            options={
                "ordering": ("name",),
                "verbose_name": "court",
                "verbose_name_plural": "courts",
            },
        ),
        migrations.AlterModelOptions(
            name="courtclass",
            options={
                "ordering": ("name",),
                "verbose_name": "court class",
                "verbose_name_plural": "court classes",
            },
        ),
        migrations.AlterModelOptions(
            name="documentnature",
            options={
                "verbose_name": "document nature",
                "verbose_name_plural": "document natures",
            },
        ),
        migrations.AlterModelOptions(
            name="documenttopic",
            options={
                "ordering": ["topic"],
                "verbose_name": "document topic",
                "verbose_name_plural": "document topics",
            },
        ),
        migrations.AlterModelOptions(
            name="entityprofile",
            options={"verbose_name": "profile", "verbose_name_plural": "profile"},
        ),
        migrations.AlterModelOptions(
            name="gazette",
            options={
                "base_manager_name": "objects",
                "verbose_name": "gazette",
                "verbose_name_plural": "gazettes",
            },
        ),
        migrations.AlterModelOptions(
            name="genericdocument",
            options={
                "base_manager_name": "objects",
                "verbose_name": "generic document",
                "verbose_name_plural": "generic documents",
            },
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "image", "verbose_name_plural": "images"},
        ),
        migrations.AlterModelOptions(
            name="ingestor",
            options={"verbose_name": "ingestor", "verbose_name_plural": "ingestor"},
        ),
        migrations.AlterModelOptions(
            name="ingestorsetting",
            options={
                "verbose_name": "ingestor setting",
                "verbose_name_plural": "ingestor settings",
            },
        ),
        migrations.AlterModelOptions(
            name="judge",
            options={
                "ordering": ["name"],
                "verbose_name": "judge",
                "verbose_name_plural": "judges",
            },
        ),
        migrations.AlterModelOptions(
            name="judgment",
            options={
                "base_manager_name": "objects",
                "ordering": ["title"],
                "verbose_name": "judgment",
                "verbose_name_plural": "judgments",
            },
        ),
        migrations.AlterModelOptions(
            name="legalinstrument",
            options={
                "base_manager_name": "objects",
                "verbose_name": "legal instrument",
                "verbose_name_plural": "legal instruments",
            },
        ),
        migrations.AlterModelOptions(
            name="legislation",
            options={
                "base_manager_name": "objects",
                "verbose_name": "legislation",
                "verbose_name_plural": "legislation",
            },
        ),
        migrations.AlterModelOptions(
            name="locality",
            options={
                "ordering": ["name"],
                "verbose_name": "locality",
                "verbose_name_plural": "localities",
            },
        ),
        migrations.AlterModelOptions(
            name="mattertype",
            options={
                "ordering": ["name"],
                "verbose_name": "matter type",
                "verbose_name_plural": "matter types",
            },
        ),
        migrations.AlterModelOptions(
            name="predicate",
            options={
                "ordering": ("name",),
                "verbose_name": "predicate",
                "verbose_name_plural": "predicates",
            },
        ),
        migrations.AlterModelOptions(
            name="relationship",
            options={"verbose_name": "predicate", "verbose_name_plural": "predicates"},
        ),
        migrations.AlterModelOptions(
            name="sourcefile",
            options={
                "verbose_name": "source file",
                "verbose_name_plural": "source files",
            },
        ),
        migrations.AlterModelOptions(
            name="taxonomy",
            options={"verbose_name": "taxonomies", "verbose_name_plural": "taxonomies"},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="work",
            options={
                "ordering": ["title"],
                "verbose_name": "work",
                "verbose_name_plural": "works",
            },
        ),
        migrations.AlterField(
            model_name="alternativename",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alternative_names",
                to="peachjam.coredocument",
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="alternativename",
            name="title",
            field=models.CharField(max_length=1024, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="body",
            field=models.TextField(verbose_name="body"),
        ),
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateField(verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=peachjam.models.article.file_location,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=1024, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=models.TextField(verbose_name="summary"),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=1024, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="article",
            name="topics",
            field=models.ManyToManyField(to="peachjam.Taxonomy", verbose_name="topics"),
        ),
        migrations.AlterField(
            model_name="attachedfilenature",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="attachedfilenature",
            name="name",
            field=models.CharField(max_length=1024, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="attachedfiles",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="peachjam.coredocument",
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="attachedfiles",
            name="file",
            field=peachjam.storage.DynamicStorageFileField(
                max_length=1024,
                upload_to=peachjam.models.attachments.file_location,
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="attachedfiles",
            name="filename",
            field=models.CharField(max_length=1024, verbose_name="filename"),
        ),
        migrations.AlterField(
            model_name="attachedfiles",
            name="mimetype",
            field=models.CharField(max_length=1024, verbose_name="mimetype"),
        ),
        migrations.AlterField(
            model_name="attachedfiles",
            name="nature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="peachjam.attachedfilenature",
                verbose_name="nature",
            ),
        ),
        migrations.AlterField(
            model_name="attachedfiles",
            name="size",
            field=models.BigIntegerField(default=0, verbose_name="size"),
        ),
        migrations.AlterField(
            model_name="author",
            name="code",
            field=models.SlugField(max_length=255, unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="casenumber",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_numbers",
                to="peachjam.judgment",
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="casenumber",
            name="matter_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="peachjam.mattertype",
                verbose_name="matter type",
            ),
        ),
        migrations.AlterField(
            model_name="casenumber",
            name="number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="number"
            ),
        ),
        migrations.AlterField(
            model_name="casenumber",
            name="string",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="string"
            ),
        ),
        migrations.AlterField(
            model_name="casenumber",
            name="string_override",
            field=models.CharField(
                blank=True,
                help_text="Override for full case number string",
                max_length=1024,
                null=True,
                verbose_name="string override",
            ),
        ),
        migrations.AlterField(
            model_name="casenumber",
            name="year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="year"
            ),
        ),
        migrations.AlterField(
            model_name="citationlink",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="citation_links",
                to="peachjam.coredocument",
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="citationlink",
            name="target_id",
            field=models.CharField(max_length=1024, verbose_name="target id"),
        ),
        migrations.AlterField(
            model_name="citationlink",
            name="target_selectors",
            field=models.JSONField(verbose_name="target selectors"),
        ),
        migrations.AlterField(
            model_name="citationlink",
            name="text",
            field=models.TextField(verbose_name="text"),
        ),
        migrations.AlterField(
            model_name="citationlink",
            name="url",
            field=models.URLField(max_length=1024, verbose_name="url"),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="citation",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="citation"
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="content_html",
            field=models.TextField(blank=True, null=True, verbose_name="content HTML"),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="content_html_is_akn",
            field=models.BooleanField(
                default=False, verbose_name="content HTML is AKN"
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="date",
            field=models.DateField(verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("core_document", "Core Document"),
                    ("gazette", "Gazette"),
                    ("generic_document", "Generic Document"),
                    ("judgment", "Judgment"),
                    ("legal_instrument", "Legal Instrument"),
                    ("legislation", "Legislation"),
                    ("book", "Book"),
                    ("journal", "Journal"),
                ],
                default="core_document",
                max_length=255,
                verbose_name="document type",
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="expression_frbr_uri",
            field=models.CharField(
                max_length=1024, unique=True, verbose_name="expression FRBR URI"
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="frbr_uri_actor",
            field=models.CharField(
                blank=True,
                help_text="Originating actor. Lowercase letters, numbers _ and - only.",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9_-]+$",
                        "Only lowercase letters, numbers, _ and - allowed",
                    )
                ],
                verbose_name="FRBR URI actor",
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="frbr_uri_date",
            field=models.CharField(
                help_text="YYYY, YYYY-MM, or YYYY-MM-DD",
                max_length=10,
                validators=[peachjam.frbr_uri.validate_frbr_uri_date],
                verbose_name="FRBR URI date",
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="frbr_uri_doctype",
            field=models.CharField(
                choices=[
                    ("act", "act"),
                    ("doc", "doc"),
                    ("judgment", "judgment"),
                    ("statement", "statement"),
                    ("officialGazette", "officialGazette"),
                ],
                max_length=20,
                verbose_name="FRBR URI doctype",
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="frbr_uri_number",
            field=models.CharField(
                help_text="Unique number or short title identifying this work. Lowercase letters, numbers _ and - only.",
                max_length=1024,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9_-]+$",
                        "Only lowercase letters, numbers, _ and - allowed",
                    )
                ],
                verbose_name="FRBR URI number",
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="frbr_uri_subtype",
            field=models.CharField(
                blank=True,
                help_text="Document subtype. Lowercase letters, numbers _ and - only.",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9_-]+$",
                        "Only lowercase letters, numbers, _ and - allowed",
                    )
                ],
                verbose_name="FRBR URI subtype",
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="jurisdiction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="countries_plus.country",
                verbose_name="jurisdiction",
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="languages_plus.language",
                verbose_name="language",
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="locality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="peachjam.locality",
                verbose_name="locality",
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="source_url",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="source URL"
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="title",
            field=models.CharField(max_length=1024, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="toc_json",
            field=models.JSONField(blank=True, null=True, verbose_name="TOC JSON"),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="peachjam.work",
                verbose_name="work",
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="work_frbr_uri",
            field=models.CharField(max_length=1024, verbose_name="work FRBR URI"),
        ),
        migrations.AlterField(
            model_name="court",
            name="code",
            field=models.SlugField(max_length=255, unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="court",
            name="court_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courts",
                to="peachjam.courtclass",
                verbose_name="court class",
            ),
        ),
        migrations.AlterField(
            model_name="court",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="courtclass",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="courtclass",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="documentnature",
            name="code",
            field=models.SlugField(max_length=1024, unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="documentnature",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="documentnature",
            name="name",
            field=models.CharField(max_length=1024, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="documenttopic",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taxonomies",
                to="peachjam.coredocument",
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="documenttopic",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="peachjam.taxonomy",
                verbose_name="topic",
            ),
        ),
        migrations.AlterField(
            model_name="entityprofile",
            name="about_html",
            field=models.TextField(blank=True, null=True, verbose_name="about HTML"),
        ),
        migrations.AlterField(
            model_name="entityprofile",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="entityprofile",
            name="background_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=peachjam.models.profile.entity_profile_photo_filename,
                verbose_name="background photo",
            ),
        ),
        migrations.AlterField(
            model_name="entityprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=peachjam.models.profile.entity_profile_photo_filename,
                verbose_name="profile photo",
            ),
        ),
        migrations.AlterField(
            model_name="entityprofile",
            name="website_url",
            field=models.URLField(blank=True, null=True, verbose_name="website URL"),
        ),
        migrations.AlterField(
            model_name="genericdocument",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="peachjam.author",
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="genericdocument",
            name="nature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="peachjam.documentnature",
                verbose_name="nature",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="peachjam.coredocument",
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                max_length=1024,
                upload_to=peachjam.models.attachments.file_location,
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="filename",
            field=models.CharField(max_length=1024, verbose_name="filename"),
        ),
        migrations.AlterField(
            model_name="image",
            name="mimetype",
            field=models.CharField(max_length=1024, verbose_name="mimetype"),
        ),
        migrations.AlterField(
            model_name="image",
            name="size",
            field=models.BigIntegerField(default=0, verbose_name="size"),
        ),
        migrations.AlterField(
            model_name="ingestor",
            name="adapter",
            field=models.CharField(max_length=2048, verbose_name="adapter"),
        ),
        migrations.AlterField(
            model_name="ingestor",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="enabled"),
        ),
        migrations.AlterField(
            model_name="ingestor",
            name="last_refreshed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last refreshed at"
            ),
        ),
        migrations.AlterField(
            model_name="ingestor",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="ingestorsetting",
            name="ingestor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="peachjam.ingestor",
                verbose_name="ingestor",
            ),
        ),
        migrations.AlterField(
            model_name="ingestorsetting",
            name="name",
            field=models.CharField(max_length=2048, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="ingestorsetting",
            name="value",
            field=models.CharField(max_length=2048, verbose_name="value"),
        ),
        migrations.AlterField(
            model_name="judge",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="judge",
            name="name",
            field=models.CharField(max_length=1024, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="additional_citations",
            field=models.TextField(
                blank=True, null=True, verbose_name="additional citations"
            ),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="case_name",
            field=models.CharField(
                help_text="Party names for use in title",
                max_length=4096,
                verbose_name="case name",
            ),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="court",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="peachjam.court",
                verbose_name="court",
            ),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="flynote",
            field=models.TextField(blank=True, null=True, verbose_name="flynote"),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="headnote_holding",
            field=models.TextField(
                blank=True, null=True, verbose_name="headnote holding"
            ),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="judges",
            field=models.ManyToManyField(
                blank=True,
                through="peachjam.Bench",
                to="peachjam.Judge",
                verbose_name="judges",
            ),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="mnc",
            field=models.CharField(
                help_text="Media neutral citation", max_length=4096, verbose_name="MNC"
            ),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="serial_number",
            field=models.IntegerField(
                help_text="Serial number for MNC, unique for a year and an author.",
                verbose_name="serial number",
            ),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="serial_number_override",
            field=models.IntegerField(
                blank=True,
                help_text="Specific MNC serial number assigned by the court.",
                null=True,
                verbose_name="serial number override",
            ),
        ),
        migrations.AlterField(
            model_name="legalinstrument",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="peachjam.author",
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="legalinstrument",
            name="nature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="peachjam.documentnature",
                verbose_name="nature",
            ),
        ),
        migrations.AlterField(
            model_name="legislation",
            name="metadata_json",
            field=models.JSONField(verbose_name="metadata JSON"),
        ),
        migrations.AlterField(
            model_name="legislation",
            name="parent_work",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="peachjam.work",
                verbose_name="parent work",
            ),
        ),
        migrations.AlterField(
            model_name="legislation",
            name="repealed",
            field=models.BooleanField(default=False, verbose_name="repealed"),
        ),
        migrations.AlterField(
            model_name="locality",
            name="code",
            field=models.CharField(max_length=20, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="locality",
            name="jurisdiction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="countries_plus.country",
                verbose_name="jurisdiction",
            ),
        ),
        migrations.AlterField(
            model_name="locality",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="mattertype",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="mattertype",
            name="name",
            field=models.CharField(max_length=1024, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="peachjamsettings",
            name="default_document_language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="languages_plus.language",
                verbose_name="default document language",
            ),
        ),
        migrations.AlterField(
            model_name="peachjamsettings",
            name="document_jurisdictions",
            field=models.ManyToManyField(
                blank=True,
                related_name="_peachjam_peachjamsettings_document_jurisdictions_+",
                to="countries_plus.Country",
                verbose_name="document jurisdictions",
            ),
        ),
        migrations.AlterField(
            model_name="peachjamsettings",
            name="document_languages",
            field=models.ManyToManyField(
                blank=True,
                related_name="_peachjam_peachjamsettings_document_languages_+",
                to="languages_plus.Language",
                verbose_name="document languages",
            ),
        ),
        migrations.AlterField(
            model_name="predicate",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="predicate",
            name="reverse_verb",
            field=models.CharField(
                help_text="Reversed verbal form of the relationship",
                max_length=100,
                verbose_name="reverse verb",
            ),
        ),
        migrations.AlterField(
            model_name="predicate",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="predicate",
            name="verb",
            field=models.CharField(max_length=100, verbose_name="verb"),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="object_target_id",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="object target ID"
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="object_work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="peachjam.work",
                verbose_name="object work",
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="predicate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="peachjam.predicate",
                verbose_name="predicate",
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="subject_target_id",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="subject target ID"
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="subject_work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="peachjam.work",
                verbose_name="subject work",
            ),
        ),
        migrations.AlterField(
            model_name="sourcefile",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_file",
                to="peachjam.coredocument",
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="sourcefile",
            name="file",
            field=peachjam.storage.DynamicStorageFileField(
                max_length=1024,
                upload_to=peachjam.models.attachments.file_location,
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="sourcefile",
            name="filename",
            field=models.CharField(max_length=1024, verbose_name="filename"),
        ),
        migrations.AlterField(
            model_name="sourcefile",
            name="mimetype",
            field=models.CharField(max_length=1024, verbose_name="mimetype"),
        ),
        migrations.AlterField(
            model_name="sourcefile",
            name="size",
            field=models.BigIntegerField(default=0, verbose_name="size"),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=peachjam.models.article.file_location,
                verbose_name="photo",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_description",
            field=models.TextField(verbose_name="profile description"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="frbr_uri",
            field=models.CharField(
                max_length=1024, unique=True, verbose_name="FRBR URI"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=3),
                default=list,
                size=None,
                verbose_name="languages",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="title",
            field=models.CharField(max_length=1024, verbose_name="title"),
        ),
    ]
