# Generated by Django 3.2.16 on 2023-01-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0042_i18n_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="coredocument",
            name="allow_robots",
            field=models.BooleanField(default=True, verbose_name="allow robots"),
        ),
    ]
