# Generated by Django 3.2.16 on 2023-01-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0042_i18n_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachedfiles",
            name="source_url",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="source URL"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="source_url",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="source URL"
            ),
        ),
        migrations.AddField(
            model_name="sourcefile",
            name="source_url",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="source URL"
            ),
        ),
    ]
