# Generated by Django 3.2.16 on 2023-01-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0043_coredocument_allow_robots"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcefile",
            name="source_url",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="source URL"
            ),
        ),
    ]
