# Generated by Django 3.2.16 on 2023-01-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0044_sourcefile_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="subleg_label",
            field=models.CharField(
                default="Subsidiary legislation",
                max_length=1024,
                verbose_name="subsidiary legislation label",
            ),
        ),
    ]
