# Generated by Django 3.2.16 on 2023-01-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0045_peachjamsettings_subleg_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coredocument",
            name="date",
            field=models.DateField(db_index=True, verbose_name="date"),
        ),
    ]
