# Generated by Django 3.2.17 on 2023-02-10 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0046_alter_coredocument_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractedCitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "citing_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citing_work",
                        to="peachjam.work",
                        verbose_name="citing work",
                    ),
                ),
                (
                    "target_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_work",
                        to="peachjam.work",
                        verbose_name="target work",
                    ),
                ),
            ],
        ),
    ]
