# Generated by Django 3.2.16 on 2023-02-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0047_coredocument_new_nature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genericdocument",
            name="nature",
        ),
        migrations.RemoveField(
            model_name="legalinstrument",
            name="nature",
        ),
    ]
