# Generated by Django 3.2.16 on 2023-02-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0048_remove_document_nature"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coredocument",
            old_name="new_nature",
            new_name="nature",
        ),
    ]
