# Generated by Django 3.2.16 on 2023-02-10 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0051_backfill_extracted_citations"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="document text"
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_content",
                        to="peachjam.coredocument",
                        verbose_name="document",
                    ),
                ),
            ],
            options={
                "verbose_name": "document content",
                "verbose_name_plural": "document contents",
            },
        ),
    ]
