# Generated by Django 3.2.18 on 2023-02-21 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0053_externaldocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="name")),
                (
                    "court",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peachjam.court",
                        verbose_name="court",
                    ),
                ),
            ],
            options={
                "verbose_name": "registry",
                "verbose_name_plural": "registries",
            },
        ),
    ]
