# Generated by Django 3.2.18 on 2023-02-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0054_courtregistry"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="registry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="peachjam.courtregistry",
            ),
        ),
    ]
