# Generated by Django 3.2.18 on 2023-02-24 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0055_judgment_registry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courtregistry",
            options={
                "verbose_name": "court registry",
                "verbose_name_plural": "court registries",
            },
        ),
        migrations.AddField(
            model_name="courtregistry",
            name="code",
            field=models.SlugField(
                default="-", max_length=255, unique=True, verbose_name="code"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="courtregistry",
            name="court",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registries",
                to="peachjam.court",
                verbose_name="court",
            ),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="registry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="judgments",
                to="peachjam.courtregistry",
            ),
        ),
    ]
