# Generated by Django 3.2.18 on 2023-02-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0056_auto_20230224_0740"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courtregistry",
            name="code",
            field=models.SlugField(
                editable=False, max_length=255, unique=True, verbose_name="code"
            ),
        ),
    ]
