# Generated by Django 3.2.18 on 2023-02-27 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0058_alter_courtregistry_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attorney",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "attorney",
                "verbose_name_plural": "attorneys",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="judgment",
            name="registry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="judgments",
                to="peachjam.courtregistry",
            ),
        ),
    ]
