# Generated by Django 3.2.18 on 2023-02-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0059_auto_20230227_1209"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="attorneys",
            field=models.ManyToManyField(
                blank=True, to="peachjam.Attorney", verbose_name="attorneys"
            ),
        ),
    ]
