# Generated by Django 3.2.18 on 2023-03-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0060_judgment_attorneys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attorney",
            name="name",
            field=models.CharField(max_length=1024, unique=True, verbose_name="name"),
        ),
    ]
