# Generated by Django 3.2.16 on 2023-03-13 08:44

from django.db import migrations


def backfill_size(apps, schema_editor):
    SourceFile = apps.get_model("peachjam", "SourceFile")
    Image = apps.get_model("peachjam", "Image")
    AttachedFiles = apps.get_model("peachjam", "AttachedFiles")

    for cls in [SourceFile, Image, AttachedFiles]:
        for f in cls.objects.filter(size=0).iterator(100):
            f.size = f.file.size
            f.save(update_fields=["size"])


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0061_alter_attorney_name"),
    ]

    operations = [migrations.RunPython(backfill_size, migrations.RunPython.noop)]
