# Generated by Django 3.2.16 on 2023-04-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0063_peachjamsettings_google_analytics_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="rank",
            field=models.FloatField(default=0.0, null=True, verbose_name="rank"),
        ),
    ]
