# Generated by Django 3.2.18 on 2023-04-03 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0063_peachjamsettings_google_analytics_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "order_outcome",
                "verbose_name_plural": "order_outcomes",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="judgment",
            name="order_outcome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_outcome",
                to="peachjam.orderoutcome",
            ),
        ),
    ]
