# Generated by Django 3.2.16 on 2023-04-11 18:54

from django.db import migrations


def update_ingestor_settings(apps, schema_editor):
    Ingestor = apps.get_model("peachjam", "Ingestor")
    IngestorSetting = apps.get_model("peachjam", "IngestorSetting")

    for ingestor in Ingestor.objects.all():
        setting = IngestorSetting.objects.filter(ingestor=ingestor, name="url").first()
        if setting:
            values = setting.value.split("/")
            place_code = values[5].split("-")
            IngestorSetting.objects.create(
                ingestor=ingestor, name="api_url", value="http://api.laws.africa/v2"
            )
            IngestorSetting.objects.create(
                ingestor=ingestor, name="jurisdiction", value=place_code[0]
            )
            if len(place_code) > 1:
                IngestorSetting.objects.create(
                    ingestor=ingestor, name="locality", value=place_code[1]
                )


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0064_auto_20230403_0448"),
    ]

    operations = [
        migrations.RunPython(update_ingestor_settings, migrations.RunPython.noop)
    ]
