# Generated by Django 3.2.18 on 2023-04-25 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0065_update_ingestor_settings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="court",
            options={
                "ordering": ("order", "name"),
                "verbose_name": "court",
                "verbose_name_plural": "courts",
            },
        ),
        migrations.AlterModelOptions(
            name="orderoutcome",
            options={
                "ordering": ["name"],
                "verbose_name": "order outcome",
                "verbose_name_plural": "order outcomes",
            },
        ),
        migrations.AddField(
            model_name="court",
            name="order",
            field=models.IntegerField(blank=True, null=True, verbose_name="order"),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="order_outcome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="judgments",
                to="peachjam.orderoutcome",
            ),
        ),
    ]
