# Generated by Django 3.2.16 on 2023-04-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0067_auto_20230425_1131"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="rank",
            field=models.FloatField(default=0.0, null=True, verbose_name="rank"),
        ),
    ]
