# Generated by Django 3.2.16 on 2023-05-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0068_work_rank"),
    ]

    operations = [
        migrations.RenameField(
            model_name="work",
            old_name="rank",
            new_name="ranking",
        ),
    ]
