# Generated by Django 3.2.16 on 2023-05-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0069_rename_rank_work_ranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="ranking",
            field=models.FloatField(default=0.0, null=True, verbose_name="ranking"),
        ),
    ]
