# Generated by Django 3.2.18 on 2023-05-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0071_africanunionorgan_memberstate_regionaleconomiccommunity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberstate",
            name="code",
        ),
    ]
