# Generated by Django 3.2.16 on 2023-05-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0072_backfill_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="pagerank_boost_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="pagerank boost value"
            ),
        ),
    ]
