# Generated by Django 3.2.18 on 2023-05-16 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0073_peachjamsettings_pagerank_boost_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericdocument",
            name="authors",
            field=models.ManyToManyField(
                blank=True, to="peachjam.Author", verbose_name="authors"
            ),
        ),
        migrations.AddField(
            model_name="legalinstrument",
            name="authors",
            field=models.ManyToManyField(
                blank=True, to="peachjam.Author", verbose_name="authors"
            ),
        ),
        migrations.AlterField(
            model_name="genericdocument",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generic_documents",
                to="peachjam.author",
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="legalinstrument",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legal_instruments",
                to="peachjam.author",
                verbose_name="author",
            ),
        ),
    ]
