# Generated by Django 3.2.18 on 2023-05-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0073_peachjamsettings_pagerank_boost_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genericdocument",
            name="author",
        ),
        migrations.AddField(
            model_name="genericdocument",
            name="authors",
            field=models.ManyToManyField(
                blank=True, to="peachjam.Author", verbose_name="authors"
            ),
        ),
    ]
