# Generated by Django 3.2.18 on 2023-05-16 11:30

from django.db import migrations


def backfill_authors(apps, schema_editor):
    GenericDocument = apps.get_model("peachjam", "GenericDocument")
    for generic_document in (
        GenericDocument.objects.only("author")
        .exclude(author=None)
        .all()
        .iterator(chunk_size=100)
    ):
        generic_document.authors.set([generic_document.author])
        generic_document.save()


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0074_auto_20230516_1128"),
    ]

    operations = [migrations.RunPython(backfill_authors, migrations.RunPython.noop)]
