# Generated by Django 3.2.18 on 2023-05-16 11:30

from django.db import migrations


def backfill_authors(apps, schema_editor):
    CoreDocument = apps.get_model("peachjam", "CoreDocument")
    for doc in CoreDocument.objects.all().iterator(chunk_size=100):
        if doc.author not in doc.authors:
            doc.authors.append(doc.author)
            doc.save()


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0074_auto_20230516_1128"),
    ]

    operations = [migrations.RunPython(backfill_authors, migrations.RunPython.noop)]
