# Generated by Django 3.2.18 on 2023-05-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0074_auto_20230511_1940"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="legalinstrument",
            name="author",
        ),
        migrations.AddField(
            model_name="legalinstrument",
            name="authors",
            field=models.ManyToManyField(
                blank=True, to="peachjam.Author", verbose_name="authors"
            ),
        ),
    ]
