# Generated by Django 3.2.18 on 2023-05-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0075_backfill_authors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genericdocument",
            name="author",
        ),
        migrations.RemoveField(
            model_name="legalinstrument",
            name="author",
        ),
    ]
