# Generated by Django 3.2.16 on 2023-05-19 18:04
from cobalt.uri import FrbrUri
from django.db import migrations, models


def backfill(apps, schema_editor):
    Work = apps.get_model("peachjam", "Work")
    for work in Work.objects.all():
        frbr_uri = FrbrUri.parse(work.frbr_uri)
        work.frbr_uri_country = frbr_uri.country
        work.frbr_uri_locality = frbr_uri.locality
        work.frbr_uri_place = frbr_uri.place
        work.frbr_uri_doctype = frbr_uri.doctype
        work.frbr_uri_subtype = frbr_uri.subtype
        work.frbr_uri_actor = frbr_uri.actor
        work.frbr_uri_date = frbr_uri.date
        work.frbr_uri_number = frbr_uri.number
        work.save()


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0076_auto_20230516_1137"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="frbr_uri_actor",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="FRBR URI actor"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="frbr_uri_country",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="FRBR URI country"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="frbr_uri_date",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="FRBR URI date"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="frbr_uri_doctype",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="FRBR URI doctype"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="frbr_uri_locality",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="FRBR URI locality"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="frbr_uri_number",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="FRBR URI number"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="frbr_uri_place",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="FRBR URI place"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="frbr_uri_subtype",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="FRBR URI subtype"
            ),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
