# Generated by Django 3.2.19 on 2023-05-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0076_auto_20230516_1137"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="metabase_dashboard_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="metabase dashboard link"
            ),
        ),
    ]
