# Generated by Django 3.2.16 on 2023-05-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0077_add_work_frbr_uri_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="frbr_uri_country",
            field=models.CharField(max_length=2, verbose_name="FRBR URI country"),
        ),
        migrations.AlterField(
            model_name="work",
            name="frbr_uri_date",
            field=models.CharField(max_length=10, verbose_name="FRBR URI date"),
        ),
        migrations.AlterField(
            model_name="work",
            name="frbr_uri_doctype",
            field=models.CharField(max_length=20, verbose_name="FRBR URI doctype"),
        ),
        migrations.AlterField(
            model_name="work",
            name="frbr_uri_number",
            field=models.CharField(max_length=1024, verbose_name="FRBR URI number"),
        ),
        migrations.AlterField(
            model_name="work",
            name="frbr_uri_place",
            field=models.CharField(max_length=100, verbose_name="FRBR URI place"),
        ),
    ]
