# Generated by Django 3.2.16 on 2023-05-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0078_make_work_frbr_uri_fields_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="topics",
            field=models.ManyToManyField(
                blank=True, to="peachjam.Taxonomy", verbose_name="topics"
            ),
        ),
    ]
