# Generated by Django 3.2.16 on 2023-05-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0078_make_work_frbr_uri_fields_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="allowed_login_domains",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="allowed login domains",
            ),
        ),
    ]
