# Generated by Django 3.2.16 on 2023-05-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0079_peachjamsettings_allowed_login_domains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="topics",
            field=models.ManyToManyField(
                blank=True, to="peachjam.Taxonomy", verbose_name="topics"
            ),
        ),
    ]
