# Generated by Django 3.2.19 on 2023-05-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0081_alter_coredocument_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="metabase_dashboard_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="metabase dashboard link"
            ),
        ),
    ]
