# Generated by Django 3.2.19 on 2023-06-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0083_alter_article_summary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coredocument",
            options={
                "ordering": ["doc_type", "title"],
                "permissions": [
                    ("can_delete_own_document", "Can delete own document"),
                    ("can_edit_own_document", "Can edit own document"),
                ],
            },
        ),
    ]
