# Generated by Django 3.2.19 on 2023-06-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0083_alter_article_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitationProcessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="processing date"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
