# Generated by Django 3.2.19 on 2023-06-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0084_alter_coredocument_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitationProcessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="processing date"
                    ),
                ),
            ],
            options={
                "verbose_name": "citation processing",
                "verbose_name_plural": "citation processing",
            },
        ),
        migrations.AddField(
            model_name="peachjamsettings",
            name="re_extract_citations",
            field=models.BooleanField(
                default=True, verbose_name="re-extract citations"
            ),
        ),
    ]
