# Generated by Django 3.2.19 on 2023-06-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0087_article_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachedfilenature",
            name="name_en",
            field=models.CharField(
                max_length=1024, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="attachedfilenature",
            name="name_fr",
            field=models.CharField(
                max_length=1024, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="attachedfilenature",
            name="name_pt",
            field=models.CharField(
                max_length=1024, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="attachedfilenature",
            name="name_sw",
            field=models.CharField(
                max_length=1024, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="court",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="court",
            name="name_fr",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="court",
            name="name_pt",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="court",
            name="name_sw",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="courtclass",
            name="name_en",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="courtclass",
            name="name_fr",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="courtclass",
            name="name_pt",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="courtclass",
            name="name_sw",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="courtregistry",
            name="name_en",
            field=models.CharField(max_length=1024, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="courtregistry",
            name="name_fr",
            field=models.CharField(max_length=1024, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="courtregistry",
            name="name_pt",
            field=models.CharField(max_length=1024, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="courtregistry",
            name="name_sw",
            field=models.CharField(max_length=1024, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="documentnature",
            name="name_en",
            field=models.CharField(
                max_length=1024, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="documentnature",
            name="name_fr",
            field=models.CharField(
                max_length=1024, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="documentnature",
            name="name_pt",
            field=models.CharField(
                max_length=1024, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="documentnature",
            name="name_sw",
            field=models.CharField(
                max_length=1024, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="orderoutcome",
            name="name_en",
            field=models.CharField(max_length=1024, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="orderoutcome",
            name="name_fr",
            field=models.CharField(max_length=1024, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="orderoutcome",
            name="name_pt",
            field=models.CharField(max_length=1024, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="orderoutcome",
            name="name_sw",
            field=models.CharField(max_length=1024, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="predicate",
            name="reverse_verb_en",
            field=models.CharField(
                help_text="Reversed verbal form of the relationship",
                max_length=100,
                null=True,
                verbose_name="reverse verb",
            ),
        ),
        migrations.AddField(
            model_name="predicate",
            name="reverse_verb_fr",
            field=models.CharField(
                help_text="Reversed verbal form of the relationship",
                max_length=100,
                null=True,
                verbose_name="reverse verb",
            ),
        ),
        migrations.AddField(
            model_name="predicate",
            name="reverse_verb_pt",
            field=models.CharField(
                help_text="Reversed verbal form of the relationship",
                max_length=100,
                null=True,
                verbose_name="reverse verb",
            ),
        ),
        migrations.AddField(
            model_name="predicate",
            name="reverse_verb_sw",
            field=models.CharField(
                help_text="Reversed verbal form of the relationship",
                max_length=100,
                null=True,
                verbose_name="reverse verb",
            ),
        ),
        migrations.AddField(
            model_name="predicate",
            name="verb_en",
            field=models.CharField(max_length=100, null=True, verbose_name="verb"),
        ),
        migrations.AddField(
            model_name="predicate",
            name="verb_fr",
            field=models.CharField(max_length=100, null=True, verbose_name="verb"),
        ),
        migrations.AddField(
            model_name="predicate",
            name="verb_pt",
            field=models.CharField(max_length=100, null=True, verbose_name="verb"),
        ),
        migrations.AddField(
            model_name="predicate",
            name="verb_sw",
            field=models.CharField(max_length=100, null=True, verbose_name="verb"),
        ),
        migrations.AddField(
            model_name="taxonomy",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="taxonomy",
            name="name_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="taxonomy",
            name="name_pt",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="taxonomy",
            name="name_sw",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
    ]
