# Generated by Django 3.2.16 on 2023-07-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0089_alter_judge_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citationlink",
            name="url",
            field=models.CharField(max_length=1024, verbose_name="url"),
        ),
    ]
