# Generated by Django 3.2.16 on 2023-07-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0090_alter_citationlink_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="mailchimp_form_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="mailchimp form url"
            ),
        ),
    ]
