# Generated by Django 3.2.16 on 2023-07-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0091_peachjamsettings_mailchimp_form_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcontent",
            name="content_xml",
            field=models.TextField(blank=True, null=True, verbose_name="document XML"),
        ),
    ]
