# Generated by Django 3.2.16 on 2023-07-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0093_add_model_labels"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="judge",
            options={
                "ordering": ("name",),
                "verbose_name": "judge",
                "verbose_name_plural": "judges",
            },
        ),
    ]
