# Generated by Django 3.2.19 on 2023-07-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0093_add_model_labels"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="label",
            options={
                "ordering": ["name"],
                "verbose_name": "label",
                "verbose_name_plural": "labels",
            },
        ),
        migrations.AddField(
            model_name="label",
            name="name_en",
            field=models.CharField(
                max_length=1024, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="name_fr",
            field=models.CharField(
                max_length=1024, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="name_pt",
            field=models.CharField(
                max_length=1024, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="name_sw",
            field=models.CharField(
                max_length=1024, null=True, unique=True, verbose_name="name"
            ),
        ),
    ]
