# Generated by Django 3.2.20 on 2023-08-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0094_alter_judge_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gazette",
            options={
                "base_manager_name": "objects",
                "permissions": [("api_gazette", "API gazette access")],
                "verbose_name": "gazette",
                "verbose_name_plural": "gazettes",
            },
        ),
        migrations.AlterModelOptions(
            name="judgment",
            options={
                "base_manager_name": "objects",
                "ordering": ["title"],
                "permissions": [("api_judgment", "API judgment access")],
                "verbose_name": "judgment",
                "verbose_name_plural": "judgments",
            },
        ),
    ]
