# Generated by Django 3.2.20 on 2023-08-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0095_api_perms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judge",
            name="name",
            field=models.CharField(max_length=1024, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="orderoutcome",
            name="name",
            field=models.CharField(max_length=1024, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="orderoutcome",
            name="name_en",
            field=models.CharField(
                max_length=1024, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="orderoutcome",
            name="name_fr",
            field=models.CharField(
                max_length=1024, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="orderoutcome",
            name="name_pt",
            field=models.CharField(
                max_length=1024, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="orderoutcome",
            name="name_sw",
            field=models.CharField(
                max_length=1024, null=True, unique=True, verbose_name="name"
            ),
        ),
    ]
