# Generated by Django 3.2.19 on 2023-08-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0097_rename_headnote_holding_case_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgment",
            name="case_summary",
            field=models.TextField(blank=True, null=True, verbose_name="case summary"),
        ),
    ]
