# Generated by Django 3.2.20 on 2023-08-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0098_alter_judgment_case_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="pocket_law_repo",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="Pocket Law repo"
            ),
        ),
    ]
