# Generated by Django 3.2.19 on 2023-08-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0100_sourcefile_file_as_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="help_link",
            field=models.URLField(
                blank=True,
                default="https://liieditors.docs.laws.africa/",
                null=True,
                verbose_name="help link",
            ),
        ),
    ]
