# Generated by Django 3.2.19 on 2023-08-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0100_sourcefile_file_as_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgment",
            name="additional_citations",
        ),
    ]
