# Generated by Django 3.2.19 on 2023-08-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0101_remove_judgment_additional_citations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternativename",
            name="title",
            field=models.CharField(
                max_length=1024,
                verbose_name="Law report citation/Alternative known name",
            ),
        ),
        migrations.AlterField(
            model_name="casenumber",
            name="string_override",
            field=models.CharField(
                blank=True,
                help_text="Override for full case number string",
                max_length=1024,
                null=True,
                verbose_name="Full case number as printed on judgment",
            ),
        ),
    ]
