# Generated by Django 3.2.19 on 2023-08-29 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries_plus", "0005_auto_20160224_1804"),
        ("peachjam", "0101_peachjamsettings_help_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coredocument",
            options={
                "ordering": ["doc_type", "title"],
                "permissions": [
                    ("can_delete_own_document", "Can delete own document"),
                    ("can_edit_own_document", "Can edit own document"),
                    ("can_edit_advanced_fields", "Can edit advanced fields"),
                ],
            },
        ),
        migrations.RemoveField(
            model_name="judgment",
            name="additional_citations",
        ),
        migrations.AddField(
            model_name="peachjamsettings",
            name="default_document_jurisdiction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="countries_plus.country",
                verbose_name="default document jurisdiction",
            ),
        ),
        migrations.AlterField(
            model_name="alternativename",
            name="title",
            field=models.CharField(
                max_length=1024,
                verbose_name="Law report citation/Alternative known name",
            ),
        ),
        migrations.AlterField(
            model_name="casenumber",
            name="string_override",
            field=models.CharField(
                blank=True,
                help_text="Override for full case number string",
                max_length=1024,
                null=True,
                verbose_name="Full case number as printed on judgment",
            ),
        ),
    ]
