# Generated by Django 3.2.19 on 2023-08-29 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries_plus", "0005_auto_20160224_1804"),
        ("peachjam", "0102_auto_20230829_0318"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="default_document_jurisdiction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="countries_plus.country",
                verbose_name="default document jurisdiction",
            ),
        ),
    ]
