# Generated by Django 3.2.20 on 2023-08-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0103_backfill_default_document_jurisdiction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="peachjamsettings",
            old_name="help_link",
            new_name="editor_help_link",
        ),
        migrations.AlterField(
            model_name="peachjamsettings",
            name="editor_help_link",
            field=models.URLField(
                blank=True,
                default="https://liieditors.docs.laws.africa/",
                null=True,
                verbose_name="editor help link",
            ),
        ),
        migrations.AddField(
            model_name="peachjamsettings",
            name="user_help_link",
            field=models.URLField(
                blank=True,
                default="https://liiguide.docs.laws.africa/",
                null=True,
                verbose_name="user help link",
            ),
        ),
    ]
