# Generated by Django 3.2.19 on 2023-08-29 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0103_peachjamsettings_default_document_jurisdiction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coredocument",
            options={
                "ordering": ["doc_type", "title"],
                "permissions": [
                    ("can_delete_own_document", "Can delete own document"),
                    ("can_edit_own_document", "Can edit own document"),
                    ("can_edit_advanced_fields", "Can edit advanced fields"),
                ],
            },
        ),
    ]
