# Generated by Django 3.2.20 on 2023-09-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0104_rename_help_link_peachjamsettings_editor_help_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="legislation",
            name="commencements_json",
            field=models.JSONField(default=list, verbose_name="commencements_json"),
        ),
        migrations.AddField(
            model_name="legislation",
            name="timeline",
            field=models.JSONField(default=list, verbose_name="timeline"),
        ),
    ]
