# Generated by Django 3.2.19 on 2023-09-04 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries_plus", "0005_auto_20160224_1804"),
        ("peachjam", "0104_rename_help_link_peachjamsettings_editor_help_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="JurisdictionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jurisdiction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="countries_plus.country",
                        verbose_name="jurisdiction",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "jurisdiction profile",
                "verbose_name_plural": "jurisdiction profiles",
            },
        ),
    ]
