# Generated by Django 3.2.20 on 2023-09-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0105_jurisdictionprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="legislation",
            name="commencements_json",
            field=models.JSONField(default=list, verbose_name="commencements JSON"),
        ),
        migrations.AddField(
            model_name="legislation",
            name="timeline_json",
            field=models.JSONField(default=list, verbose_name="timeline JSON"),
        ),
    ]
