# Generated by Django 3.2.20 on 2023-10-21 13:58
import logging

from django.db import migrations

log = logging.getLogger(__name__)


def delete_stubs_without_publication_documents(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Legislation = apps.get_model("peachjam", "Legislation")
    for legislation in (
        Legislation.objects.using(db_alias)
        .filter(metadata_json__stub=True, source_file__isnull=True)
        .order_by("-pk")
        .iterator(100)
    ):
        log.info(
            f"Deleting stub with no publication document: {legislation.expression_frbr_uri}"
        )
        legislation.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0106_legislation_timeline_commencements"),
    ]

    operations = [
        migrations.RunPython(
            delete_stubs_without_publication_documents, migrations.RunPython.noop
        ),
    ]
