# Generated by Django 3.2.19 on 2023-11-02 13:24
from django.db import migrations


def update_ingestor_api_url(apps, schema_editor):
    """Update the ingestor API URL to use the new API indigo v3."""
    Ingestor = apps.get_model("peachjam", "Ingestor")
    IngestorSetting = apps.get_model("peachjam", "IngestorSetting")

    for ingestor in Ingestor.objects.all():
        setting = IngestorSetting.objects.filter(
            ingestor=ingestor, name="api_url"
        ).first()
        if setting:
            setting.value = "https://api.laws.africa/v3"
            setting.save()


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0107_delete_stubs_without_publication_documents"),
    ]

    operations = [
        migrations.RunPython(update_ingestor_api_url, migrations.RunPython.noop)
    ]
