# Generated by Django 3.2.19 on 2023-11-14 09:13

from django.db import migrations


def add_overturned_and_upheld_predicates(apps, schema_editor):
    """Add the predicates for overturned and upheld."""
    Predicate = apps.get_model("peachjam", "Predicate")

    overturned_predicate = {
        "name": "overturns",
        "slug": "overturns",
        "verb": "overturns",
        "reverse_verb": "is overturned by",
    }
    Predicate.objects.update_or_create(
        name=overturned_predicate["name"], defaults=overturned_predicate
    )

    upheld_predicate = {
        "name": "upholds",
        "slug": "upholds",
        "verb": "upholds",
        "reverse_verb": "is upheld by",
    }
    Predicate.objects.update_or_create(
        name=upheld_predicate["name"], defaults=upheld_predicate
    )


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0108_update_ingestor_api_url"),
    ]

    operations = [
        migrations.RunPython(
            add_overturned_and_upheld_predicates, migrations.RunPython.noop
        ),
    ]
