# Generated by Django 3.2.21 on 2023-11-08 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0108_update_ingestor_api_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bench",
            name="judge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="peachjam.judge",
                verbose_name="judge",
            ),
        ),
    ]
