# Generated by Django 3.2.19 on 2023-11-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0109_add_overturned_and_upheld_predicates"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="admin_emails",
            field=models.CharField(
                blank=True,
                help_text="Enter one or more email addresses separated by spaces.",
                max_length=1024,
                null=True,
                verbose_name="admin emails",
            ),
        ),
    ]
