# Generated by Django 3.2.20 on 2023-11-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0109_add_overturned_and_upheld_predicates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="peachjamsettings",
            options={
                "permissions": [("can_debug_search", "Can debug search")],
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
            },
        ),
    ]
