# Generated by Django 3.2.19 on 2023-11-28 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0109_add_overturned_and_upheld_predicates"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "site_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_emails",
                        to="peachjam.peachjamsettings",
                        verbose_name="site settings",
                    ),
                ),
            ],
        ),
    ]
