# Generated by Django 3.2.20 on 2023-12-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0111_alter_peachjamsettings_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="pagerank_pivot_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="pagerank pivot value"
            ),
        ),
    ]
