# Generated by Django 3.2.19 on 2023-12-11 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries_plus", "0005_auto_20160224_1804"),
        ("peachjam", "0113_book_content_markdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="court",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="countries_plus.country",
                verbose_name="country",
            ),
        ),
        migrations.AddField(
            model_name="court",
            name="locality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="peachjam.locality",
                verbose_name="locality",
            ),
        ),
    ]
