# Generated by Django 3.2.19 on 2023-12-13 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries_plus", "0005_auto_20160224_1804"),
        ("peachjam", "0113_auto_20231211_0917"),
    ]

    operations = [
        migrations.AlterField(
            model_name="court",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="countries_plus.country",
                verbose_name="country",
            ),
        ),
    ]
