# Generated by Django 3.2.19 on 2024-01-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0114_alter_court_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="linkedin_link",
            field=models.URLField(blank=True, null=True, verbose_name="linkedin link"),
        ),
    ]
