# Generated by Django 3.2.19 on 2024-01-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0114_alter_court_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgment",
            name="order_outcome",
        ),
        migrations.AddField(
            model_name="judgment",
            name="order_outcome",
            field=models.ManyToManyField(blank=True, to="peachjam.OrderOutcome"),
        ),
    ]
