# Generated by Django 3.2.19 on 2024-01-18 10:57

from django.db import migrations, models


def copy_data(apps, schema_editor):
    Judgment = apps.get_model("peachjam", "Judgment")

    for judgment in Judgment.objects.filter(order_outcome__isnull=False).iterator(
        chunk_size=100
    ):
        judgment.order_outcomes.add(judgment.order_outcome)
        judgment.save()


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0115_peachjamsettings_linkedin_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="order_outcomes",
            field=models.ManyToManyField(blank=True, to="peachjam.OrderOutcome"),
        ),
        migrations.RunPython(copy_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="judgment",
            name="order_outcome",
        ),
    ]
