# Generated by Django 3.2.19 on 2024-01-18 14:10

import django.db.models.deletion
from django.db import migrations, models

import peachjam.models.core_document_model


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0116_copy_and_delete_old_order_outcome_field_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=1024, verbose_name="filename"),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=1024,
                        upload_to=peachjam.models.core_document_model.file_location,
                        verbose_name="file",
                    ),
                ),
                (
                    "mimetype",
                    models.CharField(max_length=1024, verbose_name="mimetype"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_media",
                        to="peachjam.coredocument",
                        verbose_name="document",
                    ),
                ),
            ],
        ),
    ]
