# Generated by Django 3.2.16 on 2024-01-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0116_copy_and_delete_old_order_outcome_field_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="coredocument",
            name="published",
            field=models.BooleanField(default=True, verbose_name="published"),
        ),
    ]
