# Generated by Django 3.2.20 on 2024-01-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0117_coredocument_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coredocument",
            name="published",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Is this document published and visible on the website?",
                verbose_name="published",
            ),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="slug",
            field=models.SlugField(max_length=10240, unique=True, verbose_name="slug"),
        ),
    ]
