# Generated by Django 3.2.20 on 2024-02-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0118_auto_20240130_1221"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="matomo_domain",
            field=models.CharField(
                blank=True,
                help_text="Matomo domain (e.g. mysite.matomo.cloud)",
                max_length=1024,
                null=True,
                verbose_name="matomo domain",
            ),
        ),
        migrations.AddField(
            model_name="peachjamsettings",
            name="matomo_site_id",
            field=models.CharField(
                blank=True,
                help_text="Matomo site ID (e.g. 2)",
                max_length=10,
                null=True,
                verbose_name="matomo site ID",
            ),
        ),
    ]
