# Generated by Django 3.2.21 on 2024-02-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0119_matomo"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="lower_court_judges",
            field=models.ManyToManyField(
                blank=True,
                related_name="lower_court_judgments",
                to="peachjam.Judge",
                verbose_name="lower court judges",
            ),
        ),
    ]
