# Generated by Django 3.2.20 on 2024-03-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0120_gazette_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestorsetting",
            name="value",
            field=models.CharField(
                blank=True, default="", max_length=2048, verbose_name="value"
            ),
        ),
    ]
