# Generated by Django 3.2.21 on 2024-03-04 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0121_alter_ingestorsetting_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="LowerBench",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="peachjam.judge",
                        verbose_name="lower_court_judge",
                    ),
                ),
                (
                    "judgment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lower_bench",
                        to="peachjam.judgment",
                        verbose_name="judgment",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "unique_together": {("judgment", "judge")},
            },
        ),
        migrations.AddField(
            model_name="judgment",
            name="lower_court_judges",
            field=models.ManyToManyField(
                blank=True,
                related_name="lower_court_judgments",
                through="peachjam.LowerBench",
                to="peachjam.Judge",
                verbose_name="lower court judges",
            ),
        ),
    ]
