# Generated by Django 3.2.16 on 2024-03-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0123_alter_judgment_order_outcomes"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="contact_form_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="contact form URL"
            ),
        ),
    ]
