# Generated by Django 3.2.24 on 2024-04-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0124_peachjamsettings_contact_form_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="auto_assign_title",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Whether or not the system should assign the title",
                null=True,
            ),
        ),
    ]
