# Generated by Django 3.2.24 on 2024-04-23 08:26

from django.db import migrations, models
from django.utils.text import slugify


def create_slug(apps, schema_editor):
    CourtClass = apps.get_model("peachjam", "CourtClass")
    for court_class in CourtClass.objects.all():
        court_class.slug = slugify(court_class.name)
        court_class.save()


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0125_judgment_auto_assign_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="courtclass",
            name="slug",
            field=models.SlugField(default="", max_length=255, verbose_name="slug"),
            preserve_default=False,
        ),
        migrations.RunPython(create_slug, migrations.RunPython.noop),
    ]
