# Generated by Django 3.2.24 on 2024-04-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0126_courtclass_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courtclass",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="slug"),
        ),
    ]
