# Generated by Django 3.2.24 on 2024-04-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0127_alter_courtclass_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="courtclass",
            name="show_listing_page",
            field=models.BooleanField(default=False),
        ),
    ]
