# Generated by Django 3.2.25 on 2024-05-14 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0128_courtclass_show_listing_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="n_cited_works",
            field=models.IntegerField(default=0, verbose_name="number of cited works"),
        ),
        migrations.AddField(
            model_name="work",
            name="n_citing_works",
            field=models.IntegerField(
                default=0, verbose_name="number of incoming citations"
            ),
        ),
        migrations.AlterField(
            model_name="extractedcitation",
            name="citing_work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_citations",
                to="peachjam.work",
                verbose_name="citing work",
            ),
        ),
        migrations.AlterField(
            model_name="extractedcitation",
            name="target_work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_citations",
                to="peachjam.work",
                verbose_name="target work",
            ),
        ),
    ]
