# Generated by Django 3.2.25 on 2024-05-14 06:19

from django.db import migrations
from django.db.models import Q


def backfill_citation_counts(apps, schema_editor):
    Work = apps.get_model("peachjam", "Work")
    ExtractedCitation = apps.get_model("peachjam", "ExtractedCitation")

    qs = Work.objects.filter(
        Q(outgoing_citations__isnull=False) | Q(incoming_citations__isnull=False)
    )
    for work in qs.order_by("-pk").distinct("pk").iterator(256):
        work.n_cited_works = ExtractedCitation.objects.filter(citing_work=work).count()
        work.n_citing_works = ExtractedCitation.objects.filter(target_work=work).count()
        if work.n_cited_works or work.n_citing_works:
            work.save(update_fields=["n_cited_works", "n_citing_works"])


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0129_work_citation_counts"),
    ]

    operations = [
        migrations.RunPython(backfill_citation_counts, migrations.RunPython.noop)
    ]
