# Generated by Django 3.2.21 on 2024-05-20 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0130_backfill_citation_counts"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourtGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
                (
                    "order",
                    models.IntegerField(blank=True, null=True, verbose_name="order"),
                ),
                ("show_listing_page", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "court group",
                "verbose_name_plural": "court groups",
                "ordering": ("order", "name"),
            },
        ),
        migrations.AddField(
            model_name="courtclass",
            name="court_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="peachjam.courtgroup",
                verbose_name="court group",
            ),
        ),
    ]
