# Generated by Django 3.2.21 on 2024-05-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0130_backfill_citation_counts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1024, unique=True, verbose_name="name"),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=1024, null=True, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        max_length=1024, null=True, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "name_pt",
                    models.CharField(
                        max_length=1024, null=True, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "name_sw",
                    models.CharField(
                        max_length=1024, null=True, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "outcome",
                "verbose_name_plural": "outcomes",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="judgment",
            name="order",
            field=models.TextField(blank=True, null=True, verbose_name="order"),
        ),
        migrations.AddField(
            model_name="judgment",
            name="outcomes",
            field=models.ManyToManyField(
                blank=True, related_name="judgments", to="peachjam.Outcome"
            ),
        ),
    ]
