# Generated by Django 3.2.21 on 2024-05-15 13:59

from django.db import migrations


def forwards(apps, schema_editor):
    Outcome = apps.get_model("peachjam", "Outcome")
    OrderOutCome = apps.get_model("peachjam", "OrderOutCome")
    Judgment = apps.get_model("peachjam", "Judgment")

    for outcome in OrderOutCome.objects.all():
        o = Outcome()
        o.name = outcome.name
        o.description = outcome.description
        if hasattr(outcome, "name_en"):
            o.name_en = outcome.name_en
        if hasattr(outcome, "name_fr"):
            o.name_fr = outcome.name_fr
        if hasattr(outcome, "name_pt"):
            o.name_pt = outcome.name_pt
        if hasattr(outcome, "name_sw"):
            o.name_sw = outcome.name_sw
        o.save()

    for judgment in (
        Judgment.objects.filter(order_outcomes__isnull=False)
        .order_by("pk")
        .iterator(chunk_size=100)
    ):
        j_outcomes = judgment.order_outcomes.all().values_list("name", flat=True)
        outcomes = Outcome.objects.filter(name__in=j_outcomes)
        if outcomes:
            judgment.outcomes.set(outcomes)


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0131_rename_order_outcome"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
