# Generated by Django 3.2.21 on 2024-05-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0133_backfill_outcomes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgment",
            name="order_outcomes",
        ),
        migrations.DeleteModel(
            name="OrderOutcome",
        ),
    ]
