# Generated by Django 3.2.25 on 2024-05-14 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0133_backfill_outcomes"),
    ]

    operations = [
        # this migration was broken, 0135 is the correct version
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop)
    ]
