# Generated by Django 3.2.21 on 2024-06-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0136_casehistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casehistory",
            options={
                "ordering": ["-date"],
                "verbose_name": "case history",
                "verbose_name_plural": "case histories",
            },
        ),
        migrations.AddField(
            model_name="gazette",
            name="volume_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="volume number"
            ),
        ),
    ]
