# Generated by Django 3.2.21 on 2024-06-04 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0136_casehistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casehistory",
            options={
                "ordering": ["-date"],
                "verbose_name": "case history",
                "verbose_name_plural": "case histories",
            },
        ),
        migrations.AlterField(
            model_name="courtregistry",
            name="court",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registries",
                to="peachjam.court",
                verbose_name="court",
            ),
        ),
    ]
