# Generated by Django 3.2.21 on 2024-06-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0137_registry_court"),
    ]

    operations = [
        migrations.AddField(
            model_name="gazette",
            name="volume_number",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="volume number"
            ),
        ),
    ]
