# Generated by Django 3.2.21 on 2024-06-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0138_gazette_volume_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CaseHistory",
        ),
    ]
