# Generated by Django 3.2.21 on 2024-06-05 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0139_delete_casehistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_number",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="case number",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="date")),
                (
                    "court",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="peachjam.court",
                        verbose_name="court",
                    ),
                ),
                (
                    "historical_judgment_work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="peachjam.work",
                        verbose_name="historical judgment work",
                    ),
                ),
                (
                    "judges",
                    models.ManyToManyField(
                        blank=True, to="peachjam.Judge", verbose_name="judges"
                    ),
                ),
                (
                    "judgment_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_histories",
                        to="peachjam.work",
                        verbose_name="judgment work",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="peachjam.outcome",
                        verbose_name="outcome",
                    ),
                ),
            ],
            options={
                "verbose_name": "case history",
                "verbose_name_plural": "case histories",
                "ordering": ["-date"],
            },
        ),
    ]
