# Generated by Django 3.2.21 on 2024-06-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0140_casehistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coredocument",
            name="title",
            field=models.CharField(max_length=4096, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="work",
            name="title",
            field=models.CharField(max_length=4096, verbose_name="title"),
        ),
    ]
