# Generated by Django 3.2.21 on 2024-06-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0141_work_title_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coredocument",
            name="citation",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="citation"
            ),
        ),
    ]
