# Generated by Django 3.2.21 on 2024-06-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0142_alter_coredocument_citation"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="youtube_link",
            field=models.URLField(blank=True, null=True, verbose_name="youtube link"),
        ),
    ]
