# Generated by Django 3.2.25 on 2024-07-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0143_peachjamsettings_youtube_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="gazette",
            name="special",
            field=models.BooleanField(default=False, verbose_name="special"),
        ),
    ]
