# Generated by Django 3.2.25 on 2024-07-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0144_gazette_special"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courtregistry",
            options={
                "ordering": ("name",),
                "verbose_name": "court registry",
                "verbose_name_plural": "court registries",
            },
        ),
    ]
