# Generated by Django 3.2.25 on 2024-07-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0145_alter_courtregistry_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="judgment",
            old_name="auto_assign_title",
            new_name="auto_assign_details",
        ),
    ]
