# Generated by Django 3.2.25 on 2024-07-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0146_clean_content_html"),
    ]

    operations = [
        migrations.RenameField(
            model_name="judgment",
            old_name="auto_assign_title",
            new_name="auto_assign_details",
        ),
    ]
