# Generated by Django 3.2.25 on 2024-07-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0146_rename_auto_assign_title_judgment_auto_assign_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgment",
            name="auto_assign_details",
            field=models.BooleanField(
                default=True,
                help_text="Whether or not the system should assign the details",
                verbose_name="Auto-assign details",
            ),
        ),
    ]
