# Generated by Django 3.2.25 on 2024-07-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0149_folder_saveddocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="allow_save_documents",
            field=models.BooleanField(
                default=False,
                help_text="Allow documents to be saved.",
                verbose_name="allow save documents",
            ),
        ),
    ]
