# Generated by Django 4.2.15 on 2024-08-18 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("countries_plus", "0005_auto_20160224_1804"),
        ("languages_plus", "0004_auto_20171214_0004"),
        ("peachjam", "0149_relationship_subject_selectors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coredocument",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="peachjamsettings",
            name="document_jurisdictions",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="countries_plus.country",
                verbose_name="document jurisdictions",
            ),
        ),
        migrations.AlterField(
            model_name="peachjamsettings",
            name="document_languages",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="languages_plus.language",
                verbose_name="document languages",
            ),
        ),
    ]
