# Generated by Django 4.2.15 on 2024-08-13 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peachjam", "0149_relationship_subject_selectors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="name")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user_profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "folder",
                "verbose_name_plural": "folders",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="peachjamsettings",
            name="allow_save_documents",
            field=models.BooleanField(
                default=False,
                help_text="Allow documents to be saved.",
                verbose_name="allow save documents",
            ),
        ),
        migrations.CreateModel(
            name="SavedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peachjam.coredocument",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_documents",
                        to="peachjam.folder",
                        verbose_name="folder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user_profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "saved document",
                "verbose_name_plural": "saved documents",
                "ordering": ("document__title",),
                "unique_together": {("document", "folder")},
            },
        ),
    ]
