# Generated by Django 4.2.14 on 2024-08-29 13:58

from django.db import migrations


def forwards(apps, schema_editor):
    # backfill natures for existing documents
    DocumentNature = apps.get_model("peachjam", "DocumentNature")

    DOC_TYPES = [
        ("core_document", "document", "Document"),
        ("gazette", "gazette", "Gazette"),
        ("generic_document", "document", "Document"),
        ("judgment", "judgment", "Judgment"),
        ("legal_instrument", "legal-instrument", "Legal Instrument"),
        ("legislation", "act", "Act"),
        ("book", "book", "Book"),
        ("journal", "journal", "Journal"),
    ]
    for doc_type, nature, name in DOC_TYPES:
        nature = DocumentNature.objects.get_or_create(
            code=nature, defaults={"name": name}
        )[0]

        # run raw SQL to do the update for this doc_type and nature id
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                f"UPDATE peachjam_coredocument SET nature_id = {nature.id} WHERE doc_type = '{doc_type}' AND nature_id IS NULL"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0150_peachjamsettings_survey_link_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
