# Generated by Django 4.2.14 on 2024-08-29 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0152_backfill_natures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coredocument",
            name="nature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="peachjam.documentnature",
                verbose_name="nature",
            ),
        ),
    ]
