# Generated by Django 4.2.14 on 2024-09-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0154_backfill_nature_elasticsearch"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityprofile",
            name="title",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="Title"
            ),
        ),
    ]
