# Generated by Django 4.2.16 on 2024-09-10 21:57

import django.db.models.deletion
from django.db import migrations, models

import peachjam.models.core_document_model
import peachjam.storage


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0155_entityprofile_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=1024, verbose_name="filename"),
                ),
                (
                    "mimetype",
                    models.CharField(max_length=1024, verbose_name="mimetype"),
                ),
                ("size", models.BigIntegerField(default=0, verbose_name="size")),
                (
                    "file",
                    peachjam.storage.DynamicStorageFileField(
                        max_length=1024,
                        upload_to=peachjam.models.core_document_model.file_location,
                        verbose_name="file",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="source URL",
                    ),
                ),
                (
                    "trusted_url",
                    models.URLField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="trusted URL",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_file",
                        to="peachjam.coredocument",
                        verbose_name="document",
                    ),
                ),
            ],
            options={
                "verbose_name": "publication file",
                "verbose_name_plural": "publication files",
            },
        ),
    ]
