# Generated by Django 4.2.15 on 2024-09-11 09:20

from django.db import migrations


def backfill_metadata_json(apps, schema_editor):
    Legislation = apps.get_model("peachjam", "Legislation")

    for leg in Legislation.objects.iterator(100):
        leg.metadata_json = leg.old_metadata_json
        leg.principal = leg.old_metadata_json["principal"]
        leg.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "peachjam",
            "0156_rename_metadata_json_legislation_old_metadata_json_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(backfill_metadata_json, migrations.RunPython.noop)
    ]
