# Generated by Django 4.2.15 on 2024-09-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0157_backfill_metadata_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legislation",
            name="old_metadata_json",
            field=models.JSONField(blank=True, null=True, verbose_name="metadata JSON"),
        ),
    ]
