# Generated by Django 4.2.16 on 2024-09-13 14:02

import django.db.models.deletion
from django.db import migrations, models

import peachjam.models.core_document_model


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0158_alter_legislation_old_metadata_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=1024, verbose_name="filename"),
                ),
                (
                    "mimetype",
                    models.CharField(max_length=1024, verbose_name="mimetype"),
                ),
                ("size", models.BigIntegerField(default=0, verbose_name="size")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        upload_to=peachjam.models.core_document_model.file_location,
                        verbose_name="file",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="The external URL (e.g. on gazettes.africa) where this file lives",
                        max_length=2048,
                        null=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "use_source_file",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True if the source file on the same document can be used instead",
                        verbose_name="use source file",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_file",
                        to="peachjam.coredocument",
                        verbose_name="document",
                    ),
                ),
            ],
            options={
                "verbose_name": "publication file",
                "verbose_name_plural": "publication files",
            },
        ),
    ]
