# Generated by Django 4.2.15 on 2024-09-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0158_alter_legislation_old_metadata_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestor",
            name="repeat",
            field=models.BigIntegerField(
                choices=[
                    (60, "one minute"),
                    (300, "five minutes"),
                    (1800, "thirty minutes"),
                    (3600, "hourly"),
                    (86400, "daily"),
                    (604800, "weekly"),
                    (1209600, "every 2 weeks"),
                    (2419200, "every 4 weeks"),
                    (0, "never"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="ingestor",
            name="schedule",
            field=models.BigIntegerField(
                choices=[
                    (60, "one minute"),
                    (300, "five minutes"),
                    (1800, "thirty minutes"),
                    (3600, "hourly"),
                    (86400, "daily"),
                    (604800, "weekly"),
                    (1209600, "every 2 weeks"),
                    (2419200, "every 4 weeks"),
                    (0, "never"),
                ],
                default=0,
            ),
        ),
    ]
