# Generated by Django 4.2.14 on 2024-09-26 14:17

from django.db import migrations
from django.db.models import Count


def remove_duplicate_images(apps, schema_editor):
    Image = apps.get_model("peachjam", "Image")

    # Find duplicates by grouping by document and filename
    duplicates = (
        Image.objects.values("document", "filename")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )

    # Loop through each duplicate group
    for dup in duplicates:
        # Get all images with the same document and filename
        images = Image.objects.filter(
            document=dup["document"], filename=dup["filename"]
        )

        # Keep one and delete the rest
        images.exclude(id=images.first().id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0160_ingestor_repeat_ingestor_schedule"),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_images),
        migrations.AlterUniqueTogether(
            name="image",
            unique_together={("document", "filename")},
        ),
    ]
