# Generated by Django 4.2.14 on 2024-10-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0163_allusers_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="robots_txt",
            field=models.TextField(
                blank=True, help_text="Additional robots.txt rules.", null=True
            ),
        ),
    ]
