# Generated by Django 4.2.15 on 2024-10-09 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0164_peachjamsettings_robots_txt"),
    ]

    operations = [
        migrations.CreateModel(
            name="CauseList",
            fields=[
                (
                    "coredocument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="peachjam.coredocument",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="peachjam.court",
                        verbose_name="court",
                    ),
                ),
                (
                    "judges",
                    models.ManyToManyField(
                        blank=True, to="peachjam.judge", verbose_name="judges"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("peachjam.coredocument",),
        ),
    ]
