# Generated by Django 4.2.16 on 2024-10-11 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0165_causelist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="causelist",
            name="court",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="causelists",
                to="peachjam.court",
                verbose_name="court",
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("core_document", "Core Document"),
                    ("gazette", "Gazette"),
                    ("generic_document", "Generic Document"),
                    ("judgment", "Judgment"),
                    ("legal_instrument", "Legal Instrument"),
                    ("legislation", "Legislation"),
                    ("book", "Book"),
                    ("journal", "Journal"),
                    ("causelist", "Cause List"),
                ],
                default="core_document",
                max_length=255,
                verbose_name="document type",
            ),
        ),
    ]
