# Generated by Django 4.2.14 on 2024-10-10 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0165_editactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="coredocument",
            name="ingestor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peachjam.ingestor",
            ),
        ),
    ]
