# Generated by Django 4.2.15 on 2024-10-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0166_coredocument_ingestor"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="allow_social_logins",
            field=models.BooleanField(
                default=False,
                help_text="Allow signups via social accounts",
                verbose_name="allow social logins",
            ),
        ),
    ]
