# Generated by Django 4.2.14 on 2024-10-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0166_coredocument_ingestor"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="lawsafrica_api_token",
            field=models.CharField(
                blank=True,
                help_text="Laws.Africa API token",
                null=True,
                verbose_name="Laws.Africa API token",
            ),
        ),
        migrations.AddField(
            model_name="peachjamsettings",
            name="lawsafrica_extractor_url",
            field=models.URLField(
                blank=True,
                help_text="Laws.Africa extractor service API URL",
                null=True,
                verbose_name="Laws.Africa extractor URL",
            ),
        ),
    ]
