# Generated by Django 4.2.14 on 2024-10-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0167_ratification_ratificationcountry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
    ]
