# Generated by Django 4.2.16 on 2024-10-16 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0167_peachjamsettings_allow_social_logins"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourtDivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
                (
                    "code",
                    models.SlugField(max_length=255, unique=True, verbose_name="code"),
                ),
                (
                    "order",
                    models.IntegerField(blank=True, null=True, verbose_name="order"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("core_document", "Core Document"),
                    ("gazette", "Gazette"),
                    ("generic_document", "Generic Document"),
                    ("judgment", "Judgment"),
                    ("legal_instrument", "Legal Instrument"),
                    ("legislation", "Legislation"),
                    ("book", "Book"),
                    ("journal", "Journal"),
                    ("causelist", "Cause List"),
                ],
                default="core_document",
                max_length=255,
                verbose_name="document type",
            ),
        ),
        migrations.CreateModel(
            name="CauseList",
            fields=[
                (
                    "coredocument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="peachjam.coredocument",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="causelists",
                        to="peachjam.court",
                        verbose_name="court",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="causelists",
                        to="peachjam.courtdivision",
                    ),
                ),
                (
                    "judges",
                    models.ManyToManyField(
                        blank=True, to="peachjam.judge", verbose_name="judges"
                    ),
                ),
                (
                    "registry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="causelists",
                        to="peachjam.courtregistry",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("peachjam.coredocument",),
        ),
    ]
