# Generated by Django 4.2.14 on 2024-10-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0171_update_ingestor_settings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingestor",
            options={"verbose_name": "ingestor", "verbose_name_plural": "ingestors"},
        ),
        migrations.DeleteModel(
            name="LegalInstrument",
        ),
    ]
