# Generated by Django 4.2.15 on 2024-10-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0173_alter_ratification_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="causelist",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="end date"),
        ),
    ]
