# Generated by Django 4.2.14 on 2024-10-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0174_causelist_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="google_search_engine_id",
            field=models.CharField(
                blank=True,
                help_text="ID of a Google custom search engine.",
                max_length=100,
                null=True,
            ),
        ),
    ]
