# Generated by Django 4.2.14 on 2024-11-04 10:18

import django.db.models.deletion
from django.db import migrations, models

import peachjam.models.partner


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0175_peachjamsettings_google_search_engine_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="url")),
                (
                    "document_blurb_html",
                    models.TextField(
                        blank=True, null=True, verbose_name="document blurb"
                    ),
                ),
            ],
            options={
                "verbose_name": "partner",
                "verbose_name_plural": "partners",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="PartnerLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=1024, verbose_name="filename"),
                ),
                (
                    "mimetype",
                    models.CharField(max_length=1024, verbose_name="mimetype"),
                ),
                ("size", models.BigIntegerField(default=0, verbose_name="size")),
                (
                    "file",
                    models.ImageField(
                        max_length=1024,
                        upload_to=peachjam.models.partner.file_location,
                        verbose_name="file",
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logo",
                        to="peachjam.partner",
                        verbose_name="partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "logo",
                "verbose_name_plural": "logos",
            },
        ),
        migrations.AddField(
            model_name="work",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Publication partner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peachjam.partner",
                verbose_name="partner",
            ),
        ),
    ]
