# Generated by Django 4.2.14 on 2024-11-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0176_partner_partnerlogo_work_partner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentnature",
            options={
                "ordering": ["name"],
                "verbose_name": "document nature",
                "verbose_name_plural": "document natures",
            },
        ),
    ]
