# Generated by Django 4.2.14 on 2024-11-13 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0177_alter_documentnature_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "coredocument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="peachjam.coredocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "bill",
                "verbose_name_plural": "bills",
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("peachjam.coredocument",),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("core_document", "Core Document"),
                    ("bill", "Bill"),
                    ("gazette", "Gazette"),
                    ("generic_document", "Generic Document"),
                    ("judgment", "Judgment"),
                    ("legal_instrument", "Legal Instrument"),
                    ("legislation", "Legislation"),
                    ("book", "Book"),
                    ("journal", "Journal"),
                    ("causelist", "Cause List"),
                ],
                default="core_document",
                max_length=255,
                verbose_name="document type",
            ),
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="frbr_uri_doctype",
            field=models.CharField(
                choices=[
                    ("act", "act"),
                    ("bill", "bill"),
                    ("doc", "doc"),
                    ("judgment", "judgment"),
                    ("statement", "statement"),
                    ("officialGazette", "officialGazette"),
                ],
                max_length=20,
                verbose_name="FRBR URI doctype",
            ),
        ),
    ]
