# Generated by Django 4.2.14 on 2024-11-13 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0178_bill_alter_coredocument_doc_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPropertyLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_fr", models.CharField(max_length=255, null=True)),
                ("name_pt", models.CharField(max_length=255, null=True)),
                ("name_sw", models.CharField(max_length=255, null=True)),
            ],
            options={
                "verbose_name": "custom property label",
                "verbose_name_plural": "custom property labels",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CustomProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=4096, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_properties",
                        to="peachjam.coredocument",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="peachjam.custompropertylabel",
                    ),
                ),
            ],
            options={
                "verbose_name": "custom property",
                "verbose_name_plural": "custom properties",
                "ordering": ["label"],
            },
        ),
    ]
