# Generated by Django 4.2.14 on 2024-11-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0179_custompropertylabel_customproperty"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxonomy",
            name="show_in_document_listing",
            field=models.BooleanField(
                default=False,
                help_text="Show this taxonomy in the document listing page? Cascades to descendents.",
                verbose_name="show in document listing",
            ),
        ),
    ]
