# Generated by Django 4.2.15 on 2024-11-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0181_taxonomy_path_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="allow_save_searches",
            field=models.BooleanField(
                default=False,
                help_text="Allow searches to be saved.",
                verbose_name="allow save searches",
            ),
        ),
    ]
