# Generated by Django 4.2.14 on 2024-11-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0181_taxonomy_path_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ("-date",),
                "verbose_name": "article",
                "verbose_name_plural": "articles",
            },
        ),
    ]
