# Generated by Django 4.2.14 on 2024-11-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0182_alter_article_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="Featured articles will be displayed on the homepage.",
                verbose_name="featured",
            ),
        ),
    ]
