# Generated by Django 4.2.14 on 2024-11-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0184_bill_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genericdocument",
            old_name="authors",
            new_name="author",
        ),
    ]
