# Generated by Django 4.2.15 on 2024-12-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0187_folder_created_at_saveddocument_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="show_contact_form",
            field=models.BooleanField(
                default=False,
                help_text="Show the contact form.",
                verbose_name="show contact form",
            ),
        ),
    ]
