# Generated by Django 4.2.15 on 2025-01-21 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("peachjam", "0188_peachjamsettings_show_contact_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="coredocument",
            name="restricted",
            field=models.BooleanField(
                default=False,
                help_text="Restrict access to this document to selected groups.",
            ),
        ),
        migrations.CreateModel(
            name="DocumentAccessGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                        verbose_name="group",
                    ),
                ),
            ],
            options={
                "verbose_name": "document access group",
                "verbose_name_plural": "document access groups",
            },
        ),
    ]
