# Generated by Django 4.2.15 on 2025-01-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0188_peachjamsettings_show_contact_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="coredocument",
            name="restricted",
            field=models.BooleanField(default=False),
        ),
    ]
