# Generated by Django 4.2.16 on 2025-01-27 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0189_coredocument_restricted_documentaccessgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casehistory",
            name="historical_judgment_work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_case_histories",
                to="peachjam.work",
                verbose_name="historical judgment work",
            ),
        ),
    ]
