# Generated by Django 4.2.15 on 2025-01-14 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("peachjam", "0189_coredocument_restricted"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                        verbose_name="group",
                    ),
                ),
            ],
            options={
                "verbose_name": "public group",
                "verbose_name_plural": "public groups",
            },
        ),
    ]
