# Generated by Django 4.2.15 on 2025-01-21 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("peachjam", "0189_coredocument_restricted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bill",
            options={
                "base_manager_name": "objects",
                "permissions": [
                    ("can_view_restricted_document", "Can view restricted document")
                ],
                "verbose_name": "bill",
                "verbose_name_plural": "bills",
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={
                "base_manager_name": "objects",
                "permissions": [
                    ("can_view_restricted_document", "Can view restricted document")
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="causelist",
            options={
                "base_manager_name": "objects",
                "permissions": [
                    ("can_view_restricted_document", "Can view restricted document")
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="coredocument",
            options={
                "ordering": ["doc_type", "title"],
                "permissions": [
                    ("can_delete_own_document", "Can delete own document"),
                    ("can_edit_own_document", "Can edit own document"),
                    ("can_edit_advanced_fields", "Can edit advanced fields"),
                    ("can_view_restricted_document", "Can view restricted document"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="externaldocument",
            options={
                "base_manager_name": "objects",
                "permissions": [
                    ("can_view_restricted_document", "Can view restricted document")
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="genericdocument",
            options={
                "base_manager_name": "objects",
                "permissions": [
                    ("can_view_restricted_document", "Can view restricted document")
                ],
                "verbose_name": "generic document",
                "verbose_name_plural": "generic documents",
            },
        ),
        migrations.AlterModelOptions(
            name="journal",
            options={
                "base_manager_name": "objects",
                "permissions": [
                    ("can_view_restricted_document", "Can view restricted document")
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="judgment",
            options={
                "base_manager_name": "objects",
                "ordering": ["title"],
                "permissions": [
                    ("api_judgment", "API judgment access"),
                    ("can_view_restricted_document", "Can view restricted document"),
                ],
                "verbose_name": "judgment",
                "verbose_name_plural": "judgments",
            },
        ),
        migrations.AlterModelOptions(
            name="legislation",
            options={
                "base_manager_name": "objects",
                "permissions": [
                    ("can_view_restricted_document", "Can view restricted document")
                ],
                "verbose_name": "legislation",
                "verbose_name_plural": "legislation",
            },
        ),
        migrations.CreateModel(
            name="DocumentAccessGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="slug"),
                ),
                ("description", models.TextField()),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                        verbose_name="group",
                    ),
                ),
            ],
            options={
                "verbose_name": "document access group",
                "verbose_name_plural": "document access groups",
            },
        ),
    ]
