# Generated by Django 4.2.15 on 2025-01-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0190_publicgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicgroup",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="slug"),
        ),
    ]
