# Generated by Django 4.2.16 on 2025-01-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0190_alter_casehistory_historical_judgment_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="anonymised",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not the judgment is anonymised",
                verbose_name="Anonymised",
            ),
        ),
    ]
