# Generated by Django 4.2.14 on 2025-01-29 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0191_judgment_anonymised"),
    ]

    operations = [
        migrations.CreateModel(
            name="Replacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_text", models.TextField()),
                ("new_text", models.TextField()),
                ("target", models.JSONField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replacements",
                        to="peachjam.judgment",
                    ),
                ),
            ],
        ),
    ]
