# Generated by Django 4.2.15 on 2025-02-06 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0192_replacement"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="documenttopic",
            unique_together={("document", "topic")},
        ),
    ]
