# Generated by Django 4.2.15 on 2025-02-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0193_alter_documenttopic_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgment",
            name="order_outcomes",
        ),
        migrations.DeleteModel(
            name="OrderOutcome",
        ),
    ]
