# Generated by Django 4.2.15 on 2025-02-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0195_alter_saveddocument_document_annotation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=4096, unique=True, verbose_name="name"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="extractedcitation",
            name="treatments",
            field=models.ManyToManyField(
                to="peachjam.treatment", verbose_name="treatment"
            ),
        ),
    ]
