# Generated by Django 4.2.15 on 2025-02-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0196_treatment_extractedcitation_treatments"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="name_en",
            field=models.CharField(
                max_length=4096, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="name_fr",
            field=models.CharField(
                max_length=4096, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="name_pt",
            field=models.CharField(
                max_length=4096, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="name_sw",
            field=models.CharField(
                max_length=4096, null=True, unique=True, verbose_name="name"
            ),
        ),
    ]
