# Generated by Django 4.2.14 on 2025-03-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0197_treatment_name_en_treatment_name_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="allow_signups",
            field=models.BooleanField(
                default=True,
                help_text="Allow users to create accounts",
                verbose_name="allow signups",
            ),
        ),
    ]
