# Generated by Django 4.2.14 on 2025-03-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0197_treatment_name_en_treatment_name_fr_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="peachjamsettings",
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
            },
        ),
    ]
