# Generated by Django 4.2.15 on 2025-03-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0198_userfollowing_userfollowing_unique_user_court_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfollowing",
            name="last_alerted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last alerted at"
            ),
        ),
    ]
