# Generated by Django 4.2.15 on 2025-03-19 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages_plus", "0004_auto_20171214_0004"),
        ("peachjam", "0200_alter_taxonomy_options_userfollowing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="preferred_language",
            field=models.ForeignKey(
                default="en",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="languages_plus.language",
                verbose_name="preferred language",
            ),
        ),
    ]
