# Generated by Django 4.2.15 on 2025-03-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0201_userprofile_preferred_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfollowing",
            name="last_alerted_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="last alerted at"
            ),
        ),
    ]
