# Generated by Django 4.2.14 on 2025-03-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("peachjam", "0202_alter_userfollowing_last_alerted_at")]

    operations = [
        migrations.AlterModelOptions(
            name="folder",
            options={
                "ordering": ("name",),
                "permissions": [("download", "Can download documents")],
                "verbose_name": "folder",
                "verbose_name_plural": "folders",
            },
        ),
    ]
