# Generated by Django 4.2.14 on 2025-03-24 12:30

import django.db.models.deletion
from django.db import migrations, models

import peachjam.models.attachments


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0203_alter_folder_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSocialImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=1024,
                        upload_to=peachjam.models.attachments.file_location,
                        verbose_name="file",
                    ),
                ),
                (
                    "html_md5sum",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="html md5sum"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_image",
                        to="peachjam.coredocument",
                        verbose_name="document",
                    ),
                ),
            ],
            options={
                "verbose_name": "social media image",
                "verbose_name_plural": "social media images",
            },
        ),
    ]
