# Generated by Django 4.2.14 on 2025-03-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0204_documentsocialimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratification",
            name="source_url",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="source URL"
            ),
        ),
    ]
