# Generated by Django 4.2.14 on 2025-03-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0204_documentsocialimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcefile",
            name="sha256",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="SHA 256",
            ),
        ),
    ]
