# Generated by Django 4.2.15 on 2025-03-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0205_alter_ratification_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxonomy",
            name="restricted",
            field=models.BooleanField(default=False, verbose_name="restricted"),
        ),
    ]
