# Generated by Django 4.2.15 on 2025-03-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0205_alter_ratification_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveddocument",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
