# Generated by Django 4.2.14 on 2025-03-28 07:44

import uuid

from django.db import migrations, models


def create_uuid(apps, schema_editor):
    UserProfile = apps.get_model("peachjam", "UserProfile")
    for profile in UserProfile.objects.all():
        profile.tracking_id = uuid.uuid4()
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0205_alter_ratification_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="tracking_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                verbose_name="tracking id",
                blank=True,
                null=True,
            ),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name="userprofile",
            name="tracking_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="tracking id"
            ),
        ),
    ]
