# Generated by Django 4.2.15 on 2025-04-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0207_sourcefile_sha256"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxonomy",
            name="restricted",
            field=models.BooleanField(default=False, verbose_name="restricted"),
        ),
    ]
