# Generated by Django 4.2.15 on 2025-04-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0208_taxonomy_restricted"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseVerdict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1024, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "case verdict",
                "verbose_name_plural": "case verdicts",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="judgment",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="judgments",
                to="peachjam.courtdivision",
                verbose_name="court division",
            ),
        ),
        migrations.AlterField(
            model_name="courtdivision",
            name="code",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="code"
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="verdict",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="judgments",
                to="peachjam.caseverdict",
                verbose_name="verdict",
            ),
        ),
    ]
