# Generated by Django 4.2.15 on 2025-04-07 13:00
import os

from django.db import migrations


def forwards(apps, schema_editor):
    from django.conf import settings
    from django_elasticsearch_dsl.registries import registry

    if not settings.DEBUG and os.environ.get("ELASTICSEARCH_HOST"):
        for ix in registry.get_indices():
            if not ix._mapping:
                continue
            print(f"Adding case action and court division mapping for {ix._name}")
            ix.connection.indices.put_mapping(
                index=ix._name,
                body={
                    "properties": {
                        "case_action": ix._mapping["case_action"].to_dict(),
                        "division": ix._mapping["division"].to_dict(),
                    }
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0209_caseaction_judgment_division_and_more"),
    ]

    operations = []
