# Generated by Django 4.2 on 2025-04-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0209_caseaction_judgment_division_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship",
            name="object_target_id",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="object target ID"
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="subject_target_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="subject target ID",
            ),
        ),
    ]
