# Generated by Django 4.2.14 on 2025-04-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0210_alter_relationship_object_target_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="must_be_anonymised",
            field=models.BooleanField(
                default=False,
                help_text="Must this judgment be anonymised?",
                verbose_name="Must be anonymised",
            ),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="anonymised",
            field=models.BooleanField(
                default=False,
                help_text="Has the judgment been anonymised?",
                verbose_name="Anonymised",
            ),
        ),
        migrations.AlterField(
            model_name="editactivity",
            name="stage",
            field=models.CharField(
                choices=[
                    ("initial", "initial"),
                    ("corrections", "corrections"),
                    ("anonymisation", "anonymisation"),
                ],
                default="initial",
                max_length=255,
            ),
        ),
    ]
