# Generated by Django 4.2 on 2025-04-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0210_alter_relationship_object_target_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveddocument",
            name="note",
            field=models.TextField(
                blank=True, max_length=2048, null=True, verbose_name="note"
            ),
        ),
    ]
