# Generated by Django 4.2.14 on 2025-04-16 07:45

from django.db import migrations, models

import peachjam.models.attachments


class Migration(migrations.Migration):

    dependencies = [("peachjam", "0212_judgment_must_be_anonymised_and_more")]

    operations = [
        migrations.AddField(
            model_name="sourcefile",
            name="anonymised_file_as_pdf",
            field=models.FileField(
                blank=True,
                max_length=1024,
                null=True,
                upload_to=peachjam.models.attachments.file_location,
                verbose_name="anonymised file as pdf",
            ),
        ),
        migrations.AddField(
            model_name="sourcefile",
            name="file_is_anonymised",
            field=models.BooleanField(default=False, verbose_name="file is anonymised"),
        ),
    ]
