# Generated by Django 4.2.14 on 2025-04-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0213_sourcefile_anonymised_file_as_pdf_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE peachjam_judgment SET must_be_anonymised = true WHERE anonymised is TRUE and must_be_anonymised IS FALSE;",
            migrations.RunSQL.noop,
        ),
    ]
