# Generated by Django 4.2 on 2025-04-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0214_backfill_must_be_anonymised"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleattachment",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="Set to True if this file should not be publicly accessible",
                verbose_name="private",
            ),
        ),
        migrations.AddField(
            model_name="attachedfiles",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="Set to True if this file should not be publicly accessible",
                verbose_name="private",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="Set to True if this file should not be publicly accessible",
                verbose_name="private",
            ),
        ),
        migrations.AddField(
            model_name="partnerlogo",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="Set to True if this file should not be publicly accessible",
                verbose_name="private",
            ),
        ),
        migrations.AddField(
            model_name="publicationfile",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="Set to True if this file should not be publicly accessible",
                verbose_name="private",
            ),
        ),
        migrations.AddField(
            model_name="sourcefile",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="Set to True if this file should not be publicly accessible",
                verbose_name="private",
            ),
        ),
    ]
