# Generated by Django 4.2.14 on 2025-04-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0214_backfill_must_be_anonymised"),
    ]

    operations = [
        migrations.RenameField(
            model_name="work",
            old_name="ranking",
            new_name="pagerank",
        ),
        migrations.AddField(
            model_name="work",
            name="authority_score",
            field=models.FloatField(default=0.0, verbose_name="authority score"),
        ),
        migrations.AddField(
            model_name="work",
            name="n_citing_works_normalized",
            field=models.FloatField(
                default=0.0, verbose_name="number of incoming citations normalized"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="pagerank",
            field=models.FloatField(default=0.0, null=True, verbose_name="pagerank"),
        ),
        migrations.AddField(
            model_name="work",
            name="pagerank_normalized",
            field=models.FloatField(default=0.0, verbose_name="pagerank normalized"),
        ),
    ]
