# Generated by Django 4.2 on 2025-04-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0215_remove_work_ranking_work_authority_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachedfiles",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="Set to True if this file should not be publicly accessible",
                verbose_name="private",
            ),
        ),
    ]
