# Generated by Django 4.2.16 on 2025-05-02 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0216_attachedfiles_private"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvisionLevelEnrichment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.IntegerField(verbose_name="source id")),
                (
                    "provision_eid",
                    models.CharField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="provision eid",
                    ),
                ),
                (
                    "enrichment_type",
                    models.CharField(
                        choices=[
                            ("provision_enrichment", "Provision enrichment"),
                            (
                                "unconstitutional_provision",
                                "Unconstitutional provision",
                            ),
                        ],
                        default="provision_enrichment",
                        max_length=256,
                        verbose_name="enrichment type",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True, max_length=2048, null=True, verbose_name="text"
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichments",
                        to="peachjam.work",
                        verbose_name="work",
                    ),
                ),
            ],
            options={
                "verbose_name": "provision-level enrichment",
                "verbose_name_plural": "provision-level enrichments",
            },
        ),
        migrations.CreateModel(
            name="UnconstitutionalProvision",
            fields=[
                (
                    "provisionlevelenrichment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="peachjam.provisionlevelenrichment",
                    ),
                ),
                (
                    "date_deemed_unconstitutional",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="date deemed unconstitutional",
                    ),
                ),
                (
                    "end_of_suspension_period",
                    models.DateField(
                        blank=True, null=True, verbose_name="end of suspension period"
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(default=False, verbose_name="resolved"),
                ),
                (
                    "date_resolved",
                    models.DateField(
                        blank=True, null=True, verbose_name="date resolved"
                    ),
                ),
                (
                    "judgment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provisions_deemed_unconstitutional",
                        to="peachjam.work",
                        verbose_name="judgment",
                    ),
                ),
                (
                    "resolving_amendment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unconstitutional_provisions_resolved",
                        to="peachjam.work",
                        verbose_name="resolving amendment work",
                    ),
                ),
            ],
            options={
                "verbose_name": "unconstitutional provision",
                "verbose_name_plural": "unconstitutional provisions",
            },
            bases=("peachjam.provisionlevelenrichment",),
        ),
    ]
