# Generated by Django 4.2.14 on 2025-05-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0216_attachedfiles_private"),
    ]

    operations = [
        # sets anonymised to true on source documents created before "must be anonymised" was introduced,
        # but only if there is no HTML content
        migrations.RunSQL(
            """UPDATE peachjam_sourcefile sf
SET file_is_anonymised = TRUE
FROM peachjam_judgment j, peachjam_coredocument d, peachjam_documentcontent dc
WHERE j.coredocument_ptr_id = sf.document_id
  AND d.id = sf.document_id
  AND dc.document_id = sf.document_id
  AND j.anonymised IS TRUE
  AND sf.file_is_anonymised IS DISTINCT FROM TRUE
  AND (dc.content_text is null or length(dc.content_text) < 10)
  AND d.created_at <= '2025-04-22 00:00:00'::timestamp;
    """,
            migrations.RunSQL.noop,
        ),
    ]
