# Generated by Django 4.2.15 on 2025-05-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peachjam", "0217_backfill_anonymised_source_files")]

    operations = [
        migrations.AddField(
            model_name="saveddocument",
            name="folders",
            field=models.ManyToManyField(to="peachjam.folder"),
        ),
        migrations.AddField(
            model_name="saveddocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
    ]
