# Generated by Django 4.2.15 on 2025-05-13 09:17

from django.db import migrations


def backfill_saveddocument_folder(apps, schema_editor):
    Folder = apps.get_model("peachjam", "Folder")
    SavedDocument = apps.get_model("peachjam", "SavedDocument")
    null_documents = SavedDocument.objects.filter(folder__isnull=True)
    if null_documents:
        for obj in null_documents:
            my_documents, _ = Folder.objects.get_or_create(
                name="My Documents", user=obj.user
            )
            obj.folder = my_documents
            obj.save()

    for obj in SavedDocument.objects.all():
        obj.folders.add(obj.folder)


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0217_saveddocument_folders_saveddocument_updated_at"),
    ]

    operations = [
        migrations.RunPython(backfill_saveddocument_folder, migrations.RunPython.noop)
    ]
