# Generated by Django 4.2.15 on 2025-05-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0219_backfill_saveddocument_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saveddocument",
            name="folders",
            field=models.ManyToManyField(
                related_name="saved_documents", to="peachjam.folder"
            ),
        ),
    ]
