# Generated by Django 4.2.14 on 2025-05-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("peachjam", "0220_alter_saveddocument_folders")]

    operations = [
        migrations.AlterUniqueTogether(
            name="saveddocument",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="saveddocument",
            name="folder",
        ),
    ]
