# Generated by Django 4.2 on 2025-05-15 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("peachjam", "0222_alter_coredocument_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvisionEnrichment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provision_eid",
                    models.CharField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="provision eid",
                    ),
                ),
                (
                    "whole_work",
                    models.BooleanField(default=False, verbose_name="whole work"),
                ),
                (
                    "enrichment_type",
                    models.CharField(
                        choices=[
                            ("provision_enrichment", "Provision enrichment"),
                            (
                                "unconstitutional_provision",
                                "Unconstitutional provision",
                            ),
                        ],
                        default="provision_enrichment",
                        max_length=256,
                        verbose_name="enrichment type",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True, max_length=2048, null=True, verbose_name="text"
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichments",
                        to="peachjam.work",
                        verbose_name="work",
                    ),
                ),
            ],
            options={
                "verbose_name": "provision enrichment",
                "verbose_name_plural": "provision enrichments",
            },
        ),
        migrations.CreateModel(
            name="UnconstitutionalProvision",
            fields=[
                (
                    "provisionenrichment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="peachjam.provisionenrichment",
                    ),
                ),
                (
                    "date_deemed_unconstitutional",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="date deemed unconstitutional",
                    ),
                ),
                (
                    "end_of_suspension_period",
                    models.DateField(
                        blank=True, null=True, verbose_name="end of suspension period"
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(default=False, verbose_name="resolved"),
                ),
                (
                    "date_resolved",
                    models.DateField(
                        blank=True, null=True, verbose_name="date resolved"
                    ),
                ),
                (
                    "judgment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provisions_deemed_unconstitutional",
                        to="peachjam.work",
                        verbose_name="judgment",
                    ),
                ),
                (
                    "resolving_amendment_work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unconstitutional_provisions_resolved",
                        to="peachjam.work",
                        verbose_name="resolving amendment work",
                    ),
                ),
            ],
            options={
                "verbose_name": "unconstitutional provision",
                "verbose_name_plural": "unconstitutional provisions",
            },
            bases=("peachjam.provisionenrichment",),
        ),
    ]
