# Generated by Django 4.2.14 on 2025-05-22 13:45

from django.db import migrations
from django.db.models import Count


def limit_to_lowest(topics):
    """Limit the topics to the lowest level of the tree. This is used to avoid a document being tagged under
    a parent and a descendant taxonomy topic."""

    # walk bottom up and exclude topics that already have a descendant selected
    selected = []
    for topic in sorted(topics, key=lambda topic: topic.depth, reverse=True):
        if not any(t.path.startswith(topic.path) for t in selected):
            selected.append(topic)

    return selected


def redundant_topic_ids(topic_links):
    retained_ids = {
        topic.pk for topic in limit_to_lowest([link.topic for link in topic_links])
    }
    return [link.topic_id for link in topic_links if link.topic_id not in retained_ids]


def forwards(apps, schema_editor):
    CoreDocument = apps.get_model("peachjam", "CoreDocument")
    DocumentTopic = apps.get_model("peachjam", "DocumentTopic")

    # A document with only one topic cannot contain a redundant ancestor topic.
    # Work only on the small set with multiple assignments, and preserve the
    # existing through rows that should remain.
    document_ids = (
        CoreDocument.objects.annotate(topic_count=Count("taxonomies"))
        .filter(topic_count__gt=1)
        .values_list("pk", flat=True)
    )

    for document_id in document_ids.iterator(chunk_size=1000):
        topic_links = list(
            DocumentTopic.objects.filter(document_id=document_id).select_related(
                "topic"
            )
        )
        if redundant_ids := redundant_topic_ids(topic_links):
            DocumentTopic.objects.filter(
                document_id=document_id, topic_id__in=redundant_ids
            ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0222_alter_coredocument_options"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
