# Generated by Django 4.2 on 2025-06-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0224_provisionenrichment_unconstitutionalprovision"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="blurb",
            field=models.CharField(
                blank=True,
                help_text="A quick summary of the judgment, for use in listings",
                max_length=4096,
                null=True,
                verbose_name="blurb",
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="held",
            field=models.JSONField(
                blank=True,
                help_text="The main findings of the judgment",
                null=True,
                verbose_name="held",
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="issues",
            field=models.JSONField(
                blank=True,
                help_text="A list of issues that the judgment addresses",
                null=True,
                verbose_name="issues",
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="summary_ai_generated",
            field=models.BooleanField(
                default=False,
                help_text="Was this summary generated by an AI?",
                verbose_name="summary AI generated",
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="summary_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the AI summary was generated",
                null=True,
                verbose_name="summary generated at",
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="summary_trace_id",
            field=models.CharField(
                blank=True,
                help_text="The trace ID for the AI summary generation",
                max_length=1024,
                null=True,
                verbose_name="summary trace ID",
            ),
        ),
    ]
