# Generated by Django 4.2 on 2025-06-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0226_alter_coredocument_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="case_summary_ai",
            field=models.TextField(blank=True, null=True, verbose_name="case summary"),
        ),
    ]
