# Generated by Django 4.2 on 2025-06-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0227_judgment_case_summary_ai"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgment",
            name="case_summary_ai",
        ),
    ]
