# Generated by Django 4.2.16 on 2025-06-11 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0227_judgment_case_summary_ai"),
    ]

    operations = [
        migrations.CreateModel(
            name="UncommencedProvision",
            fields=[
                (
                    "provisionenrichment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="peachjam.provisionenrichment",
                    ),
                ),
                (
                    "and_all_descendants",
                    models.BooleanField(
                        default=False, verbose_name="and all descendants"
                    ),
                ),
            ],
            options={
                "verbose_name": "uncommenced provision",
                "verbose_name_plural": "uncommenced provisions",
            },
            bases=("peachjam.provisionenrichment",),
        ),
        migrations.AlterField(
            model_name="provisionenrichment",
            name="enrichment_type",
            field=models.CharField(
                choices=[
                    ("provision_enrichment", "Provision enrichment"),
                    ("unconstitutional_provision", "Unconstitutional provision"),
                    ("uncommenced_provision", "Uncommenced provision"),
                ],
                default="provision_enrichment",
                max_length=256,
                verbose_name="enrichment type",
            ),
        ),
    ]
