# Generated by Django 4.2 on 2025-06-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0228_remove_judgment_case_summary_ai"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="allow_anonymisation",
            field=models.BooleanField(
                default=False,
                help_text="Allow documents to be anonymised.",
                verbose_name="allow anonymisation",
            ),
        ),
    ]
