# Generated by Django 4.2.14 on 2025-06-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0228_remove_judgment_case_summary_ai"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coredocument",
            options={
                "ordering": ["doc_type", "title"],
                "permissions": [
                    ("can_delete_own_document", "Can delete own document"),
                    ("can_edit_own_document", "Can edit own document"),
                    ("can_edit_advanced_fields", "Can edit advanced fields"),
                    ("can_debug_document", "Can do document debugging"),
                    ("can_view_document_summary", "Can view document summary"),
                    ("can_generate_judgment_summary", "Can generate judgment summary"),
                    ("can_offline", "Can save content for offline use"),
                ],
            },
        ),
    ]
