# Generated by Django 4.2.14 on 2025-06-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0229_alter_coredocument_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxonomy",
            name="allow_offline",
            field=models.BooleanField(
                default=False,
                help_text="Allow users to make this taxonomy and its descendants available offline.",
                verbose_name="allow offline access",
            ),
        ),
    ]
