# Generated by Django 4.2.16 on 2025-07-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0232_taxonomy_allow_offline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provisionenrichment",
            name="text",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="text"
            ),
        ),
    ]
