# Generated by Django 4.2 on 2025-07-29 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0233_alter_provisionenrichment_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractedCitationContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selector_anchor_id",
                    models.CharField(
                        max_length=1024, verbose_name="selector anchor id"
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="prefix"
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="suffix"
                    ),
                ),
                (
                    "exact",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="exact"
                    ),
                ),
                (
                    "target_provision_eid",
                    models.CharField(
                        max_length=1024, null=True, verbose_name="target provision eid"
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citation_contexts",
                        to="peachjam.coredocument",
                        verbose_name="citation context",
                    ),
                ),
                (
                    "target_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="peachjam.work",
                        verbose_name="target work",
                    ),
                ),
            ],
        ),
    ]
