# Generated by Django 4.2 on 2025-08-04 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0233_alter_provisionenrichment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provisionenrichment",
            name="enrichment_type",
            field=models.CharField(
                choices=[
                    ("provision_enrichment", "Provision enrichment"),
                    ("unconstitutional_provision", "Unconstitutional provision"),
                    ("uncommenced_provision", "Uncommenced provision"),
                    ("provision_citation", "Provision citation"),
                ],
                default="provision_enrichment",
                max_length=256,
                verbose_name="enrichment type",
            ),
        ),
        migrations.CreateModel(
            name="ProvisionCitation",
            fields=[
                (
                    "provisionenrichment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="peachjam.provisionenrichment",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="prefix"
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="suffix"
                    ),
                ),
                (
                    "exact",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="exact"
                    ),
                ),
                (
                    "citing_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provision_citations",
                        to="peachjam.coredocument",
                        verbose_name="citing document",
                    ),
                ),
            ],
            options={
                "verbose_name": "provision citation",
                "verbose_name_plural": "provision citations",
            },
            bases=("peachjam.provisionenrichment",),
        ),
    ]
