# Generated by Django 4.2.16 on 2025-08-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0234_provision_citations"),
    ]

    operations = [
        migrations.AddField(
            model_name="unconstitutionalprovision",
            name="read_in_text_html",
            field=models.CharField(
                blank=True, max_length=4096, null=True, verbose_name="read-in text HTML"
            ),
        ),
    ]
