# Generated by Django 4.2.16 on 2025-08-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0235_unconstitutionalprovision_read_in_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unconstitutionalprovision",
            name="read_in_text_html",
            field=models.CharField(
                blank=True,
                max_length=16384,
                null=True,
                verbose_name="read-in text HTML",
            ),
        ),
    ]
