# Generated by Django 4.2.15 on 2025-08-13 11:56

from django.db import migrations


def delete_saved_documents_without_folder(apps, schema_editor):
    SavedDocument = apps.get_model("peachjam", "SavedDocument")
    null_documents = SavedDocument.objects.filter(folders__isnull=True)
    for obj in null_documents:
        obj.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0236_alter_unconstitutionalprovision_read_in_text_html"),
    ]

    operations = [
        migrations.RunPython(
            delete_saved_documents_without_folder, migrations.RunPython.noop
        ),
    ]
