# Generated by Django 4.2 on 2025-08-19 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0237_delete_saved_documents_without_folder"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("new_documents", "New Documents")], max_length=256
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_notified", models.BooleanField(default=False)),
                (
                    "subject_documents",
                    models.ManyToManyField(
                        related_name="+", to="peachjam.coredocument"
                    ),
                ),
                (
                    "user_following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="peachjam.userfollowing",
                    ),
                ),
            ],
        ),
    ]
