# Generated by Django 4.2 on 2025-08-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0238_timelineevent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timelineevent",
            name="user_notified",
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="email_alert_sent_at",
            field=models.DateTimeField(null=True),
        ),
    ]
