# Generated by Django 4.2 on 2025-08-21 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_search", "0019_es_mapping_add_summary"),
        ("peachjam", "0239_remove_timelineevent_user_notified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfollowing",
            name="saved_search",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="peachjam_search.savedsearch",
                verbose_name="saved search",
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("new_documents", "New Documents"),
                    ("saved_search", "Saved Search"),
                ],
                max_length=256,
            ),
        ),
        migrations.AddConstraint(
            model_name="userfollowing",
            constraint=models.UniqueConstraint(
                condition=models.Q(("saved_search__isnull", False)),
                fields=("user", "saved_search"),
                name="unique_user_saved_seardh",
            ),
        ),
    ]
