# Generated by Django 4.2 on 2025-08-27 14:32
import logging

from django.db import migrations

log = logging.getLogger(__name__)


def create_follows_for_saved_searches(apps, schema_editor):
    UserFollowing = apps.get_model("peachjam", "UserFollowing")
    SavedSearch = apps.get_model("peachjam_search", "SavedSearch")

    for saved_search in SavedSearch.objects.all():
        uf, new = UserFollowing.objects.get_or_create(
            user=saved_search.user,
            saved_search=saved_search,
        )
        if new:
            log.info(
                f"Created follow for saved search {saved_search.id} and user {saved_search.user_id}"
            )
        else:
            log.info(
                f"Follow already exists for saved search {saved_search.id} and user {saved_search.user_id}"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0240_userfollowing_saved_search_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_follows_for_saved_searches, migrations.RunPython.noop
        ),
    ]
