# Generated by Django 4.2 on 2025-09-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0241_create_saved_search_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineevent",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
