# Generated by Django 4.2 on 2025-10-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0244_alter_coredocument_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coredocument",
            options={
                "ordering": ["doc_type", "title"],
                "permissions": [
                    ("can_delete_own_document", "Can delete own document"),
                    ("can_edit_own_document", "Can edit own document"),
                    ("can_edit_advanced_fields", "Can edit advanced fields"),
                    ("can_debug_document", "Can do document debugging"),
                    ("can_view_document_summary", "Can view document summary"),
                    ("can_generate_judgment_summary", "Can generate judgment summary"),
                    ("can_offline", "Can save content for offline use"),
                    (
                        "can_view_historical_legislation",
                        "Can view historical legislation",
                    ),
                    ("can_view_case_history", "Can view case history"),
                    ("can_view_provision_changes", "Can view provision changes"),
                ],
            },
        ),
    ]
