# Generated by Django 4.2.16 on 2025-10-06 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0244_alter_coredocument_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Glossary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_code",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z]{2}(-[a-z]+)?$",
                                "Two lowercase letters (a country code), optionally followed by '-' and a lowercase locality code",
                            )
                        ],
                        verbose_name="place code",
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="data")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
