# Generated by Django 4.2.14 on 2025-10-08 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0245_alter_coredocument_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="accepted_terms_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the user accepted the terms of service.",
                verbose_name="accepted terms at",
                null=True,
                blank=True,
            ),
        ),
    ]
