# Generated by Django 4.2.14 on 2025-10-11 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0246_userprofile_accepted_terms_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvisionCitationCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provision_eid",
                    models.CharField(
                        max_length=2048, null=False, verbose_name="provision eid"
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0, verbose_name="count")),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provision_citation_counts",
                        to="peachjam.work",
                        verbose_name="work",
                    ),
                ),
            ],
            options={
                "verbose_name": "provision citation count",
                "verbose_name_plural": "provision citation counts",
            },
        ),
        migrations.AddConstraint(
            model_name="provisioncitationcount",
            constraint=models.UniqueConstraint(
                fields=("work", "provision_eid"), name="unique_provision_citation_count"
            ),
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO peachjam_provisioncitationcount (work_id, provision_eid, count)
                SELECT pe.work_id,
                       pe.provision_eid,
                       COUNT(DISTINCT pc.citing_document_id) AS citation_count
                FROM peachjam_provisionenrichment pe
                INNER JOIN peachjam_provisioncitation pc ON pc.provisionenrichment_ptr_id = pe.id
                WHERE pe.enrichment_type = 'provision_citation' AND pe.provision_eid IS NOT NULL
                GROUP BY pe.work_id, pe.provision_eid
                """,
            reverse_sql="DELETE FROM peachjam_provisioncitationcount",
        ),
    ]
