# Generated by Django 4.2 on 2025-11-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0248_glossary"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="case_summary_public",
            field=models.BooleanField(
                default=False,
                help_text="Always show the case summary publicly, even when generated by AI.",
                verbose_name="case summary public",
            ),
        ),
    ]
