# Generated by Django 4.2 on 2025-11-05 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0248_glossary"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveddocument",
            name="work",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_documents",
                to="peachjam.work",
                verbose_name="work",
            ),
        ),
    ]
