# Generated by Django 4.2 on 2025-11-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0248_glossary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="saveddocument",
            options={
                "ordering": ("work__title",),
                "verbose_name": "saved document",
                "verbose_name_plural": "saved documents",
            },
        ),
        migrations.AddField(
            model_name="saveddocument",
            name="work",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_documents",
                to="peachjam.work",
                verbose_name="work",
            ),
        ),
    ]
