# Generated by Django 4.2 on 2025-11-12 08:45

from django.db import migrations


def forwards_func(apps, schema_editor):
    SavedDocument = apps.get_model("peachjam", "SavedDocument")
    CoreDocument = apps.get_model("peachjam", "CoreDocument")
    for saved_doc in SavedDocument.objects.filter(work__isnull=True):
        core_doc = CoreDocument.objects.filter(id=saved_doc.document_id).first()
        if core_doc and core_doc.work_id:
            saved_doc.work_id = core_doc.work_id
            saved_doc.save(update_fields=["work"])


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0249_alter_saveddocument_options_saveddocument_work"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
