# Generated by Django 4.2 on 2025-11-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0249_userfollowing_saved_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineevent",
            name="subject_works",
            field=models.ManyToManyField(related_name="+", to="peachjam.work"),
        ),
    ]
