# Generated by Django 4.2 on 2025-11-12 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0250_backfill_saved_doc_work"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saveddocument",
            name="work",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_documents",
                to="peachjam.work",
                verbose_name="work",
            ),
            preserve_default=False,
        ),
    ]
