# Generated by Django 4.2 on 2025-11-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0250_saved_document_backfill_work"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="saveddocument",
            options={
                "ordering": ("work__title",),
                "verbose_name": "saved document",
                "verbose_name_plural": "saved documents",
            },
        ),
        migrations.RemoveField(
            model_name="saveddocument",
            name="document",
        ),
    ]
