# Generated by Django 4.2 on 2025-11-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0251_alter_saveddocument_work"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saveddocument",
            name="document",
        ),
    ]
