# Generated by Django 4.2 on 2025-11-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0253_remove_saveddocument_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineevent",
            name="subject_works",
            field=models.ManyToManyField(related_name="+", to="peachjam.work"),
        ),
    ]
