# Generated by Django 4.2 on 2025-11-18 02:28

from django.db import migrations


def forwards_func(apps, schema_editor):
    TimelineEvent = apps.get_model("peachjam", "TimelineEvent")
    Work = apps.get_model("peachjam", "Work")

    for event in TimelineEvent.objects.all():
        work_ids = event.subject_documents.all().values_list("work__id", flat=True)
        works = Work.objects.filter(id__in=work_ids).distinct()
        event.subject_works.set(works)


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0254_timelineevent_subject_works"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
