# Generated by Django 4.2 on 2025-11-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0255_backfill_timeline_subject_works"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timelineevent",
            name="subject_documents",
        ),
    ]
