# Generated by Django 4.2 on 2025-11-19 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0256_remove_timelineevent_subject_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfollowing",
            name="saved_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="peachjam.saveddocument",
                verbose_name="saved document",
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("new_documents", "New Documents"),
                    ("saved_search", "Saved Search"),
                    ("new_citation", "New Citation"),
                    ("new_amendment", "New Amendment"),
                ],
                max_length=256,
            ),
        ),
        migrations.AddConstraint(
            model_name="userfollowing",
            constraint=models.UniqueConstraint(
                condition=models.Q(("saved_document__isnull", False)),
                fields=("user", "saved_document"),
                name="unique_user_saved_document",
            ),
        ),
    ]
