# Generated by Django 4.2 on 2025-11-20 10:31

from django.db import migrations


def forwards_func(apps, schema_editor):
    # create user follows from existing saved documents
    SavedDocument = apps.get_model("peachjam", "SavedDocument")
    UserFollowing = apps.get_model("peachjam", "UserFollowing")
    for saved_doc in SavedDocument.objects.all():
        UserFollowing.objects.get_or_create(
            user=saved_doc.user,
            saved_document=saved_doc,
            defaults={"created_at": saved_doc.created_at},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0257_userfollowing_saved_document_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
