# Generated by Django 4.2.27 on 2025-12-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0258_backfill_saved_docs_follows"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
          WITH latest_expression_date AS (
              SELECT DISTINCT ON (work_id)
                  work_id, id AS document_id, date
              FROM peachjam_coredocument
              ORDER BY work_id, date DESC
          )
          DELETE FROM peachjam_timelineevent_subject_works AS sw
          USING peachjam_timelineevent AS te,
                latest_expression_date AS lde
          WHERE sw.timelineevent_id = te.id
            AND sw.work_id = lde.work_id
            AND te.event_type = 'new_citation'
            AND lde.date < DATE '2024-12-01';
          """,
            reverse_sql="",
        ),
    ]
