# Generated by Django 4.2.27 on 2025-12-04 11:07

from django.db import migrations


def forwards_func(apps, schema):
    TimelineEvent = apps.get_model("peachjam", "TimelineEvent")
    te = TimelineEvent.objects.filter(subject_works__isnull=True)
    te.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0259_remove_old_timeline_subject_works"),
    ]

    operations = [migrations.RunPython(forwards_func, migrations.RunPython.noop)]
