# Generated by Django 4.2.14 on 2025-12-10 11:42

import re

from django.db import migrations

# handles starts at the start which don't need to preserve whitespace
STARTING_STAR = re.compile(r"^\s*\*\s*")
# handles stars in the middle which need to preserve at least one space
STARS = re.compile(r"\s+\*\s+")


def clean_flynote(value):
    if not value:
        return value
    value = STARTING_STAR.sub("", value)
    value = STARS.sub(" ", value)
    return value.strip()


def forwards_func(apps, schema_editor):
    Judgment = apps.get_model("peachjam", "Judgment")
    judgments = Judgment.objects.filter(flynote__isnull=False, flynote__contains="*")

    for judgment in judgments.all():
        cleaned = clean_flynote(judgment.flynote)
        if cleaned != judgment.flynote:
            judgment.flynote = cleaned
            judgment.save(update_fields=["flynote"])


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0260_remove_empty_timelines"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
