# Generated by Django 4.2.27 on 2025-12-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0262_unique_timeline_event_email_alert"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="timelineevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email_alert_sent_at__isnull", True)),
                fields=("user_following", "event_type"),
                name="unique_user_following_email_alert",
            ),
        ),
    ]
