# Generated by Django 4.2.27 on 2026-01-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0263_alter_timeline_unique_constraint"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Journal",
            new_name="JournalArticle",
        ),
        migrations.RemoveField(
            model_name="attachedfilenature",
            name="name_fr",
        ),
        migrations.RemoveField(
            model_name="attachedfilenature",
            name="name_pt",
        ),
        migrations.RemoveField(
            model_name="court",
            name="name_fr",
        ),
        migrations.RemoveField(
            model_name="court",
            name="name_pt",
        ),
        migrations.RemoveField(
            model_name="courtclass",
            name="name_fr",
        ),
        migrations.RemoveField(
            model_name="courtclass",
            name="name_pt",
        ),
        migrations.RemoveField(
            model_name="custompropertylabel",
            name="name_fr",
        ),
        migrations.RemoveField(
            model_name="custompropertylabel",
            name="name_pt",
        ),
        migrations.RemoveField(
            model_name="documentnature",
            name="name_fr",
        ),
        migrations.RemoveField(
            model_name="documentnature",
            name="name_pt",
        ),
        migrations.RemoveField(
            model_name="label",
            name="name_fr",
        ),
        migrations.RemoveField(
            model_name="label",
            name="name_pt",
        ),
        migrations.RemoveField(
            model_name="outcome",
            name="name_fr",
        ),
        migrations.RemoveField(
            model_name="outcome",
            name="name_pt",
        ),
        migrations.RemoveField(
            model_name="predicate",
            name="reverse_verb_fr",
        ),
        migrations.RemoveField(
            model_name="predicate",
            name="reverse_verb_pt",
        ),
        migrations.RemoveField(
            model_name="predicate",
            name="verb_fr",
        ),
        migrations.RemoveField(
            model_name="predicate",
            name="verb_pt",
        ),
        migrations.RemoveField(
            model_name="taxonomy",
            name="name_fr",
        ),
        migrations.RemoveField(
            model_name="taxonomy",
            name="name_pt",
        ),
        migrations.RemoveField(
            model_name="taxonomy",
            name="path_name_fr",
        ),
        migrations.RemoveField(
            model_name="taxonomy",
            name="path_name_pt",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="name_fr",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="name_pt",
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("core_document", "Core Document"),
                    ("bill", "Bill"),
                    ("gazette", "Gazette"),
                    ("generic_document", "Generic Document"),
                    ("judgment", "Judgment"),
                    ("legal_instrument", "Legal Instrument"),
                    ("legislation", "Legislation"),
                    ("book", "Book"),
                    ("journal_article", "JournalArticle"),
                    ("causelist", "Cause List"),
                ],
                default="core_document",
                max_length=255,
                verbose_name="document type",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courtregistry",
            unique_together={
                ("court", "name_en"),
                ("court", "name"),
                ("court", "name_sw"),
            },
        ),
        migrations.RemoveField(
            model_name="courtregistry",
            name="name_fr",
        ),
        migrations.RemoveField(
            model_name="courtregistry",
            name="name_pt",
        ),
    ]
