# Generated by Django 4.2.27 on 2026-01-07 15:53

from django.db import migrations


def update_journal_article_metadata(apps, schema_editor):
    JournalArticle = apps.get_model("peachjam", "JournalArticle")
    JournalArticle.objects.all().update(
        doc_type="journal_article", frbr_uri_subtype="journal-article"
    )


def reverse_update(apps, schema_editor):
    # Optional: Logic to revert changes if you unapply the migration
    JournalArticle = apps.get_model("peachjam", "JournalArticle")
    JournalArticle.objects.filter(doc_type="journal_article").update(
        doc_type="journal", frbr_uri_subtype="journal"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0264_rename_journal_journalarticle_and_more"),
    ]

    operations = [
        migrations.RunPython(update_journal_article_metadata, reverse_update),
    ]
