# Generated by Django 4.2.27 on 2026-01-07 15:53
import logging

from django.db import migrations
from django.db.models import F, Value
from django.db.models.functions import Replace

from peachjam_search.tasks import search_model_saved


def update_journal_article_metadata(apps, schema_editor):
    JournalArticle = apps.get_model("peachjam", "JournalArticle")

    JournalArticle.objects.all().update(
        doc_type="journal_article",
        frbr_uri_subtype="journal-article",
        expression_frbr_uri=Replace(
            F("expression_frbr_uri"),
            Value("/journal/"),
            Value("/journal-article/"),
        ),
        work_frbr_uri=Replace(
            F("work_frbr_uri"),
            Value("/journal/"),
            Value("/journal-article/"),
        ),
    )
    Work = apps.get_model("peachjam", "Work")
    Work.objects.filter(frbr_uri_subtype="journal").update(
        frbr_uri_subtype="journal-article",
        frbr_uri=Replace(
            F("frbr_uri"),
            Value("/journal/"),
            Value("/journal-article/"),
        ),
    )


def reverse_update(apps, schema_editor):
    # Optional: Logic to revert changes if you unapply the migration
    JournalArticle = apps.get_model("peachjam", "JournalArticle")

    JournalArticle.objects.filter(doc_type="journal_article").update(
        doc_type="journal",
        frbr_uri_subtype="journal",
        expression_frbr_uri=Replace(
            F("expression_frbr_uri"),
            Value("/journal-article/"),
            Value("/journal/"),
        ),
        work_frbr_uri=Replace(
            F("work_frbr_uri"),
            Value("/journal-article/"),
            Value("/journal/"),
        ),
    )
    Work = apps.get_model("peachjam", "Work")
    Work.objects.filter(frbr_uri_subtype="journal-article").update(
        frbr_uri_subtype="journal",
        frbr_uri=Replace(
            F("frbr_uri"),
            Value("/journal-article/"),
            Value("/journal/"),
        ),
    )


def reindex_journal_articles(apps, schema_editor):
    JournalArticle = apps.get_model("peachjam", "JournalArticle")
    qs = JournalArticle.objects.order_by("pk").values_list("pk", flat=True)

    count = 0
    for pk in qs.iterator():
        search_model_saved("peachjam.JournalArticle", pk)
        count += 1

    logging.info("Reindexed {} journal articles".format(count))


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0264_rename_journal_journalarticle_and_more"),
    ]

    operations = [
        migrations.RunPython(
            update_journal_article_metadata, reverse_update, reindex_journal_articles
        ),
    ]
