# Generated by Django 4.2.27 on 2026-01-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0265_auto_20260107_1553"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                (
                    "doi",
                    models.CharField(
                        max_length=255, verbose_name="Directory of Indexing (DOI)"
                    ),
                ),
            ],
        ),
    ]
