# Generated by Django 4.2.27 on 2026-01-20 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0265_auto_20260107_1553"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512, unique=True)),
                ("slug", models.SlugField(default="", max_length=512)),
                (
                    "doi",
                    models.CharField(
                        max_length=255, verbose_name="Directory of Indexing (DOI)"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="coredocument",
            name="summary",
            field=models.TextField(blank=True, null=True, verbose_name="summary"),
        ),
        migrations.AddField(
            model_name="journalarticle",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="peachjam.author"
            ),
        ),
        migrations.AddField(
            model_name="journalarticle",
            name="page_range",
            field=models.CharField(
                blank=True,
                help_text="Page range, e.g. pages 17-24",
                max_length=255,
                null=True,
                verbose_name="page range",
            ),
        ),
        migrations.AddField(
            model_name="journalarticle",
            name="slug",
            field=models.SlugField(blank=True, max_length=512, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="VolumeIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The volume and issue number (e.g., 'Vol 58, Issue 1' or 'Volume 58')",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, default="", max_length=255, null=True),
                ),
                ("issue", models.IntegerField()),
                (
                    "year",
                    models.IntegerField(
                        db_index=True,
                        help_text="Publication year used for sorting and faceting",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volumes",
                        to="peachjam.journal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volume/Issue",
                "verbose_name_plural": "Volumes/Issues",
                "ordering": ["-year", "title"],
            },
        ),
        migrations.AddField(
            model_name="journalarticle",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="peachjam.journal",
            ),
        ),
        migrations.AddField(
            model_name="journalarticle",
            name="volume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="peachjam.volumeissue",
            ),
        ),
    ]
