# Generated by Django 4.2.27 on 2026-01-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0266_journals"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="volumeissue",
            unique_together={("journal", "title")},
        ),
    ]
