# Generated by Django 4.2.27 on 2026-01-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0266_journals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="doi",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Digital Object Identifier (DOI)",
            ),
        ),
        migrations.AlterField(
            model_name="volumeissue",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="volumeissue",
            unique_together={("journal", "slug")},
        ),
    ]
