# Generated by Django 4.2.27 on 2026-01-12 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0267_journalarticle_journal"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolumeIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The volume and issue number (e.g., 'Vol 58, Issue 1' or 'Volume 58')",
                        max_length=255,
                    ),
                ),
                ("issue", models.IntegerField()),
                (
                    "year",
                    models.IntegerField(
                        db_index=True,
                        help_text="Publication year used for sorting and faceting",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volumes",
                        to="peachjam.journal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volume/Issue",
                "verbose_name_plural": "Volumes/Issues",
                "ordering": ["-year", "title"],
            },
        ),
    ]
