# Generated by Django 4.2.27 on 2026-01-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0267_alter_journal_doi_alter_volumeissue_slug_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="volumeissue",
            unique_together={("journal", "title"), ("journal", "slug")},
        ),
    ]
