# Generated by Django 4.2.15 on 2026-02-03 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0268_alter_volumeissue_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="courtregistry",
            unique_together={("court", "name")},
        ),
        migrations.AlterField(
            model_name="author",
            name="code",
            field=models.SlugField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9_-]+$",
                        "Only lowercase letters, numbers, _ and - allowed",
                    )
                ],
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("new_documents", "New Documents"),
                    ("saved_search", "Saved Search"),
                    ("new_citation", "New Citation"),
                    ("new_amendment", "New Amendment"),
                    ("new_repeal", "New Repeal"),
                    ("new_commencement", "New Commencement"),
                    ("new_overturn", "New Overturn"),
                ],
                max_length=256,
            ),
        ),
    ]
