# Generated by Django 4.2.27 on 2026-02-11 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries_plus", "0005_auto_20160224_1804"),
        ("peachjam", "0268_alter_volumeissue_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArbitralInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "acronym",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="acronym"
                    ),
                ),
                (
                    "headquarters_city",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="headquarters city"
                    ),
                ),
                (
                    "is_internationally_recognized",
                    models.BooleanField(
                        default=False, verbose_name="internationally recognized"
                    ),
                ),
            ],
            options={
                "verbose_name": "arbitral institution",
                "verbose_name_plural": "arbitral institutions",
                "ordering": ("name",),
            },
        ),
        migrations.AlterField(
            model_name="coredocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("core_document", "Core Document"),
                    ("bill", "Bill"),
                    ("gazette", "Gazette"),
                    ("generic_document", "Generic Document"),
                    ("judgment", "Judgment"),
                    ("legal_instrument", "Legal Instrument"),
                    ("legislation", "Legislation"),
                    ("book", "Book"),
                    ("journal_article", "Journal Article"),
                    ("causelist", "Cause List"),
                    ("arbitration_award", "Arbitration Award"),
                ],
                default="core_document",
                max_length=255,
                verbose_name="document type",
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("new_documents", "New Documents"),
                    ("saved_search", "Saved Search"),
                    ("new_citation", "New Citation"),
                    ("new_amendment", "New Amendment"),
                    ("new_repeal", "New Repeal"),
                    ("new_commencement", "New Commencement"),
                    ("new_overturn", "New Overturn"),
                ],
                max_length=256,
            ),
        ),
        migrations.CreateModel(
            name="ArbitrationSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255, verbose_name="city")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
                (
                    "is_new_york_convention_signatory",
                    models.BooleanField(
                        default=True,
                        help_text="Can awards be enforced in 170+ countries.",
                        verbose_name="New York Convention signatory",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countries_plus.country",
                        verbose_name="country",
                    ),
                ),
            ],
            options={
                "verbose_name": "arbitration seat",
                "verbose_name_plural": "arbitration seats",
                "ordering": ("city", "country"),
            },
        ),
        migrations.CreateModel(
            name="ArbitrationAward",
            fields=[
                (
                    "coredocument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="peachjam.coredocument",
                    ),
                ),
                (
                    "case_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="case number"
                    ),
                ),
                (
                    "applicable_law",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="applicable law"
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("INVESTOR_STATE", "Investor State"),
                            ("COMMERCIAL", "Commercial Arbitration"),
                            ("IIA", "International Investor Agreement"),
                        ],
                        max_length=50,
                        verbose_name="case type",
                    ),
                ),
                (
                    "award_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FINAL", "Final Award"),
                            ("INTERIM", "Interim Award"),
                            ("PARTIAL", "Partial Award"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="award type",
                    ),
                ),
                (
                    "nature_of_proceedings",
                    models.CharField(
                        choices=[
                            ("DOMESTIC", "Domestic"),
                            ("INTERNATIONAL", "International"),
                        ],
                        max_length=50,
                        verbose_name="nature of proceedings",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CLAIMANT", "In Favour of Claimant"),
                            ("RESPONDENT", "In Favour of Respondent"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="outcome",
                    ),
                ),
                (
                    "claimants_country_of_origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awards_as_claimants",
                        to="countries_plus.country",
                        verbose_name="claimants country of origin",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="peachjam.arbitralinstitution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "respondents_country_of_origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awards_as_respondents",
                        to="countries_plus.country",
                        verbose_name="respondents country of origin",
                    ),
                ),
                (
                    "rules_of_arbitration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arbitration_rules",
                        to="peachjam.coredocument",
                        verbose_name="rules of arbitration",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="peachjam.arbitrationseat",
                        verbose_name="seat",
                    ),
                ),
            ],
            options={
                "verbose_name": "arbitration award",
                "verbose_name_plural": "arbitration awards",
            },
            bases=("peachjam.coredocument",),
        ),
    ]
