# Generated by Django 4.2.27 on 2026-02-09 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries_plus", "0005_auto_20160224_1804"),
        ("peachjam", "0268_alter_volumeissue_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArbitralInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("acronym", models.CharField(blank=True, max_length=50, unique=True)),
                ("headquarters_city", models.CharField(blank=True, max_length=255)),
                ("is_internationally_recognized", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("new_documents", "New Documents"),
                    ("saved_search", "Saved Search"),
                    ("new_citation", "New Citation"),
                    ("new_amendment", "New Amendment"),
                    ("new_repeal", "New Repeal"),
                    ("new_commencement", "New Commencement"),
                    ("new_overturn", "New Overturn"),
                ],
                max_length=256,
            ),
        ),
        migrations.CreateModel(
            name="ArbitrationSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "is_new_york_convention_signatory",
                    models.BooleanField(
                        default=True,
                        help_text="Can awards be enforced in 170+ countries.",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countries_plus.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArbitrationAward",
            fields=[
                (
                    "coredocument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="peachjam.coredocument",
                    ),
                ),
                ("case_number", models.CharField(max_length=100, unique=True)),
                ("applicable_law", models.CharField(blank=True, max_length=255)),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("INVESTOR_STATE", "Investor State"),
                            ("COMMERCIAL", "Commercial Arbitration"),
                            ("IIA", "International Investor Agreement"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "award_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FINAL", "Final Award"),
                            ("INTERIM", "Interim Award"),
                            ("PARTIAL", "Partial Award"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "nature_of_proceedings",
                    models.CharField(
                        choices=[
                            ("DOMESTIC", "Domestic"),
                            ("INTERNATIONAL", "International"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CLAIMANT", "In Favour of Claimant"),
                            ("RESPONDENT", "In Favour of Respondent"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "claimants_country_of_origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awards_as_claimants",
                        to="countries_plus.country",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="peachjam.arbitralinstitution",
                    ),
                ),
                (
                    "respondents_county_of_origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awards_as_respondents",
                        to="countries_plus.country",
                    ),
                ),
                (
                    "rules_of_arbitration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arbitration_rules",
                        to="peachjam.coredocument",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="peachjam.arbitrationseat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arbitration Award",
            },
            bases=("peachjam.coredocument",),
        ),
    ]
