# Generated by Django 4.2.27 on 2026-02-12 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0268_alter_volumeissue_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="LawReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=2048, unique=True, verbose_name="title"
                    ),
                ),
                ("slug", models.CharField(max_length=2048, unique=True)),
            ],
            options={
                "verbose_name": "law report",
                "verbose_name_plural": "law reports",
                "ordering": ("title",),
            },
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("new_documents", "New Documents"),
                    ("saved_search", "Saved Search"),
                    ("new_citation", "New Citation"),
                    ("new_amendment", "New Amendment"),
                    ("new_repeal", "New Repeal"),
                    ("new_commencement", "New Commencement"),
                    ("new_overturn", "New Overturn"),
                ],
                max_length=256,
            ),
        ),
        migrations.CreateModel(
            name="LawReportVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=2048, unique=True, verbose_name="title"
                    ),
                ),
                ("slug", models.CharField(max_length=2048, unique=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "law_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volumes",
                        to="peachjam.lawreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "law report volume",
                "verbose_name_plural": "law report volumes",
                "ordering": ("title",),
                "unique_together": {("law_report", "slug")},
            },
        ),
        migrations.CreateModel(
            name="LawReportEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judgment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="law_report_entries",
                        to="peachjam.judgment",
                    ),
                ),
                (
                    "law_report_volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="law_report_entries",
                        to="peachjam.lawreportvolume",
                    ),
                ),
            ],
            options={
                "verbose_name": "law report entry",
                "verbose_name_plural": "law report entries",
            },
        ),
    ]
