# Generated by Django 4.2.27 on 2026-01-12 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0268_volumeissue"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalarticle",
            name="volume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="peachjam.volumeissue",
            ),
        ),
    ]
