# Generated by Django 4.2.27 on 2026-02-12 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0269_adds_arbitration_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="LawReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=2048, unique=True, verbose_name="title"
                    ),
                ),
                ("slug", models.CharField(max_length=2048, unique=True)),
            ],
            options={
                "verbose_name": "law report",
                "verbose_name_plural": "law reports",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="LawReportVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=2048, verbose_name="title")),
                ("slug", models.CharField(max_length=2048)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "law_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volumes",
                        to="peachjam.lawreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "law report volume",
                "verbose_name_plural": "law report volumes",
                "ordering": ("title",),
                "unique_together": {("law_report", "slug")},
            },
        ),
        migrations.CreateModel(
            name="LawReportEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judgment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="law_report_entries",
                        to="peachjam.judgment",
                    ),
                ),
                (
                    "law_report_volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="law_report_entries",
                        to="peachjam.lawreportvolume",
                    ),
                ),
            ],
            options={
                "verbose_name": "law report entry",
                "verbose_name_plural": "law report entries",
            },
        ),
    ]
