# Generated by Django 4.2.27 on 2026-01-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0269_journalarticle_volume"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="slug",
            field=models.SlugField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="volumeissue",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
