# Generated by Django 4.2.27 on 2026-02-11 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0269_lawreport_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawreportentry",
            name="law_report_volume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="law_report_entries",
                to="peachjam.lawreportvolume",
            ),
        ),
    ]
