# Generated by Django 4.2.27 on 2026-01-12 13:40

from django.db import migrations


def ensure_volume_column(apps, schema_editor):
    model = apps.get_model("peachjam", "JournalArticle")
    table = model._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        columns = [
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table
            )
        ]
    if "volume_id" in columns:
        return
    field = model._meta.get_field("volume")
    schema_editor.add_field(model, field)


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0270_journal_slug_volumeissue_slug"),
    ]

    operations = [
        migrations.RunPython(
            ensure_volume_column, reverse_code=migrations.RunPython.noop
        ),
    ]
