# Generated by Django 4.2.28 on 2026-02-24 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0271_document_chat_thread"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="flynote_taxonomy_root",
            field=models.ForeignKey(
                blank=True,
                help_text="Root taxonomy node for automatically managed flynote topics.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="peachjam.taxonomy",
                verbose_name="flynote taxonomy root",
            ),
        ),
    ]
