# Generated by Django 4.2.27 on 2026-02-19 14:35

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0271_document_chat_thread"),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgmentOffence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="judgment",
            name="case_type",
            field=models.CharField(
                blank=True,
                choices=[("criminal", "Criminal"), ("civil", "Civil")],
                max_length=512,
                null=True,
                verbose_name="case type",
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="filing_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Year the matter was filed (YYYY only).",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1800),
                    django.core.validators.MaxValueValidator(2026),
                ],
                verbose_name="filing year",
            ),
        ),
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentence_type",
                    models.CharField(
                        choices=[
                            ("imprisonment", "Imprisonment"),
                            ("fine", "Fine"),
                            ("probation", "Probation"),
                        ],
                        max_length=32,
                        verbose_name="sentence type",
                    ),
                ),
                (
                    "mandatory_minimum",
                    models.BooleanField(
                        blank=True,
                        help_text="True if the sentence reflects a mandatory minimum.",
                        null=True,
                        verbose_name="mandatory minimum",
                    ),
                ),
                (
                    "duration_months",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Imprisonment/probation duration in months, if applicable.",
                        null=True,
                        verbose_name="duration (months)",
                    ),
                ),
                (
                    "suspended",
                    models.BooleanField(
                        default=False,
                        help_text="True if the sentence is suspended (fully or partially).",
                        verbose_name="suspended",
                    ),
                ),
                (
                    "fine_amount",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Fine amount",
                        null=True,
                        verbose_name="fine amount",
                    ),
                ),
                (
                    "judgment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        to="peachjam.judgment",
                        verbose_name="offences",
                    ),
                ),
                (
                    "offence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        to="peachjam.judgmentoffence",
                        verbose_name="offences",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="Offence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provision_eid",
                    models.CharField(
                        help_text="AKN element id / EID for the provision within the code (e.g., 'sec_296').",
                        max_length=2048,
                        verbose_name="provision EID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Internal offence code / short identifier (often from the code or a local convention).",
                        max_length=2048,
                        verbose_name="offence code",
                    ),
                ),
                ("title", models.CharField(max_length=4096, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "elements",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=4096),
                        blank=True,
                        default=list,
                        help_text="List of offence elements (actus reus, mens rea, etc.).",
                        size=None,
                    ),
                ),
                (
                    "penalty",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable recommended/typical penalty guidance.",
                        verbose_name="recommended penalty",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        help_text="The Work for the code (e.g., Penal Code) that defines this offence.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offences",
                        to="peachjam.work",
                        verbose_name="work",
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
                "unique_together": {("work", "provision_eid")},
            },
        ),
        migrations.AddField(
            model_name="judgmentoffence",
            name="judgment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="judgment_offence",
                to="peachjam.judgment",
                verbose_name="judgment",
            ),
        ),
        migrations.AddField(
            model_name="judgmentoffence",
            name="offence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="judgment_offence",
                to="peachjam.offence",
                verbose_name="judgments",
            ),
        ),
    ]
