# Generated by Django 4.2.27 on 2026-01-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0271_ensure_journalarticle_volume_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="coredocument",
            name="summary",
            field=models.TextField(blank=True, null=True, verbose_name="summary"),
        ),
        migrations.AddField(
            model_name="journalarticle",
            name="page_range",
            field=models.CharField(
                blank=True,
                help_text="Page range, e.g. pages 17-24",
                max_length=255,
                null=True,
                verbose_name="page range",
            ),
        ),
        migrations.AddField(
            model_name="journalarticle",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                to="peachjam.author",
            ),
        ),
    ]
