# Generated by Django 4.2.27 on 2026-01-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0272_add_summary_journalarticle_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="slug",
            field=models.SlugField(default="", max_length=512),
        ),
        migrations.AlterField(
            model_name="journal",
            name="title",
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name="volumeissue",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255, null=True),
        ),
    ]
