# Generated by Django 4.2.27 on 2026-02-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0272_add_flynote_taxonomy_root_to_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="helpscout_beacon_id",
            field=models.CharField(
                blank=True,
                help_text="ID of a helpscout contact us beacon.",
                max_length=100,
                null=True,
            ),
        ),
    ]
