# Generated by Django 4.2.27 on 2026-02-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0272_judgmentoffence"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="offence",
            unique_together=set(),
        ),
    ]
