# Generated by Django 4.2.27 on 2026-01-12 15:20

from django.db import migrations
from django.utils.text import slugify


def backfill_journal_volume_slugs(apps, schema_editor):
    Journal = apps.get_model("peachjam", "Journal")
    VolumeIssue = apps.get_model("peachjam", "VolumeIssue")

    for journal in Journal.objects.filter(slug__in=["", None]):
        journal.slug = slugify(journal.title)
        journal.save(update_fields=["slug"])

    for volume in VolumeIssue.objects.filter(slug__in=["", None]):
        volume.slug = slugify(volume.title)
        volume.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0272_add_summary_journalarticle_fields"),
    ]

    operations = [
        migrations.RunPython(
            backfill_journal_volume_slugs, reverse_code=migrations.RunPython.noop
        ),
    ]
