# Generated by Django 4.2.28 on 2026-02-27 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0273_peachjam_settings_helpscout_beacon_fix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peachjamsettings",
            name="flynote_taxonomy_root",
            field=models.ForeignKey(
                blank=True,
                help_text="Root taxonomy node for automatically managed flynote topics.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="peachjam.taxonomy",
                verbose_name="flynote taxonomy root",
            ),
        ),
    ]
