# Generated by Django 4.2.27 on 2026-02-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0273_peachjam_settings_helpscout_beacon_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcontent",
            name="content_html",
            field=models.TextField(blank=True, null=True, verbose_name="Content HTML"),
        ),
        migrations.AddField(
            model_name="documentcontent",
            name="source_html",
            field=models.TextField(blank=True, null=True, verbose_name="Source HTML"),
        ),
    ]
