# Generated by Django 4.2.27 on 2026-01-12 16:10

from django.db import migrations, models
from django.utils.text import slugify


def backfill_journalarticle_slugs(apps, schema_editor):
    JournalArticle = apps.get_model("peachjam", "JournalArticle")

    def unique_slug(base_slug, article_id):
        slug = base_slug
        counter = 2
        while JournalArticle.objects.filter(slug=slug).exclude(pk=article_id).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        return slug

    for article in JournalArticle.objects.all():
        raw_slug = (article.slug or "").strip().lower()
        if not raw_slug or raw_slug in {"none", "null"}:
            raw_slug = slugify(article.title)
        new_slug = unique_slug(raw_slug, article.pk)
        if article.slug != new_slug:
            article.slug = new_slug
            article.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0273_backfill_journal_volume_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalarticle",
            name="slug",
            field=models.SlugField(blank=True, max_length=512, null=True, unique=True),
        ),
        migrations.RunPython(
            backfill_journalarticle_slugs, reverse_code=migrations.RunPython.noop
        ),
    ]
