# Generated by Django on 2026-03-03

from django.db import migrations

from peachjam.analysis.flynotes import FlynoteParser
from peachjam_search.tasks import search_model_saved


def clean_flynote(value):
    if not value:
        return value
    return FlynoteParser.clean(value)


def forwards_func(apps, schema_editor):
    Judgment = apps.get_model("peachjam", "Judgment")
    judgments = Judgment.objects.filter(flynote__isnull=False, flynote__contains="<")

    for judgment in judgments.only("flynote").all():
        cleaned = clean_flynote(judgment.flynote)
        if cleaned != judgment.flynote:
            judgment.flynote = cleaned
            judgment.save(update_fields=["flynote"])
            # ensure it's re-indexed for search
            search_model_saved("peachjam.Judgment", judgment.pk)


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0273_peachjam_settings_helpscout_beacon_fix"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
