# Generated by Django 4.2.27 on 2026-01-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0273_alter_journal_slug_alter_journal_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="editorial_board",
            field=models.TextField(
                default="default",
                help_text="Markdown or plain text listing board members",
            ),
            preserve_default=False,
        ),
    ]
