# Generated by Django 4.2.28 on 2026-03-02 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0274_alter_peachjamsettings_flynote_taxonomy_root"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxonomyDocumentCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0, verbose_name="count")),
                (
                    "taxonomy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_count_cache",
                        to="peachjam.taxonomy",
                        verbose_name="taxonomy",
                    ),
                ),
            ],
            options={
                "verbose_name": "taxonomy document count",
                "verbose_name_plural": "taxonomy document counts",
            },
        ),
    ]
