# Generated by Django 4.2.27 on 2026-01-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0274_journal_editorial_board"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="editorial_board",
        ),
    ]
