# Generated by Django 4.2.27 on 2026-01-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0275_remove_journal_editorial_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="peer_reviewed",
            field=models.BooleanField(default=True),
        ),
    ]
