# Generated by Django 4.2.27 on 2026-03-02

from django.db import migrations


def backfill_document_content_html(apps, schema_editor):
    CoreDocument = apps.get_model("peachjam", "CoreDocument")
    DocumentContent = apps.get_model("peachjam", "DocumentContent")

    qs = CoreDocument.objects.exclude(content_html__isnull=True).only(
        "id", "content_html"
    )
    for doc in qs.iterator(chunk_size=1000):
        content_html = doc.content_html
        if not content_html:
            continue

        document_content, _ = DocumentContent.objects.get_or_create(document_id=doc.id)
        update_fields = []

        if not document_content.content_html:
            document_content.content_html = content_html
            update_fields.append("content_html")

        if not document_content.source_html:
            document_content.source_html = content_html
            update_fields.append("source_html")

        if update_fields:
            document_content.save(update_fields=update_fields)


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0275_add_documentcontent_source_html_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_document_content_html, migrations.RunPython.noop),
    ]
