# Generated by Django 4.2.28 on 2026-03-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0274_clean_flynotes"),
        ("peachjam", "0275_taxonomy_document_count"),
    ]

    operations = []
