# Generated by Django 4.2.27 on 2026-03-02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0275_backfill_documentcontent_html"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coredocument",
            name="content_html",
        ),
    ]
