# Generated by Django 4.2.27 on 2026-03-03

from django.db import migrations, models


def migrate_content_html_is_akn(apps, schema_editor):
    CoreDocument = apps.get_model("peachjam", "CoreDocument")
    DocumentContent = apps.get_model("peachjam", "DocumentContent")

    qs = CoreDocument.objects.filter(content_html_is_akn=True).only("id")
    for doc in qs.iterator(chunk_size=1000):
        document_content, _ = DocumentContent.objects.get_or_create(document_id=doc.id)
        if not document_content.content_html_is_akn:
            document_content.content_html_is_akn = True
            document_content.save(update_fields=["content_html_is_akn"])


def reverse_migrate_content_html_is_akn(apps, schema_editor):
    CoreDocument = apps.get_model("peachjam", "CoreDocument")
    DocumentContent = apps.get_model("peachjam", "DocumentContent")

    qs = DocumentContent.objects.filter(content_html_is_akn=True).only("document_id")
    for doc_content in qs.iterator(chunk_size=1000):
        CoreDocument.objects.filter(pk=doc_content.document_id).update(
            content_html_is_akn=True
        )


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0275_backfill_documentcontent_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcontent",
            name="content_html_is_akn",
            field=models.BooleanField(
                default=False, verbose_name="content HTML is AKN"
            ),
        ),
        migrations.RunPython(
            migrate_content_html_is_akn, reverse_migrate_content_html_is_akn
        ),
    ]
