# Generated by Django 4.2.27 on 2026-01-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0276_journal_peer_reviewed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="peer_reviewed",
        ),
    ]
