# Generated by Django 4.2.28 on 2026-03-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0276_merge_20260303_1236"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxonomy",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Hide this taxonomy and its descendants from public taxonomy listings.",
                verbose_name="hidden",
            ),
        ),
    ]
