# Generated by Django 4.2.27 on 2026-01-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0273_backfill_journal_volume_slugs"),
        ("peachjam", "0277_remove_journal_peer_reviewed"),
    ]

    operations = []
