# Generated by Django 4.2.28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0277_taxonomy_hidden_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flynote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=1024, unique=True, verbose_name="slug"),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "flynote",
                "verbose_name_plural": "flynotes",
            },
        ),
        migrations.CreateModel(
            name="JudgmentFlynote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flynotes",
                        to="peachjam.judgment",
                        verbose_name="judgment",
                    ),
                ),
                (
                    "flynote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judgments",
                        to="peachjam.flynote",
                        verbose_name="flynote",
                    ),
                ),
            ],
            options={
                "verbose_name": "judgment flynote",
                "verbose_name_plural": "judgment flynotes",
                "ordering": ["flynote"],
                "unique_together": {("document", "flynote")},
            },
        ),
        migrations.CreateModel(
            name="FlynoteDocumentCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0, verbose_name="count")),
                (
                    "flynote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_count_cache",
                        to="peachjam.flynote",
                        verbose_name="flynote",
                    ),
                ),
            ],
            options={
                "verbose_name": "flynote document count",
                "verbose_name_plural": "flynote document counts",
            },
        ),
    ]
