# Generated by Django 4.2.27 on 2026-01-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0274_journalarticle_slug"),
        ("peachjam", "0278_merge_20260116_0809"),
    ]

    operations = []
