# Generated by Django 4.2.28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0278_add_flynote_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="peachjamsettings",
            name="flynote_taxonomy_root",
        ),
    ]
