# Generated by Django 4.2.28 on 2026-03-05

from django.db import migrations

BATCH_SIZE = 1000


def backfill_document_content(apps, schema_editor):
    conn = schema_editor.connection

    # Step 1: Insert missing rows in batches.
    # No OFFSET needed — the LEFT JOIN / WHERE dc.document_id IS NULL condition
    # naturally selects only rows not yet inserted on each iteration.
    while True:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO peachjam_documentcontent (
                    document_id,
                    content_html,
                    source_html,
                    content_html_is_akn,
                    toc_json
                )
                SELECT
                    d.id,
                    d.content_html,
                    d.content_html,
                    COALESCE(d.content_html_is_akn, FALSE),
                    d.toc_json
                FROM peachjam_coredocument d
                LEFT JOIN peachjam_documentcontent dc ON dc.document_id = d.id
                WHERE dc.document_id IS NULL
                  AND (
                    d.content_html IS NOT NULL
                    OR d.toc_json IS NOT NULL
                    OR COALESCE(d.content_html_is_akn, FALSE) = TRUE
                  )
                ORDER BY d.id
                LIMIT %s
                """,
                [BATCH_SIZE],
            )
            if cursor.rowcount < BATCH_SIZE:
                break

    # Step 2: Backfill missing/blank content_html and source_html in batches.
    while True:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                UPDATE peachjam_documentcontent dc
                SET
                    content_html = CASE
                        WHEN (dc.content_html IS NULL OR dc.content_html = '')
                             AND d.content_html IS NOT NULL
                        THEN d.content_html
                        ELSE dc.content_html
                    END,
                    source_html = CASE
                        WHEN (dc.source_html IS NULL OR dc.source_html = '')
                             AND d.content_html IS NOT NULL
                        THEN d.content_html
                        ELSE dc.source_html
                    END
                FROM peachjam_coredocument d
                WHERE dc.document_id = d.id
                  AND dc.document_id IN (
                    SELECT dc2.document_id
                    FROM peachjam_documentcontent dc2
                    JOIN peachjam_coredocument d2 ON dc2.document_id = d2.id
                    WHERE
                        ((dc2.content_html IS NULL OR dc2.content_html = '') AND d2.content_html IS NOT NULL)
                        OR ((dc2.source_html IS NULL OR dc2.source_html = '') AND d2.content_html IS NOT NULL)
                    ORDER BY dc2.document_id
                    LIMIT %s
                  )
                """,
                [BATCH_SIZE],
            )
            if cursor.rowcount < BATCH_SIZE:
                break

    # Step 3: Backfill toc_json in batches.
    while True:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                UPDATE peachjam_documentcontent dc
                SET toc_json = d.toc_json
                FROM peachjam_coredocument d
                WHERE dc.document_id = d.id
                  AND dc.document_id IN (
                    SELECT dc2.document_id
                    FROM peachjam_documentcontent dc2
                    JOIN peachjam_coredocument d2 ON dc2.document_id = d2.id
                    WHERE dc2.toc_json IS NULL
                      AND d2.toc_json IS NOT NULL
                    ORDER BY dc2.document_id
                    LIMIT %s
                  )
                """,
                [BATCH_SIZE],
            )
            if cursor.rowcount < BATCH_SIZE:
                break

    # Step 4: Backfill content_html_is_akn flag in batches.
    while True:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                UPDATE peachjam_documentcontent dc
                SET content_html_is_akn = TRUE
                FROM peachjam_coredocument d
                WHERE dc.document_id = d.id
                  AND dc.document_id IN (
                    SELECT dc2.document_id
                    FROM peachjam_documentcontent dc2
                    JOIN peachjam_coredocument d2 ON dc2.document_id = d2.id
                    WHERE dc2.content_html_is_akn = FALSE
                      AND COALESCE(d2.content_html_is_akn, FALSE) = TRUE
                    ORDER BY dc2.document_id
                    LIMIT %s
                  )
                """,
                [BATCH_SIZE],
            )
            if cursor.rowcount < BATCH_SIZE:
                break


class Migration(migrations.Migration):
    # atomic=False so each batch is committed independently, avoiding a single
    # long-running transaction that would accumulate large WAL entries.
    atomic = False

    dependencies = [
        ("peachjam", "0278_add_coredocument_content_html_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_document_content, migrations.RunPython.noop),
    ]
