# Generated by Django 4.2.28 on 2026-03-11

from django.db import migrations


def normalise_multiline_flynotes(apps, schema_editor):
    from peachjam.analysis.flynotes import FlynoteParser

    Judgment = apps.get_model("peachjam", "Judgment")
    parser = FlynoteParser()

    judgments = Judgment.objects.exclude(flynote__isnull=True).exclude(flynote="")

    for judgment in judgments.iterator():
        normalised = parser.normalise_multiline_text(judgment.flynote)
        if normalised != judgment.flynote:
            judgment.flynote = normalised
            judgment.save(update_fields=["flynote"])


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0279_remove_flynote_taxonomy_root"),
    ]

    operations = [
        migrations.RunPython(normalise_multiline_flynotes, migrations.RunPython.noop),
    ]
