# Generated by Django 4.2.28 on 2026-03-11

from django.db import migrations
from django.db.models import Q


def normalise_multiline_flynotes(apps, schema_editor):
    from peachjam.analysis.flynotes import FlynoteParser

    Judgment = apps.get_model("peachjam", "Judgment")
    parser = FlynoteParser()

    candidate_filter = Q(flynote__regex=r"\.[[:space:]]+[A-Z]") | Q(
        flynote__contains="\n"
    )

    judgments = (
        Judgment.objects.exclude(flynote__isnull=True)
        .exclude(flynote="")
        .filter(candidate_filter)
        .only("flynote")
        .order_by("pk")
    )

    last_pk = 0
    batch_size = 500
    while True:
        batch = list(judgments.filter(pk__gt=last_pk)[:batch_size])
        if not batch:
            break

        for judgment in batch:
            normalised = parser.normalise_multiline_text(judgment.flynote)
            if normalised != judgment.flynote:
                judgment.flynote = normalised
                judgment.save(update_fields=["flynote"])

        last_pk = batch[-1].pk


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0280_userprofile_deletion_fields"),
    ]

    operations = [
        migrations.RunPython(normalise_multiline_flynotes, migrations.RunPython.noop),
    ]
