# Generated by Django 4.2.28 on 2026-03-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0281_normalise_multiline_flynotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcontent",
            name="content_html",
            field=models.TextField(blank=True, null=True, verbose_name="Content HTML"),
        ),
        migrations.AddField(
            model_name="documentcontent",
            name="content_html_is_akn",
            field=models.BooleanField(
                default=False, verbose_name="content HTML is AKN"
            ),
        ),
        migrations.AddField(
            model_name="documentcontent",
            name="source_html",
            field=models.TextField(blank=True, null=True, verbose_name="Source HTML"),
        ),
        migrations.AddField(
            model_name="documentcontent",
            name="toc_json",
            field=models.JSONField(blank=True, null=True, verbose_name="TOC JSON"),
        ),
    ]
