# Generated by Django 4.2.29 on 2026-03-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0281_judgmentoffence_judgment_case_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="allow_criminal_data_extraction",
            field=models.BooleanField(
                default=False,
                help_text="Allow AI-based criminal data extraction for judgments.",
                verbose_name="allow criminal data extraction",
            ),
        ),
    ]
