# Generated by Django 4.2.28 on 2026-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0281_normalise_multiline_flynotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flynotedocumentcount",
            name="count",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="count"
            ),
        ),
    ]
