# Generated by Django 4.2.29 on 2026-03-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0283_judgmentoffence_judgment_case_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfollowing",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="peachjam.journal",
                verbose_name="journal",
            ),
        ),
        migrations.AddField(
            model_name="userfollowing",
            name="law_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="peachjam.lawreport",
                verbose_name="law report",
            ),
        ),
        migrations.AddConstraint(
            model_name="userfollowing",
            constraint=models.UniqueConstraint(
                condition=models.Q(("journal__isnull", False)),
                fields=("user", "journal"),
                name="unique_user_journal",
            ),
        ),
        migrations.AddConstraint(
            model_name="userfollowing",
            constraint=models.UniqueConstraint(
                condition=models.Q(("law_report__isnull", False)),
                fields=("user", "law_report"),
                name="unique_user_law_report",
            ),
        ),
    ]
