# Generated by Django 4.2.28 on 2026-03-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0285_backfill_documentcontent_from_coredocument"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coredocument",
            name="content_html",
        ),
        migrations.RemoveField(
            model_name="coredocument",
            name="content_html_is_akn",
        ),
        migrations.RemoveField(
            model_name="coredocument",
            name="toc_json",
        ),
    ]
