# Generated by Django 4.2.29 on 2026-04-05 00:00

import django.contrib.postgres.fields
from django.db import migrations, models


def seed_offence_categories(apps, schema_editor):
    OffenceCategory = apps.get_model("peachjam", "OffenceCategory")

    categories = [
        (
            1,
            "Violence",
            "Offences involving physical force, injury, or threats of violence.",
        ),
        (
            2,
            "Sexual and Gender-Based Violence",
            "Offences involving sexual harm, coercion, or gender-based abuse.",
        ),
        (
            3,
            "Property",
            "Offences involving theft, damage, trespass, or unlawful interference with property.",
        ),
        (
            4,
            "Financial and Economic",
            "Offences involving fraud, false pretences, corruption, or unlawful financial gain.",
        ),
        (
            5,
            "Public Order",
            "Offences involving disorder, disturbance, or disruption of public peace.",
        ),
        (
            6,
            "State and Political",
            "Offences against the state, public authority, or political order.",
        ),
        (
            7,
            "Justice System",
            "Offences affecting courts, investigations, evidence, or the administration of justice.",
        ),
        (
            8,
            "Public Safety",
            "Offences creating danger to the public, transport, health, or general safety.",
        ),
        (
            9,
            "Morality",
            "Offences historically framed around morality, decency, or prohibited conduct.",
        ),
    ]

    for order, name, description in categories:
        OffenceCategory.objects.update_or_create(
            name=name,
            defaults={
                "slug": name.lower().replace(" and ", "-and-").replace(" ", "-"),
                "description": description,
                "order": order,
                "is_active": True,
            },
        )


def unseed_offence_categories(apps, schema_editor):
    OffenceCategory = apps.get_model("peachjam", "OffenceCategory")
    OffenceCategory.objects.filter(
        name__in=[
            "Violence",
            "Sexual and Gender-Based Violence",
            "Property",
            "Financial and Economic",
            "Public Order",
            "State and Political",
            "Justice System",
            "Public Safety",
            "Morality",
        ]
    ).delete()


def deduplicate_offence_provision_eids(apps, schema_editor):
    Offence = apps.get_model("peachjam", "Offence")

    seen = {}

    for offence in Offence.objects.order_by("pk"):
        key = (offence.work_id, offence.provision_eid)

        if key not in seen:
            seen[key] = offence.pk
            continue

        offence.provision_eid = f"{offence.provision_eid}__{offence.code}"
        offence.save(update_fields=["provision_eid"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0287_userfollowing_journal_userfollowing_law_report_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OffenceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="slug"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "order",
                    models.IntegerField(blank=True, null=True, verbose_name="order"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "offence category",
                "verbose_name_plural": "offence categories",
                "ordering": ("order", "name"),
            },
        ),
        migrations.AddField(
            model_name="judgmentoffence",
            name="case_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Case-specific semantic tags extracted from the judgment for this offence.",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="offence",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="offences",
                to="peachjam.offencecategory",
                verbose_name="categories",
            ),
        ),
        migrations.AddField(
            model_name="offence",
            name="offence_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Flexible semantic tags that are inherent to the offence definition.",
                size=None,
            ),
        ),
        migrations.RunPython(deduplicate_offence_provision_eids, noop_reverse),
        migrations.AddConstraint(
            model_name="judgmentoffence",
            constraint=models.UniqueConstraint(
                fields=("judgment", "offence"),
                name="unique_judgment_offence_judgment_offence",
            ),
        ),
        migrations.AddConstraint(
            model_name="offence",
            constraint=models.UniqueConstraint(
                fields=("work", "provision_eid"),
                name="unique_offence_work_provision_eid",
            ),
        ),
        migrations.RunPython(seed_offence_categories, unseed_offence_categories),
    ]
