# Generated by Django 4.2.29 on 2026-04-10 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0291_judgment_court_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="OffenceGrouping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=50, verbose_name="kind")),
                ("label", models.CharField(max_length=255, verbose_name="label")),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="number",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="title",
                    ),
                ),
                (
                    "provision_eid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="AKN element id / EID for the grouping within the work.",
                        max_length=255,
                        verbose_name="provision EID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="order")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="peachjam.offencegrouping",
                        verbose_name="parent",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        help_text="The Work that defines this offence grouping.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offence_groupings",
                        to="peachjam.work",
                        verbose_name="work",
                    ),
                ),
            ],
            options={
                "verbose_name": "offence grouping",
                "verbose_name_plural": "offence groupings",
                "ordering": ("work_id", "parent_id", "order", "id"),
            },
        ),
        migrations.AddField(
            model_name="offence",
            name="grouping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offences",
                to="peachjam.offencegrouping",
                verbose_name="grouping",
            ),
        ),
        migrations.AddIndex(
            model_name="offencegrouping",
            index=models.Index(fields=["kind"], name="offence_grouping_kind_idx"),
        ),
        migrations.AddIndex(
            model_name="offencegrouping",
            index=models.Index(
                fields=["work", "kind"], name="offence_grouping_work_kind_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="offencegrouping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provision_eid", ""), _negated=True),
                fields=("work", "provision_eid"),
                name="unique_offencegrouping_work_provision_eid",
            ),
        ),
    ]
