# Generated by Django 4.2.30 on 2026-04-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0292_offencegrouping_and_offence_grouping_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offencecategory",
            options={
                "ordering": ("name",),
                "verbose_name": "offence category",
                "verbose_name_plural": "offence categories",
            },
        ),
        migrations.AlterField(
            model_name="sentence",
            name="fine_amount",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="Fine amount",
                null=True,
                verbose_name="fine amount",
            ),
        ),
        migrations.AlterField(
            model_name="volumeissue",
            name="title",
            field=models.CharField(
                help_text="The volume and issue number, e.g. 'Vol. 3 No.1 1993' or 'Vol. 3 No.1 - 1993'.",
                max_length=2048,
            ),
        ),
    ]
