# Generated by Django 4.2.28 on 2026-04-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0292_offencegrouping_and_offence_grouping_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="flynote_raw",
            field=models.TextField(blank=True, null=True, verbose_name="flynote (raw)"),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE peachjam_judgment
                SET flynote_raw = flynote
                WHERE flynote IS NOT NULL
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
