# Generated by Django 4.2.28 on 2026-04-24 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0294_flynote_deprecated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgmentflynote",
            name="flynote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="judgments",
                to="peachjam.flynote",
                verbose_name="flynote",
            ),
        ),
    ]
