# Generated by Django 4.2.28 on 2026-04-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0295_judgment_flynote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flynote",
            name="slug",
            field=models.CharField(blank=True, null=True, verbose_name="slug"),
        ),
    ]
