# Generated by Django 4.2.28 on 2026-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0296_flynote_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="flynote",
            name="document_count_refresh_pending",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="document count refresh pending",
            ),
        ),
    ]
