# Generated by Django 4.2.29 on 2026-05-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0298_alter_offencecategory_options_remove_flynote_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgmentoffence",
            name="judgment",
        ),
        migrations.RemoveField(
            model_name="judgmentoffence",
            name="offence",
        ),
        migrations.RemoveField(
            model_name="judgmentoffence",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="offence",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="offence",
            name="grouping",
        ),
        migrations.RemoveField(
            model_name="offence",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="offence",
            name="work",
        ),
        migrations.RemoveField(
            model_name="offencegrouping",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="offencegrouping",
            name="work",
        ),
        migrations.RemoveField(
            model_name="sentence",
            name="judgment",
        ),
        migrations.RemoveField(
            model_name="sentence",
            name="offence",
        ),
        migrations.RemoveField(
            model_name="judgment",
            name="case_type",
        ),
        migrations.RemoveField(
            model_name="judgment",
            name="filing_year",
        ),
        migrations.DeleteModel(
            name="CaseTag",
        ),
        migrations.DeleteModel(
            name="JudgmentOffence",
        ),
        migrations.DeleteModel(
            name="Offence",
        ),
        migrations.DeleteModel(
            name="OffenceCategory",
        ),
        migrations.DeleteModel(
            name="OffenceGrouping",
        ),
        migrations.DeleteModel(
            name="OffenceTag",
        ),
        migrations.DeleteModel(
            name="Sentence",
        ),
    ]
