# Generated by Django 4.2.29 on 2026-05-13 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0298_move_arbitration_to_peachjam_pro"),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgePerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=1024, verbose_name="full name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "judge",
                "verbose_name_plural": "judges",
                "ordering": ("full_name", "pk"),
            },
        ),
        migrations.CreateModel(
            name="JudgeAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="name")),
                (
                    "normalized_name",
                    models.CharField(
                        db_index=True, max_length=1024, verbose_name="normalized name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=True, verbose_name="verified"),
                ),
                (
                    "judge_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="peachjam.judgeperson",
                        verbose_name="judge person",
                    ),
                ),
            ],
            options={
                "verbose_name": "judge alias",
                "verbose_name_plural": "judge aliases",
                "ordering": ("name", "pk"),
            },
        ),
        migrations.AddField(
            model_name="bench",
            name="extracted_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="extracted name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bench",
            name="is_manual_override",
            field=models.BooleanField(default=False, verbose_name="manual override"),
        ),
        migrations.AddField(
            model_name="bench",
            name="judge_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bench_entries",
                to="peachjam.judgeperson",
                verbose_name="judge",
            ),
        ),
        migrations.AddField(
            model_name="bench",
            name="matched_alias",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bench_entries",
                to="peachjam.judgealias",
                verbose_name="matched alias",
            ),
        ),
        migrations.AddField(
            model_name="bench",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=32,
                verbose_name="title",
            ),
            preserve_default=False,
        ),
    ]
