# Generated by Django 4.2.29 on 2026-05-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0298_move_arbitration_to_peachjam_pro"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flynote",
            options={
                "permissions": [("view_linked_judgments", "Can view linked judgments")],
                "verbose_name": "flynote",
                "verbose_name_plural": "flynotes",
            },
        ),
    ]
