# Generated by Django 4.2.29 on 2026-05-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0299_flynote_view_linked_judgments_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfollowing",
            name="flynote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="peachjam.flynote",
                verbose_name="flynote",
            ),
        ),
        migrations.AddConstraint(
            model_name="userfollowing",
            constraint=models.UniqueConstraint(
                condition=models.Q(("flynote__isnull", False)),
                fields=("user", "flynote"),
                name="unique_user_flynote",
            ),
        ),
    ]
