# Generated by Django 4.2.29 on 2026-05-26 03:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0299_judgeperson_alter_bench_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="judge",
            options={
                "ordering": ("name",),
                "verbose_name": "legacy judge",
                "verbose_name_plural": "legacy judges",
            },
        ),
    ]
