# Generated by Django 4.2.29 on 2026-05-27 00:00

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0300_userfollowing_flynote"),
    ]

    operations = [
        migrations.AddField(
            model_name="flynote",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2026, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flynote",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="created at",
            ),
        ),
    ]
