# Generated by Django 4.2.28 on 2026-05-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0301_flynote_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="helpscout_beacon_secret_key",
            field=models.CharField(
                blank=True,
                help_text="Secret key for helpscout signature.",
                max_length=100,
                null=True,
            ),
        ),
    ]
