# Generated by Django 4.2.29 on 2026-06-02 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0302_peachjamsettings_helpscout_beacon_secret_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provisionenrichment",
            name="enrichment_type",
            field=models.CharField(
                choices=[
                    ("provision_enrichment", "Provision enrichment"),
                    ("unconstitutional_provision", "Unconstitutional provision"),
                    ("uncommenced_provision", "Uncommenced provision"),
                    ("provision_citation", "Provision citation"),
                    ("provision_topic", "Provision topic"),
                ],
                default="provision_enrichment",
                max_length=256,
                verbose_name="enrichment type",
            ),
        ),
        migrations.CreateModel(
            name="ProvisionTopicEnrichment",
            fields=[
                (
                    "provisionenrichment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="peachjam.provisionenrichment",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provision_enrichments",
                        to="peachjam.taxonomy",
                        verbose_name="topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "provision topic enrichment",
                "verbose_name_plural": "provision topic enrichments",
            },
            bases=("peachjam.provisionenrichment",),
        ),
    ]
