# Generated by Codex on 2026-06-11

from django.db import migrations, models

from peachjam.models.judgment import default_summary_language


def backfill_summary_language(apps, schema_editor):
    Judgment = apps.get_model("peachjam", "Judgment")
    Judgment.objects.filter(summary_language__isnull=True).update(
        summary_language=default_summary_language()
    )


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0303_provision_topic_enrichment"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="summary_language",
            field=models.CharField(
                blank=True,
                default=default_summary_language,
                help_text="The language used for the AI-generated summary",
                max_length=128,
                null=True,
                verbose_name="summary language",
            ),
        ),
        migrations.RunPython(
            backfill_summary_language,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="judgment",
            name="summary_language",
            field=models.CharField(
                blank=True,
                default=default_summary_language,
                help_text="The language used for the AI-generated summary",
                max_length=128,
                verbose_name="summary language",
            ),
        ),
    ]
