# Generated by Django 4.2.29 on 2026-05-13 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0305_judgment_summary_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="judge",
            options={
                "ordering": ("name",),
                "verbose_name": "legacy judge",
                "verbose_name_plural": "legacy judges",
            },
        ),
        migrations.CreateModel(
            name="JudgePerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=1024,
                        unique=True,
                        verbose_name="full name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "judge",
                "verbose_name_plural": "judges",
                "ordering": ("full_name", "pk"),
            },
        ),
        migrations.CreateModel(
            name="JudgeAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="name")),
                (
                    "normalized_name",
                    models.CharField(
                        db_index=True, max_length=1024, verbose_name="normalized name"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Judicial title parsed from the alias name, for "
                            "example 'JA' or 'DCJ'."
                        ),
                        max_length=32,
                        verbose_name="title",
                    ),
                ),
                (
                    "judge_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="peachjam.judgeperson",
                        verbose_name="judge person",
                    ),
                ),
            ],
            options={
                "verbose_name": "judge alias",
                "verbose_name_plural": "judge aliases",
                "ordering": ("name", "pk"),
            },
        ),
        migrations.AddField(
            model_name="bench",
            name="judge_person",
            field=models.ForeignKey(
                blank=True,
                help_text="Canonical judge identity for this bench row.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bench_entries",
                to="peachjam.judgeperson",
                verbose_name="judge",
            ),
        ),
        migrations.AddField(
            model_name="bench",
            name="extracted_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Judge name exactly as it appeared in the source, "
                    "for example 'ABBAN, J.A.'."
                ),
                max_length=1024,
                verbose_name="extracted name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bench",
            name="matched_alias",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Alias that matched the legacy judge name to the "
                    "canonical judge."
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bench_entries",
                to="peachjam.judgealias",
                verbose_name="matched alias",
            ),
        ),
    ]
