# Generated by Django 4.2.29 on 2026-07-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries_plus", "0005_auto_20160224_1804"),
        ("peachjam", "0309_add_account_feature_flags"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="locality",
            unique_together={("name", "jurisdiction")},
        ),
        migrations.AddField(
            model_name="locality",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="locality",
            name="name_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="locality",
            name="name_pt",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="locality",
            name="name_sw",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AlterUniqueTogether(
            name="locality",
            unique_together={
                ("name", "jurisdiction"),
                ("name_en", "jurisdiction"),
                ("name_fr", "jurisdiction"),
                ("name_pt", "jurisdiction"),
                ("name_sw", "jurisdiction"),
            },
        ),
    ]
