# Generated by Django 4.2.29 on 2026-07-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0309_remove_peachjamsettings_allow_signups"),
    ]

    operations = [
        migrations.AddField(
            model_name="peachjamsettings",
            name="allow_annotations",
            field=models.BooleanField(
                default=True,
                help_text="Allow private document annotations.",
                verbose_name="allow annotations",
            ),
        ),
        migrations.AddField(
            model_name="peachjamsettings",
            name="allow_follows",
            field=models.BooleanField(
                default=True,
                help_text="Allow courts, authors, topics, and other entities to be followed.",
                verbose_name="allow follows",
            ),
        ),
    ]
