# Generated by Django 4.2.29 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0310_locality_name_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="citationlink",
            name="origin",
            field=models.CharField(
                choices=[
                    ("automatic", "Automatically extracted"),
                    ("manual", "Manually created"),
                ],
                default="automatic",
                max_length=16,
                verbose_name="origin",
            ),
        ),
    ]
