# Generated by Django 4.2.29 on 2026-08-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0311_citationlink_origin"),
        ("peachjam", "0311_sourcefile_start_page"),
    ]

    operations = []
