# Generated by Django 4.2.29 on 2026-08-12

from django.db import migrations


def mark_external_citation_links_manual(apps, schema_editor):
    """Preserve pre-existing citation links that extraction could not have generated."""
    CitationLink = apps.get_model("peachjam", "CitationLink")
    CitationLink.objects.exclude(url__startswith="/akn").update(origin="manual")


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0312_merge_20260811_1345"),
    ]

    operations = [
        migrations.RunPython(
            mark_external_citation_links_manual, migrations.RunPython.noop
        ),
    ]
