# Generated by Django 4.2.29 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


def seed_onboarding_options(apps, schema_editor):
    options = {
        "OnboardingIntent": [
            "Research case law",
            "Research legislation",
            "Track legal updates",
            "Use AI-assisted legal research",
            "Just exploring",
        ],
        "PracticeType": [
            "Student",
            "Sole practitioner",
            "Law firm (2–5 lawyers)",
            "Law firm (6+ lawyers)",
            "Government or public sector",
            "Corporate legal department",
            "Other",
        ],
    }

    for model_name, labels in options.items():
        model = apps.get_model("peachjam", model_name)
        model.objects.bulk_create(
            [model(label=label, order=order) for order, label in enumerate(labels)]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0317_backfill_anonymised_source_file_pdfs"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="label")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="order"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "onboarding intent",
                "verbose_name_plural": "onboarding intents",
                "ordering": ["order", "label"],
            },
        ),
        migrations.CreateModel(
            name="PracticeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="label")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="order"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "practice type",
                "verbose_name_plural": "practice types",
                "ordering": ["order", "label"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_completed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="onboarding completed at",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_intents",
            field=models.ManyToManyField(
                blank=True,
                to="peachjam.onboardingintent",
                verbose_name="onboarding intents",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_skipped_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="onboarding skipped at",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="practice_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="peachjam.practicetype",
                verbose_name="practice type",
            ),
        ),
        migrations.RunPython(seed_onboarding_options, migrations.RunPython.noop),
    ]
