# Generated by Django 4.2.29 on 2026-08-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0320_peachjamsettings_email_alert_default_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peachjamsettings",
            name="allow_signups",
            field=models.BooleanField(
                default=True,
                help_text="Deprecated compatibility field. Use the global accounts switch instead.",
                verbose_name="allow signups",
            ),
        ),
    ]
