# Generated by Django 4.2.30 on 2026-09-07 15:09

import django.db.models.deletion
from django.db import migrations, models


def seed_popular_legislation(apps, schema_editor):
    PeachJamSettings = apps.get_model("peachjam", "PeachJamSettings")
    PopularLegislation = apps.get_model("peachjam", "PopularLegislation")
    Work = apps.get_model("peachjam", "Work")

    works = Work.objects.filter(
        documents__doc_type="legislation",
        documents__locality__isnull=True,
        documents__published=True,
    )
    site_settings = PeachJamSettings.objects.first()
    if site_settings:
        jurisdiction_id = site_settings.default_document_jurisdiction_id
        if jurisdiction_id is None:
            jurisdiction_ids = list(
                site_settings.document_jurisdictions.values_list("pk", flat=True)[:2]
            )
            if len(jurisdiction_ids) == 1:
                jurisdiction_id = jurisdiction_ids[0]
        if jurisdiction_id:
            works = works.filter(documents__jurisdiction_id=jurisdiction_id)

    popular_ordering = ("-authority_score", "-pagerank", "title")
    pinned_work_id = (
        works.filter(title__icontains="constitution")
        .exclude(title__icontains="amendment")
        .order_by(*popular_ordering)
        .values_list("pk", flat=True)
        .first()
    )
    works = works.annotate(
        popular_priority=models.Case(
            models.When(pk=pinned_work_id, then=models.Value(0)),
            default=models.Value(1),
            output_field=models.IntegerField(),
        )
    ).order_by("popular_priority", *popular_ordering)
    work_ids = list(works.values_list("pk", flat=True).distinct()[:10])
    PopularLegislation.objects.bulk_create(
        [
            PopularLegislation(work_id=work_id, position=position)
            for position, work_id in enumerate(work_ids, start=1)
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0321_alter_peachjamsettings_allow_signups"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularLegislation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="position"),
                ),
                (
                    "work",
                    models.OneToOneField(
                        limit_choices_to={
                            "documents__doc_type": "legislation",
                            "documents__locality__isnull": True,
                            "documents__published": True,
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popular_legislation",
                        to="peachjam.work",
                        verbose_name="legislation",
                    ),
                ),
            ],
            options={
                "verbose_name": "popular legislation",
                "verbose_name_plural": "popular legislation",
                "ordering": ("position", "pk"),
            },
        ),
        migrations.RunPython(seed_popular_legislation, migrations.RunPython.noop),
    ]
