# Generated by Django 4.2.29 on 2026-09-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0323_backfill_locality_name_en"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadingAuthority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("editorial_note", models.TextField(verbose_name="editorial note")),
                ("as_at_date", models.DateField(verbose_name="reviewed as at")),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "judgment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leading_authorities",
                        to="peachjam.judgment",
                        verbose_name="judgment",
                    ),
                ),
            ],
            options={
                "verbose_name": "leading authority",
                "verbose_name_plural": "leading authorities",
                "ordering": ("subject__name", "pk"),
            },
        ),
        migrations.CreateModel(
            name="LegalSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("area_of_law", "Area of law"),
                            ("concept", "Concept"),
                            ("doctrine", "Doctrine"),
                            ("procedure", "Procedure"),
                            ("principle", "Principle"),
                            ("remedy", "Remedy"),
                            ("defence", "Defence"),
                        ],
                        max_length=32,
                        verbose_name="subject type",
                    ),
                ),
            ],
            options={
                "verbose_name": "legal subject",
                "verbose_name_plural": "legal subjects",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="LeadingAuthoritySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("citation", models.TextField(verbose_name="citation")),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "leading_authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="peachjam.leadingauthority",
                        verbose_name="leading authority",
                    ),
                ),
            ],
            options={
                "verbose_name": "leading authority source",
                "verbose_name_plural": "leading authority sources",
                "ordering": ("pk",),
            },
        ),
        migrations.AddField(
            model_name="leadingauthority",
            name="subject",
            field=models.ForeignKey(
                limit_choices_to={"subject_type__in": ("doctrine", "principle")},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leading_authorities",
                to="peachjam.legalsubject",
                verbose_name="legal subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="leadingauthority",
            constraint=models.UniqueConstraint(
                fields=("judgment", "subject"),
                name="unique_leading_authority_judgment_subject",
            ),
        ),
    ]
