# Generated by Django 4.2.30 on 2026-09-23 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0322_leadingauthority_legalsubject_and_more"),
        ("peachjam", "0323_backfill_locality_name_en"),
    ]

    operations = []
