repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.5
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-case-conflict
  - id: check-yaml
  - id: end-of-file-fixer
    exclude_types: [pofile, javascript, map]
  - id: trailing-whitespace
  - id: mixed-line-ending
    language_version: python3
- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.19.14
  hooks:
  - id: djlint-django
    args: [--reformat, --lint]
