files:
  - source: /peachjam/locale/en/LC_MESSAGES/django.po
    translation: /peachjam/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%
  - source: /peachjam_ml/locale/en/LC_MESSAGES/django.po
    translation: /peachjam_ml/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%
  - source: /peachjam_search/locale/en/LC_MESSAGES/django.po
    translation: /peachjam_search/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%
  - source: /peachjam_subs/locale/en/LC_MESSAGES/django.po
    translation: /peachjam_subs/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%
  - source: /africanlii/locale/en/LC_MESSAGES/django.po
    translation: /africanlii/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%
  - source: /liiweb/locale/en/LC_MESSAGES/django.po
    translation: /liiweb/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%
  - source: /lawlibrary/locale/en/LC_MESSAGES/django.po
    translation: /lawlibrary/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%
  - source: /senlii/locale/en/LC_MESSAGES/django.po
    translation: /senlii/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%
  - source: /tanzlii/locale/en/LC_MESSAGES/django.po
    translation: /tanzlii/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%
  - source: /zanzibarlii/locale/en/LC_MESSAGES/django.po
    translation: /zanzibarlii/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%
  - source: /peachjam/js/locale/en/translation.json
    translation: /peachjam/js/locale/%two_letters_code%/%original_file_name%
