# Generated by Django 3.2.13 on 2022-06-15 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("peachjam", "0007_documenttopic_taxonomy"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("url", models.URLField(max_length=1024)),
                ("target_id", models.CharField(max_length=1024)),
                ("target_selectors", models.JSONField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citation_links",
                        to="peachjam.coredocument",
                    ),
                ),
            ],
        ),
    ]
