# Generated by Django 3.2 on 2022-03-08 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=20)),
                ('header_title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peach_jam.country')),
            ],
            options={
                'verbose_name_plural': 'courts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MatterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('date', models.DateField()),
                ('citation', models.CharField(blank=True, max_length=1024, null=True)),
                ('case_number_numeric', models.CharField(blank=True, max_length=1024, null=True)),
                ('case_number_year', models.CharField(blank=True, max_length=1024, null=True)),
                ('case_number_string', models.CharField(blank=True, max_length=1024, null=True)),
                ('document_content', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('source_file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peach_jam.court')),
                ('matter_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='peach_jam.mattertype')),
            ],
        ),
    ]
