# Generated by Django 3.2.12 on 2022-03-10 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries_plus.country')),
            ],
            options={
                'verbose_name_plural': 'courts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MatterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('date', models.DateField()),
                ('citation', models.CharField(blank=True, max_length=1024, null=True)),
                ('case_number_numeric', models.CharField(blank=True, max_length=1024, null=True)),
                ('case_number_year', models.IntegerField(blank=True, null=True)),
                ('case_number_string', models.CharField(blank=True, max_length=1024, null=True)),
                ('document_content', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peach_jam.court')),
                ('matter_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='peach_jam.mattertype')),
            ],
        ),
    ]
