LIIS = [
    {
        "name": "EswatiniLII",
        "country": "Eswatini",
        "url": "https://eswatinilii.org",
        "logo": "images/liis/eswatinilii.png",
        "domain": "eswatinilii.org",
    },
    {
        "name": "GhaLII",
        "country": "Ghana",
        "url": "https://ghalii.org",
        "logo": "images/liis/ghalii.png",
        "domain": "ghalii.org",
    },
    {
        "name": "Kenya Law",
        "country": "Kenya",
        "url": "http://kenyalaw.org",
        "logo": "images/liis/kenyalaw.png",
        "domain": "kenyalaw.org",
    },
    {
        "name": "LesothoLII",
        "country": "Lesotho",
        "url": "https://lesotholii.org",
        "logo": "images/liis/lesotholii.png",
        "domain": "lesotholii.org",
    },
    {
        "name": "MalawiLII",
        "country": "Malawi",
        "url": "https://malawilii.org",
        "logo": "images/liis/malawilii.png",
        "domain": "malawilii.org",
    },
    {
        "name": "NamibLII",
        "country": "Namibia",
        "url": "https://namiblii.org",
        "logo": "images/liis/namiblii.png",
        "domain": "namiblii.org",
    },
    {
        "name": "SierraLII",
        "country": "Sierra Leone",
        "url": "https://sierralii.org",
        "logo": "images/liis/sierralii.png",
        "domain": "sierralii.org",
    },
    {
        "name": "SeyLII",
        "country": "Seychelles",
        "url": "https://seylii.org",
        "logo": "images/liis/seylii.png",
        "domain": "seylii.org",
    },
    {
        "name": "LawLibrary",
        "country": "South Africa",
        "url": "https://lawlibrary.org.za",
        "logo": "images/liis/lawlibrary.png",
        "domain": "lawlibrary.org.za",
    },
    {
        "name": "TanzLII",
        "country": "Tanzania",
        "url": "https://tanzlii.org",
        "logo": "images/liis/tanzlii.png",
        "domain": "tanzlii.org",
    },
    {
        "name": "ULII",
        "country": "Uganda",
        "url": "https://ulii.org",
        "logo": "images/liis/ulii.png",
        "domain": "ulii.org",
    },
    {
        "name": "ZambiaLII",
        "country": "Zambia",
        "url": "https://zambialii.org",
        "logo": "images/liis/zambialii.png",
        "domain": "zambialii.org",
    },
    {
        "name": "ZanzibarLII",
        "country": "Zanzibar",
        "url": "https://zanzibarlii.org",
        "logo": "images/liis/zanzibarlii.png",
        "domain": "zanzibarlii.org",
    },
    {
        "name": "ZimLII",
        "country": "Zimbabwe",
        "url": "https://zimlii.org",
        "logo": "images/liis/zimlii.png",
        "domain": "zimlii.org",
    },
]
