import logging

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import connection, models, transaction
from django.db.models import Exists, OuterRef
from django.db.models.deletion import ProtectedError
from django.urls import reverse
from django.utils.html import format_html
from django.utils.http import urlencode
from django.utils.translation import gettext_lazy as _
from django_lifecycle import AFTER_SAVE, LifecycleModelMixin
from treebeard.mp_tree import MP_Node

from peachjam.models.lifecycle import on_attribute_changed
from peachjam.tasks import refresh_flynote_document_count

log = logging.getLogger(__name__)

__all__ = ["Flynote", "JudgmentFlynote", "FlynoteDocumentCount"]


class Flynote(LifecycleModelMixin, MP_Node):
    """Hierarchical flynote tree node using treebeard's materialised path. This is used to represent textual flynotes
    in a tree form, for browsing and for search.

    Use of this model is controlled by settings.PEACHJAM["USE_FLYNOTE_TREE"].

    When SUMMARISER_INDEX_FLYNOTES is False, then this model is ignored and only text-based flynotes are used.
    In that case, Judgment.flynote_raw is the source of truth for a flynote, and it is copied directly to
    Judgment.flynote, which is shown to the user.

    When SUMMARISER_INDEX_FLYNOTES is True, then Judgment.flynote_raw is parsed into a tree of Flynote nodes. These
    are considered the source of truth and Judgment.flynote is generated from the linked Flynote models.

    When this model is used, it means we can make sweeping adjustments to all flynotes by manipulating the models,
    and the changes get persisted to Judgment.flynote which ensures the textual format matches the object tree format.
    This is useful for things like merging flynotes, correcting typos, etc.

    Additionally, Judgment.flynote_raw is ALSO updated (which may seem confusing) so that the tree changes are not
    "reverted" if an editor makes small changes to Judgment.flynote_raw.

    The logical model (when the Flynote models are in use) is:

    summary generated by AI (or human edits flynote in admin area):
      -> Judgment.flynote_raw updated
      -> Flynote tree updated to match flynote_raw
      -> Judgment.flynote updated to match Flynote tree AND Judgment.flynote_raw updated to match Flynote tree (with
         flag to prevent circular events)

    Flynote tree updated (eg. node renamed, merged, moved):
      -> Judgment.flynote updated to match Flynote tree AND Judgment.flynote_raw updated to match Flynote tree (with
         flag to prevent circular events)
    """

    name = models.CharField(_("name"), max_length=255)
    deprecated = models.BooleanField(_("deprecated"), default=False, db_index=True)

    class Meta:
        verbose_name = _("flynote")
        verbose_name_plural = _("flynotes")

    def __str__(self):
        return f"{self.name} ({self.pk})"

    def get_absolute_url(self):
        return reverse("flynote_detail", kwargs={"pk": self.pk})

    def validate_deprecated_invariant(self):
        """Ensure an active node cannot exist under a deprecated ancestor."""
        if self.deprecated or self.is_root():
            return

        if self.get_ancestors().filter(deprecated=True).exists():
            raise ValidationError(
                {
                    "deprecated": _(
                        "A flynote cannot be active when any ancestor is deprecated."
                    )
                }
            )

    def validate_unique_sibling_name(self):
        """Prevent admin edits from creating duplicate sibling/root names."""
        if not self.pk:
            return

        name = self.name.strip()
        duplicate = (
            self.get_siblings().exclude(pk=self.pk).filter(name__iexact=name).first()
        )
        if not duplicate:
            return

        merge_url = "{}?{}".format(
            reverse("flynote-manager"),
            urlencode(
                {
                    "flynote": duplicate.pk,
                    "tab": "merge",
                    "selected": self.pk,
                }
            ),
        )
        raise ValidationError(
            {
                "name": format_html(
                    _(
                        "A sibling flynote already has this name. "
                        '<a href="{}">Merge this flynote into that one</a> instead.'
                    ),
                    merge_url,
                )
            }
        )

    def clean(self):
        super().clean()
        self.validate_deprecated_invariant()
        self.validate_unique_sibling_name()

    @on_attribute_changed(AFTER_SAVE, ["name", "path"], [])
    def serialise_linked_judgments(self):
        subtree_flynote_ids = Flynote.objects.filter(
            path__startswith=self.path
        ).values_list("pk", flat=True)

        from peachjam.tasks import serialise_judgment_flynote_tree

        judgment_ids = (
            JudgmentFlynote.objects.filter(flynote_id__in=subtree_flynote_ids)
            .values_list("document_id", flat=True)
            .distinct()
        )
        for judgment_id in judgment_ids:
            serialise_judgment_flynote_tree(judgment_id)

    @on_attribute_changed(AFTER_SAVE, ["deprecated"], [])
    def handle_deprecated_changed(self):
        self.cascade_deprecated()

        if (
            not self.deprecated
            or self.initial_value("deprecated")
            or not settings.PEACHJAM["SUMMARISE_USE_FLYNOTE_TREE"]
        ):
            return

        from peachjam.tasks import generate_judgment_summary

        # this flynote is deprecated, any documents linked to it must have new summaries generated
        judgment_ids = self.judgments.values_list("document_id", flat=True).distinct()
        for judgment_id in judgment_ids:
            generate_judgment_summary(judgment_id)

    def cascade_deprecated(self):
        """Propagate this node's current deprecated state to its descendants.

        The current node is assumed to have already been saved with the desired
        state. The cascade mirrors that state across the subtree so editors can
        toggle an entire branch on or off with a single change.
        """
        for child in self.get_children():
            if child.deprecated != self.deprecated:
                child.deprecated = self.deprecated
                # this will trigger a change, which will call cascade_deprecated on the child
                child.save()
            else:
                child.cascade_deprecated()

    def rename_to_or_merge(self, new_name):
        """Rename this flynote, or merge it into an existing sibling of the same name.

        This is the small convenience wrapper around ``merge_sources_into`` for
        cleanup flows that only need to decide whether the cleaned name should
        become a rename or a sibling merge.
        """
        if not self.pk:
            raise ValidationError(_("Flynote must be saved before it can be renamed."))

        new_name = (new_name or "").strip()
        if not new_name:
            raise ValidationError(_("Flynote name cannot be blank."))

        duplicate = (
            self.get_siblings()
            .exclude(pk=self.pk)
            .filter(name__iexact=new_name)
            .first()
        )
        if duplicate:
            duplicate.merge_sources_into([self])
            return duplicate, "merge"

        self.name = new_name
        self.full_clean()
        self.save(update_fields=["name"])
        return self, "rename"

    def merge_sources_into(self, sources):
        """Merge sibling flynotes into this flynote.

        Direct judgment links on each source move to this flynote. Source
        children are merged into matching children on this flynote, or
        re-parented under this flynote. Source flynotes are then deleted
        explicitly.
        """
        if not all(isinstance(source, Flynote) for source in sources):
            raise TypeError("merge_sources_into expects a list of Flynote objects")

        source_ids = []
        for source in sources:
            if source.pk and source.pk != self.pk and source.pk not in source_ids:
                source_ids.append(source.pk)

        if not source_ids:
            return

        with transaction.atomic():
            target = Flynote.objects.select_for_update().get(pk=self.pk)
            sources = list(
                Flynote.objects.select_for_update()
                .filter(pk__in=source_ids)
                .order_by("path")
            )

            if len(sources) != len(source_ids):
                raise ValidationError(
                    _("One or more selected flynotes no longer exist.")
                )

            target_parent = target.get_parent()
            target_parent_id = target_parent.pk if target_parent else None
            source_parents = []
            source_parent_ids = set()

            for source in sources:
                source_parent = source.get_parent()
                source_parent_id = source_parent.pk if source_parent else None
                if source.depth != target.depth or source_parent_id != target_parent_id:
                    raise ValidationError(
                        _(
                            "Flynotes can only be merged into a sibling at the same level."
                        )
                    )
                if source_parent_id and source_parent_id not in source_parent_ids:
                    source_parents.append(source_parent)
                    source_parent_ids.add(source_parent_id)

            log.info(f"Merging flynotes into {self}: {sources}")
            for source in sources:
                target._merge_other_into(source)

            for source_parent in source_parents:
                if Flynote.objects.filter(pk=source_parent.pk).exists():
                    source_parent.refresh_from_db()
                    FlynoteDocumentCount.quick_refresh_for_single_flynote(source_parent)
            log.info("Finished merging flynotes")

    def _merge_other_into(self, source):
        """Merge one corresponding source flynote into this flynote."""
        from peachjam.analysis.flynotes import FlynoteParser

        for judgment_flynote in list(source.judgments.select_for_update()):
            duplicate = JudgmentFlynote.objects.filter(
                document_id=judgment_flynote.document_id,
                flynote=self,
            ).exists()
            if duplicate:
                judgment_flynote.delete()
            else:
                judgment_flynote.flynote = self
                judgment_flynote.save(update_fields=["flynote"])

        for child in list(source.get_children()):
            normalised = FlynoteParser.normalise_name(child.name)
            target_child = None
            if normalised:
                target_child = next(
                    (
                        candidate
                        for candidate in self.get_children().select_for_update()
                        if FlynoteParser.normalise_name(candidate.name) == normalised
                    ),
                    None,
                )

            if target_child:
                target_child._merge_other_into(child)
            else:
                # moving nodes updates path attributes, so always work with latest info from db
                child.refresh_from_db()
                self.refresh_from_db()
                child.move(self, pos="last-child")

        source.delete()
        FlynoteDocumentCount.quick_refresh_for_single_flynote(self)

    def prune_empty_descendants(self):
        """Delete empty flynotes under this flynote.

        Locks the tree root before pruning so concurrent tree/count updates for
        the same tree are serialised, even when pruning only a subtree.
        """
        flynote_id = self.pk

        with transaction.atomic():
            flynote = Flynote.objects.filter(pk=flynote_id).first()
            if not flynote:
                log.info(
                    "No flynote with id %s exists while pruning empty descendants, ignoring.",
                    flynote_id,
                )
                return

            tree_root = (
                Flynote.objects.select_for_update()
                .filter(pk=flynote.get_root().pk)
                .first()
            )
            if not tree_root:
                log.info(
                    "No flynote root exists for %s while pruning empty descendants, ignoring.",
                    flynote_id,
                )
                return

            flynote.refresh_from_db()
            root_path = flynote.path

            # Stale count rows can briefly make a linked flynote look empty, so
            # only consider nodes with no linked judgments anywhere in their
            # subtree and still guard against races during delete.
            log.info("Pruning empty flynotes under %s", flynote)
            linked_judgments = JudgmentFlynote.objects.filter(
                flynote__path__startswith=OuterRef("path")
            )
            empty_flynotes = list(
                Flynote.objects.filter(path__startswith=root_path)
                .filter(document_count_cache__isnull=True)
                .annotate(has_linked_judgments=Exists(linked_judgments))
                .filter(has_linked_judgments=False)
                .order_by("-depth", "-path")
            )
            for empty_flynote in empty_flynotes:
                try:
                    empty_flynote.delete()
                except Flynote.DoesNotExist:
                    log.warning(
                        "Skipping prune of flynote %s because it was already deleted.",
                        empty_flynote.pk,
                    )
                except ProtectedError:
                    log.warning(
                        "Skipping prune of flynote %s because linked judgments still protect it.",
                        empty_flynote.pk,
                    )

    @classmethod
    def flynotes_to_string(cls, judgment_flynotes):
        """Convert a queryset of JudgmentFlynote to a string representation."""
        if not judgment_flynotes:
            return None

        # Flynote uses Treebeard's materialized-path storage. Rebuild each leaf's
        # root-to-leaf chain by slicing its path into step-sized prefixes, then
        # fetch all needed nodes in one query instead of calling get_ancestors()
        # for every linked flynote individually.
        ancestor_paths = set()
        for judgment_flynote in judgment_flynotes:
            leaf = judgment_flynote.flynote
            for end in range(leaf.steplen, len(leaf.path) + 1, leaf.steplen):
                ancestor_paths.add(leaf.path[:end])

        flynote_nodes = Flynote.objects.filter(path__in=ancestor_paths).only(
            "path",
            "name",
        )
        node_by_path = {node.path: node for node in flynote_nodes}

        flynote_lines = []
        for judgment_flynote in judgment_flynotes:
            leaf = judgment_flynote.flynote
            components = []
            for end in range(leaf.steplen, len(leaf.path) + 1, leaf.steplen):
                node = node_by_path.get(leaf.path[:end])
                if node:
                    components.append(node.name)
            if components:
                flynote_lines.append(" — ".join(components))

        if not flynote_lines:
            return None

        return "\n".join(sorted(flynote_lines))


class JudgmentFlynote(models.Model):
    """Links a judgment to a flynote topic (leaf node)."""

    document = models.ForeignKey(
        "peachjam.Judgment",
        related_name="flynotes",
        on_delete=models.CASCADE,
        verbose_name=_("judgment"),
    )
    flynote = models.ForeignKey(
        Flynote,
        on_delete=models.PROTECT,
        related_name="judgments",
        verbose_name=_("flynote"),
    )

    class Meta:
        ordering = ["flynote"]
        verbose_name = _("judgment flynote")
        verbose_name_plural = _("judgment flynotes")
        unique_together = ("document", "flynote")

    def __str__(self):
        return f"{self.flynote.name} - {self.document.title}"


class FlynoteDocumentCount(models.Model):
    """Pre-calculated count of judgments linked to a flynote and its descendants."""

    flynote = models.OneToOneField(
        Flynote,
        on_delete=models.CASCADE,
        related_name="document_count_cache",
        verbose_name=_("flynote"),
    )
    count = models.PositiveIntegerField(_("count"), default=0, db_index=True)

    class Meta:
        verbose_name = _("flynote document count")
        verbose_name_plural = _("flynote document counts")

    def __str__(self):
        return f"{self.flynote.name}: {self.count}"

    @classmethod
    def quick_refresh_for_single_flynote(cls, flynote, limit=1000):
        """Refresh counts for one flynote now if it is cheap. Always queues a background refresh of the root.

        Child counts are assumed to already be correct. The estimate is used
        only as a cheap threshold check; refresh_for_flynote() still computes
        the exact count if the subtree is small enough.
        """
        flynote.refresh_from_db(fields=["path", "numchild"])
        direct_count = (
            JudgmentFlynote.objects.filter(flynote=flynote)
            .values("document_id")
            .distinct()
            .count()
        )
        child_count = sum(
            cls.objects.filter(flynote__in=flynote.get_children()).values_list(
                "count", flat=True
            )
        )

        estimated_count = direct_count + child_count
        if estimated_count < limit:
            cls.refresh_for_flynote(flynote)

        # always queue up a refresh of the root (if this not a root)
        if flynote.depth > 1:
            refresh_flynote_document_count(flynote.get_root().pk)

    @classmethod
    def refresh_for_flynote(cls, flynote):
        """Recompute document counts for flynotes under *flynote*, which could be a root or just a subtree.

        Each node's count includes documents linked directly to it plus
        documents linked to any of its descendants. Uses treebeard's
        materialised path to walk ancestors efficiently in a single SQL
        query, following the same pattern as TaxonomyDocumentCount.
        """
        if flynote is None:
            raise ValueError("refresh_for_flynote requires a flynote node")

        flynote_id = flynote.pk

        with transaction.atomic():
            flynote = Flynote.objects.filter(pk=flynote_id).first()
            if not flynote:
                log.info(
                    "No flynote with id %s exists while refreshing counts, ignoring.",
                    flynote_id,
                )
                return

            tree_root = (
                Flynote.objects.select_for_update()
                .filter(pk=flynote.get_root().pk)
                .first()
            )
            if not tree_root:
                log.info(
                    "No flynote root exists for %s while refreshing counts, ignoring.",
                    flynote_id,
                )
                return

            flynote.refresh_from_db()
            root_path = flynote.path
            with connection.cursor() as cursor:
                log.info("Deleting cached flynote counts under %s", flynote)
                cursor.execute(
                    """
                    DELETE FROM peachjam_flynotedocumentcount
                    WHERE flynote_id IN (
                        SELECT id FROM peachjam_flynote
                        WHERE path LIKE %s
                    )
                    """,
                    [root_path + "%"],
                )

                log.info("Rebuilding cached flynote counts under %s", flynote)
                cursor.execute(
                    """
                    INSERT INTO peachjam_flynotedocumentcount (flynote_id, count)
                    SELECT
                        ancestor.id,
                        COUNT(DISTINCT jf.document_id)
                    FROM peachjam_flynote ancestor
                    INNER JOIN peachjam_flynote descendant
                        ON descendant.path LIKE ancestor.path || '%%'
                        AND descendant.path LIKE %s
                    INNER JOIN peachjam_judgmentflynote jf
                        ON jf.flynote_id = descendant.id
                    WHERE ancestor.path LIKE %s
                    GROUP BY ancestor.id
                    ON CONFLICT (flynote_id)
                    DO UPDATE SET count = EXCLUDED.count
                    """,
                    [root_path + "%", root_path + "%"],
                )

        flynote.prune_empty_descendants()
        log.info("Refreshed document counts for flynote tree under %s", flynote)

    @classmethod
    def refresh_for_all_flynotes(cls):
        """Recompute document counts for each flynote tree independently."""
        refreshed = 0
        for root in list(Flynote.get_root_nodes()):
            cls.refresh_for_flynote(root)
            refreshed += 1

        log.info(
            "Refreshed document counts for all flynotes across %d roots.",
            refreshed,
        )
