import logging

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import connection, models, transaction
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django_lifecycle import AFTER_SAVE, LifecycleModelMixin
from treebeard.mp_tree import MP_Node

from peachjam.models.lifecycle import on_attribute_changed

log = logging.getLogger(__name__)

__all__ = ["Flynote", "JudgmentFlynote", "FlynoteDocumentCount"]


class Flynote(LifecycleModelMixin, MP_Node):
    """Hierarchical flynote tree node using treebeard's materialised path. This is used to represent textual flynotes
    in a tree form, for browsing and for search.

    Use of this model is controlled by settings.PEACHJAM["USE_FLYNOTE_TREE"].

    When SUMMARISER_INDEX_FLYNOTES is False, then this model is ignored and only text-based flynotes are used.
    In that case, Judgment.flynote_raw is the source of truth for a flynote, and it is copied directly to
    Judgment.flynote, which is shown to the user.

    When SUMMARISER_INDEX_FLYNOTES is True, then Judgment.flynote_raw is parsed into a tree of Flynote nodes. These
    are considered the source of truth and Judgment.flynote is generated from the linked Flynote models.

    When this model is used, it means we can make sweeping adjustments to all flynotes by manipulating the models,
    and the changes get persisted to Judgment.flynote which ensures the textual format matches the object tree format.
    This is useful for things like merging flynotes, correcting typos, etc.

    Additionally, Judgment.flynote_raw is ALSO updated (which may seem confusing) so that the tree changes are not
    "reverted" if an editor makes small changes to Judgment.flynote_raw.

    The logical model (when the Flynote models are in use) is:

    summary generated by AI (or human edits flynote in admin area):
      -> Judgment.flynote_raw updated
      -> Flynote tree updated to match flynote_raw
      -> Judgment.flynote updated to match Flynote tree AND Judgment.flynote_raw updated to match Flynote tree (with
         flag to prevent circular events)

    Flynote tree updated (eg. node renamed, merged, moved):
      -> Judgment.flynote updated to match Flynote tree AND Judgment.flynote_raw updated to match Flynote tree (with
         flag to prevent circular events)
    """

    name = models.CharField(_("name"), max_length=255)
    deprecated = models.BooleanField(_("deprecated"), default=False, db_index=True)
    node_order_by = ["name"]

    class Meta:
        verbose_name = _("flynote")
        verbose_name_plural = _("flynotes")

    def __str__(self):
        return f"{self.name} ({self.pk})"

    def get_absolute_url(self):
        return reverse("flynote_detail", kwargs={"pk": self.pk})

    def validate_deprecated_invariant(self):
        """Ensure an active node cannot exist under a deprecated ancestor."""
        if self.deprecated or self.is_root():
            return

        if self.get_ancestors().filter(deprecated=True).exists():
            raise ValidationError(
                {
                    "deprecated": _(
                        "A flynote cannot be active when any ancestor is deprecated."
                    )
                }
            )

    def clean(self):
        super().clean()
        self.validate_deprecated_invariant()

    @on_attribute_changed(AFTER_SAVE, ["name", "path"], [])
    def serialise_linked_judgments(self):
        subtree_flynote_ids = Flynote.objects.filter(
            path__startswith=self.path
        ).values_list("pk", flat=True)

        from peachjam.tasks import serialise_judgment_flynote_tree

        judgment_ids = (
            JudgmentFlynote.objects.filter(flynote_id__in=subtree_flynote_ids)
            .values_list("document_id", flat=True)
            .distinct()
        )
        for judgment_id in judgment_ids:
            serialise_judgment_flynote_tree(judgment_id)

    @on_attribute_changed(AFTER_SAVE, ["deprecated"], [])
    def handle_deprecated_changed(self):
        self.cascade_deprecated()

        if (
            not self.deprecated
            or self.initial_value("deprecated")
            or not settings.PEACHJAM["SUMMARISE_USE_FLYNOTE_TREE"]
        ):
            return

        from peachjam.tasks import generate_judgment_summary

        # this flynote is deprecated, any documents linked to it must have new summaries generated
        judgment_ids = self.judgments.values_list("document_id", flat=True).distinct()
        for judgment_id in judgment_ids:
            generate_judgment_summary(judgment_id)

    def cascade_deprecated(self):
        """Propagate this node's current deprecated state to its descendants.

        The current node is assumed to have already been saved with the desired
        state. The cascade mirrors that state across the subtree so editors can
        toggle an entire branch on or off with a single change.
        """
        for child in self.get_children():
            if child.deprecated != self.deprecated:
                child.deprecated = self.deprecated
                # this will trigger a change, which will call cascade_deprecated on the child
                child.save()
            else:
                child.cascade_deprecated()

    @classmethod
    def flynotes_to_string(cls, judgment_flynotes):
        """Convert a queryset of JudgmentFlynote to a string representation."""
        if not judgment_flynotes:
            return None

        # Flynote uses Treebeard's materialized-path storage. Rebuild each leaf's
        # root-to-leaf chain by slicing its path into step-sized prefixes, then
        # fetch all needed nodes in one query instead of calling get_ancestors()
        # for every linked flynote individually.
        ancestor_paths = set()
        for judgment_flynote in judgment_flynotes:
            leaf = judgment_flynote.flynote
            for end in range(leaf.steplen, len(leaf.path) + 1, leaf.steplen):
                ancestor_paths.add(leaf.path[:end])

        flynote_nodes = Flynote.objects.filter(path__in=ancestor_paths).only(
            "path",
            "name",
        )
        node_by_path = {node.path: node for node in flynote_nodes}

        flynote_lines = []
        for judgment_flynote in judgment_flynotes:
            leaf = judgment_flynote.flynote
            components = []
            for end in range(leaf.steplen, len(leaf.path) + 1, leaf.steplen):
                node = node_by_path.get(leaf.path[:end])
                if node:
                    components.append(node.name)
            if components:
                flynote_lines.append(" — ".join(components))

        if not flynote_lines:
            return None

        return "\n".join(flynote_lines)


class JudgmentFlynote(models.Model):
    """Links a judgment to a flynote topic (leaf node)."""

    document = models.ForeignKey(
        "peachjam.Judgment",
        related_name="flynotes",
        on_delete=models.CASCADE,
        verbose_name=_("judgment"),
    )
    flynote = models.ForeignKey(
        Flynote,
        on_delete=models.PROTECT,
        related_name="judgments",
        verbose_name=_("flynote"),
    )

    class Meta:
        ordering = ["flynote"]
        verbose_name = _("judgment flynote")
        verbose_name_plural = _("judgment flynotes")
        unique_together = ("document", "flynote")

    def __str__(self):
        return f"{self.flynote.name} - {self.document.title}"


class FlynoteDocumentCount(models.Model):
    """Pre-calculated count of judgments linked to a flynote and its descendants."""

    flynote = models.OneToOneField(
        Flynote,
        on_delete=models.CASCADE,
        related_name="document_count_cache",
        verbose_name=_("flynote"),
    )
    count = models.PositiveIntegerField(_("count"), default=0, db_index=True)

    class Meta:
        verbose_name = _("flynote document count")
        verbose_name_plural = _("flynote document counts")

    def __str__(self):
        return f"{self.flynote.name}: {self.count}"

    @classmethod
    def refresh_for_flynote(cls, root):
        """Recompute document counts for flynotes under *root*.

        Each node's count includes documents linked directly to it plus
        documents linked to any of its descendants. Uses treebeard's
        materialised path to walk ancestors efficiently in a single SQL
        query, following the same pattern as TaxonomyDocumentCount.
        """
        if root is None:
            raise ValueError("refresh_for_flynote requires a root flynote node")

        root_id = root.pk

        with transaction.atomic():
            root = Flynote.objects.select_for_update().filter(pk=root_id).first()
            if not root:
                log.info(
                    "No flynote root with id %s exists while refreshing counts, ignoring.",
                    root_id,
                )
                return

            root_path = root.path
            with connection.cursor() as cursor:
                log.info("Deleting cached flynote counts under root %s", root)
                cursor.execute(
                    """
                    DELETE FROM peachjam_flynotedocumentcount
                    WHERE flynote_id IN (
                        SELECT id FROM peachjam_flynote
                        WHERE path LIKE %s
                    )
                    """,
                    [root_path + "%"],
                )

                log.info("Rebuilding cached flynote counts under root %s", root)
                cursor.execute(
                    """
                    INSERT INTO peachjam_flynotedocumentcount (flynote_id, count)
                    SELECT
                        ancestor.id,
                        COUNT(DISTINCT jf.document_id)
                    FROM peachjam_flynote ancestor
                    INNER JOIN peachjam_flynote descendant
                        ON descendant.path LIKE ancestor.path || '%%'
                        AND descendant.path LIKE %s
                    INNER JOIN peachjam_judgmentflynote jf
                        ON jf.flynote_id = descendant.id
                    WHERE ancestor.path LIKE %s
                    GROUP BY ancestor.id
                    ON CONFLICT (flynote_id)
                    DO UPDATE SET count = EXCLUDED.count
                    """,
                    [root_path + "%", root_path + "%"],
                )

            # After rebuilding cumulative counts, any node in this subtree
            # without a count row has no linked documents in its subtree and
            # can be pruned safely using Treebeard's delete handling.
            log.info("Pruning empty flynotes under root %s", root)
            empty_flynotes = list(
                Flynote.objects.filter(path__startswith=root_path)
                .filter(document_count_cache__isnull=True)
                .order_by("-depth", "-path")
            )
            for flynote in empty_flynotes:
                flynote.delete()

        log.info("Refreshed document counts for flynote tree rooted at %s", root)

    @classmethod
    def refresh_for_all_flynotes(cls):
        """Recompute document counts for each flynote tree independently."""
        refreshed = 0
        for root in list(Flynote.get_root_nodes()):
            cls.refresh_for_flynote(root)
            refreshed += 1

        log.info(
            "Refreshed document counts for all flynotes across %d roots.",
            refreshed,
        )
