# Generated by Django 3.2.13 on 2022-07-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liiweb", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courtclass",
            options={"ordering": ("name",), "verbose_name_plural": "Court classes"},
        ),
    ]
