# flake8: noqa
from .about import *
from .article import *
from .attachment_media import *
from .authors import *
from .autocomplete import *
from .books import *
from .courts import *
from .document_nature import *
from .document_problem import *
from .documents import *
from .external_document import *
from .gazette import *
from .generic_document import *
from .home import *
from .judgment import *
from .legal_instrument import *
from .legislation import *
from .login import *
from .place import *
from .pocketlaw import *
from .robots import *
from .taxonomy import *
from .terms_of_use import *
from .widgets import *
