# Generated by Django 4.2.14 on 2025-03-24 14:18

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("peachjam", "0203_alter_folder_options"),
    ]

    operations = [
        # NOTE: if this migration fails with a permission error, as a superuser run the following command (it only
        #       needs to be run once):
        #
        #   CREATE EXTENSION vector;
        #
        # Alternatively, ensure your test user has superuser permissions:
        #
        #   ALTER USER peachjam WITH SUPERUSER;
        #
        VectorExtension(),
    ]
