# Generated by Django 4.2.14 on 2025-03-25 06:18

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("peachjam", "0203_alter_folder_options"),
        ("peachjam_ml", "0001_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_text_md5",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "text_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1024, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peachjam.coredocument",
                        related_name="embedding",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("text", models.TextField()),
                ("portion", models.CharField(blank=True, max_length=4096, null=True)),
                ("chunk_n", models.IntegerField(default=0)),
                ("n_chunks", models.IntegerField(default=1)),
                (
                    "provision_type",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "parent_titles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1024),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "parent_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1024),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("text_embedding", pgvector.django.vector.VectorField(dimensions=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peachjam.coredocument",
                    ),
                ),
            ],
        ),
    ]
