# Generated by Django 4.2.14 on 2025-03-25 15:24

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_ml", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contentchunk",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["text_embedding"],
                m=16,
                name="peachjam_ml_cchunk_emb_ix",
                opclasses=["vector_ip_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="documentembedding",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["text_embedding"],
                m=16,
                name="peachjam_ml_docembedding_emb_ix",
                opclasses=["vector_ip_ops"],
            ),
        ),
    ]
