# Generated by Django 4.2.14 on 2025-06-23 10:44

from django.db import migrations

from peachjam_ml.tasks import update_document_embeddings


def forwards(apps, schema_editor):
    """Mark all legislation documents with content_html_is_akn as dirty. We want to do this because we
    recently changed how the text for portions is extracted from the HTML.
    """
    CoreDocument = apps.get_model("peachjam", "CoreDocument")
    DocumentEmbedding = apps.get_model("peachjam_ml", "DocumentEmbedding")

    doc_ids = CoreDocument.objects.filter(
        content_html_is_akn=True,
        embedding__isnull=False,
    ).values_list("id", flat=True)

    DocumentEmbedding.objects.filter(document_id__in=doc_ids).update(
        content_text_md5=None
    )

    # queue background updates
    for doc_id in doc_ids:
        update_document_embeddings(doc_id, schedule=5)


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_ml", "0003_embedding_indexes"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
