# Generated by Django 4.2.14 on 2025-11-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_ml", "0004_chatthread"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatthread",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="chatthread",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="messages_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
