# Generated by Django 4.2.14 on 2024-05-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_ml", "0005_alter_chatthread_options_chatthread_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentembedding",
            name="summary_text_md5",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
