# Generated by Django 4.2.14 on 2025-11-21 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peachjam_ml", "0006_documentembedding_summary_text_md5"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatthread",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
