# Generated by Django 3.2.12 on 2022-04-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("africanlii", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="legislation",
            name="toc_json",
        ),
    ]
