# Generated by Django 3.2.12 on 2022-04-03 15:07

from django.db import migrations, models
import django.db.models.deletion
import peachjam.models.core_document_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peachjam', '0003_initial'),
        ('africanlii', '0001_initial'),
        ('countries_plus', '0005_auto_20160224_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('coredocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peachjam.coredocument')),
                ('case_number_numeric', models.CharField(blank=True, max_length=1024, null=True)),
                ('case_number_year', models.IntegerField(blank=True, null=True)),
                ('case_number_string', models.CharField(blank=True, max_length=1024, null=True)),
                ('headnote_holding', models.TextField(blank=True)),
                ('additional_citations', models.TextField(blank=True)),
                ('flynote', models.TextField(blank=True)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.court')),
                ('judges', models.ManyToManyField(blank=True, to='africanlii.Judge')),
            ],
            options={
                'ordering': ['title'],
            },
            bases=('peachjam.coredocument',),
        ),
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('coredocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peachjam.coredocument')),
                ('toc_json', models.JSONField(blank=True, null=True)),
                ('metadata_json', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Legislation',
            },
            bases=('peachjam.coredocument',),
        ),
        migrations.CreateModel(
            name='MatterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegalInstrument',
            fields=[
                ('coredocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peachjam.coredocument')),
                ('authoring_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='africanlii.authoringbody')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='africanlii.documentnature')),
            ],
            bases=('peachjam.coredocument',),
        ),
        migrations.CreateModel(
            name='JudgmentMediaSummaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=peachjam.models.core_document_model.file_location)),
                ('size', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_summaries', to='africanlii.judgment')),
            ],
            options={
                'ordering': ['document', 'filename'],
            },
        ),
        migrations.AddField(
            model_name='judgment',
            name='matter_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.mattertype'),
        ),
        migrations.CreateModel(
            name='GenericDocument',
            fields=[
                ('coredocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peachjam.coredocument')),
                ('authoring_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='africanlii.authoringbody')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='africanlii.documentnature')),
            ],
            bases=('peachjam.coredocument',),
        ),
        migrations.AddField(
            model_name='court',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries_plus.country'),
        ),
        migrations.AlterUniqueTogether(
            name='court',
            unique_together={('name', 'country')},
        ),
    ]
