# Generated by Django 3.2.12 on 2022-04-01 09:46

import africanlii.models.core_document_model
import africanlii.models.judgment
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('languages_plus', '0004_auto_20171214_0004'),
        ('africanlii', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthoringBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoreDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('legislation', 'Legislation'), ('generic_document', 'Generic Document'), ('legal_instrument', 'Legal Instrument'), ('judgment', 'Judgment')], max_length=255)),
                ('title', models.CharField(max_length=1024)),
                ('date', models.DateField()),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('citation', models.CharField(blank=True, max_length=1024, null=True)),
                ('content_html', models.TextField(blank=True, null=True)),
                ('expression_frbr_uri', models.CharField(max_length=1024, unique=True)),
                ('work_frbr_uri', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries_plus.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages_plus.language')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='judgment',
            options={'ordering': ['document__title']},
        ),
        migrations.AlterModelOptions(
            name='mattertype',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='judgment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='judgment',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='judgment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='judgment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='judgment',
            name='document_content',
        ),
        migrations.RemoveField(
            model_name='judgment',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='judgment',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='judgment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='judgment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='judgment',
            name='additional_citations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.court'),
        ),
        migrations.AddField(
            model_name='judgment',
            name='flynote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='headnote_holding',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=africanlii.models.core_document_model.file_location)),
                ('filename', models.CharField(max_length=1024)),
                ('mimetype', models.CharField(max_length=1024)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='africanlii.coredocument')),
            ],
            options={
                'ordering': ['document'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries_plus.country')),
            ],
            options={
                'verbose_name_plural': 'localities',
                'ordering': ['name'],
                'unique_together': {('name', 'jurisdiction')},
            },
        ),
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toc_json', models.JSONField(blank=True, null=True)),
                ('metadata_json', models.JSONField()),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='africanlii.coredocument')),
            ],
            options={
                'ordering': ['document__title'],
            },
        ),
        migrations.CreateModel(
            name='LegalInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authoring_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='africanlii.authoringbody')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='africanlii.coredocument')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='africanlii.documentnature')),
            ],
            options={
                'ordering': ['document__title'],
            },
        ),
        migrations.CreateModel(
            name='JudgmentMediaSummaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=africanlii.models.judgment.media_summary_file_location)),
                ('size', models.IntegerField()),
                ('filename', models.CharField(help_text='Unique attachment filename', max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judgment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_summaries', to='africanlii.judgment')),
            ],
            options={
                'ordering': ['judgment__document__title'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=africanlii.models.core_document_model.file_location)),
                ('filename', models.CharField(max_length=1024)),
                ('mimetype', models.CharField(max_length=1024)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='africanlii.coredocument')),
            ],
            options={
                'ordering': ['document'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authoring_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='africanlii.authoringbody')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='africanlii.coredocument')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='africanlii.documentnature')),
            ],
            options={
                'ordering': ['document__title'],
            },
        ),
        migrations.AddField(
            model_name='coredocument',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.locality'),
        ),
        migrations.AddField(
            model_name='judgment',
            name='document',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='africanlii.coredocument'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judgment',
            name='judges',
            field=models.ManyToManyField(blank=True, to='africanlii.Judge'),
        ),
    ]
