# Generated by Django 3.2.12 on 2022-03-29 19:17

import africanlii.models.core_document_model
import africanlii.models.judgment
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('languages_plus', '0004_auto_20171214_0004'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('africanlii', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthoringBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='judgment',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='judgment',
            old_name='document_content',
            new_name='content_html',
        ),
        migrations.RemoveField(
            model_name='judgment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='judgment',
            name='source_file',
        ),
        migrations.AddField(
            model_name='judgment',
            name='additional_citations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.court'),
        ),
        migrations.AddField(
            model_name='judgment',
            name='expression_frbr_uri',
            field=models.CharField(default='', max_length=1024, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judgment',
            name='flynote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='headnote_holding',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='jurisdiction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='countries_plus.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judgment',
            name='language',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='languages_plus.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judgment',
            name='work_frbr_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=1024, null=True)),
                ('mimetype', models.CharField(max_length=1024, null=True)),
                ('file', models.FileField(upload_to=africanlii.models.core_document_model.source_file_location)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries_plus.country')),
            ],
            options={
                'verbose_name_plural': 'localities',
                'ordering': ['name'],
                'unique_together': {('name', 'jurisdiction')},
            },
        ),
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('date', models.DateField()),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('citation', models.CharField(blank=True, max_length=1024, null=True)),
                ('content_html', models.TextField(blank=True, null=True)),
                ('expression_frbr_uri', models.CharField(max_length=1024, unique=True)),
                ('work_frbr_uri', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('toc_json', models.JSONField(blank=True, null=True)),
                ('metadata_json', models.JSONField()),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries_plus.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages_plus.language')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.locality')),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('date', models.DateField()),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('citation', models.CharField(blank=True, max_length=1024, null=True)),
                ('content_html', models.TextField(blank=True, null=True)),
                ('expression_frbr_uri', models.CharField(max_length=1024, unique=True)),
                ('work_frbr_uri', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authoring_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='africanlii.authoringbody')),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries_plus.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages_plus.language')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.locality')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='africanlii.documentnature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JudgmentMediaSummaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=africanlii.models.judgment.media_summary_file_location)),
                ('size', models.IntegerField()),
                ('filename', models.CharField(help_text='Unique attachment filename', max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judgment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='africanlii.judgment')),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=1024, null=True)),
                ('mimetype', models.CharField(max_length=1024, null=True)),
                ('image', models.ImageField(upload_to=africanlii.models.core_document_model.image_location)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('date', models.DateField()),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('citation', models.CharField(blank=True, max_length=1024, null=True)),
                ('content_html', models.TextField(blank=True, null=True)),
                ('expression_frbr_uri', models.CharField(max_length=1024, unique=True)),
                ('work_frbr_uri', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authoring_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='africanlii.authoringbody')),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries_plus.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages_plus.language')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.locality')),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='africanlii.documentnature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='judgment',
            name='judges',
            field=models.ManyToManyField(blank=True, to='africanlii.Judge'),
        ),
        migrations.AddField(
            model_name='judgment',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.locality'),
        ),
    ]
