# Generated by Django 3.2.13 on 2022-06-27 10:34

import django.db.models.deletion
from django.db import migrations, models

import peachjam.models.attachments


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("peachjam", "0001_initial"),
        ("africanlii", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Judgment",
            fields=[
                (
                    "coredocument_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="peachjam.coredocument",
                    ),
                ),
                ("headnote_holding", models.TextField(blank=True)),
                ("additional_citations", models.TextField(blank=True)),
                ("flynote", models.TextField(blank=True)),
                (
                    "court",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="peachjam.author",
                    ),
                ),
                ("judges", models.ManyToManyField(blank=True, to="africanlii.Judge")),
            ],
            options={
                "ordering": ["title"],
            },
            bases=("peachjam.coredocument",),
        ),
        migrations.CreateModel(
            name="MatterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JudgmentMediaSummaryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=peachjam.models.attachments.file_location
                    ),
                ),
                ("size", models.IntegerField()),
                ("filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_summaries",
                        to="africanlii.judgment",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "filename"],
            },
        ),
        migrations.AddField(
            model_name="casenumber",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_numbers",
                to="africanlii.judgment",
            ),
        ),
        migrations.AddField(
            model_name="casenumber",
            name="matter_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="africanlii.mattertype",
            ),
        ),
    ]
