# Generated by Django 3.2.12 on 2022-03-24 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
        ('countries_plus', '0005_auto_20160224_1804'),
        ('africanlii', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthoringBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='judgment',
            old_name='document_content',
            new_name='content_html',
        ),
        migrations.RemoveField(
            model_name='judgment',
            name='author',
        ),
        migrations.AddField(
            model_name='judgment',
            name='additional_citations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.court'),
        ),
        migrations.AddField(
            model_name='judgment',
            name='expression_frbr_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='flynote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='headnote_holding',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='judgment',
            name='jurisdicition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='countries_plus.country'),
        ),
        migrations.AddField(
            model_name='judgment',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='languages_plus.language'),
        ),
        migrations.AddField(
            model_name='judgment',
            name='media_summary_file',
            field=models.FileField(blank=True, null=True, upload_to='judgments/media_summary/'),
        ),
        migrations.AddField(
            model_name='judgment',
            name='work_frbr_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries_plus.country')),
            ],
            options={
                'verbose_name_plural': 'localities',
                'ordering': ['name'],
                'unique_together': {('name', 'jurisdiction')},
            },
        ),
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('date', models.DateField()),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='')),
                ('citation', models.CharField(blank=True, max_length=1024, null=True)),
                ('content_html', models.TextField(blank=True, null=True)),
                ('expression_frbr_uri', models.CharField(blank=True, max_length=1024, null=True)),
                ('work_frbr_uri', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('toc_json', models.JSONField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('images', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.imageset')),
                ('jurisdicition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='countries_plus.country')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='languages_plus.language')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.locality')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('date', models.DateField()),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='')),
                ('citation', models.CharField(blank=True, max_length=1024, null=True)),
                ('content_html', models.TextField(blank=True, null=True)),
                ('expression_frbr_uri', models.CharField(blank=True, max_length=1024, null=True)),
                ('work_frbr_uri', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.authoringbody')),
                ('images', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.imageset')),
                ('jurisdicition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='countries_plus.country')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='languages_plus.language')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.locality')),
                ('nature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.documentnature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='africanlii.imageset')),
            ],
        ),
        migrations.CreateModel(
            name='GenericDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('date', models.DateField()),
                ('source_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='')),
                ('citation', models.CharField(blank=True, max_length=1024, null=True)),
                ('content_html', models.TextField(blank=True, null=True)),
                ('expression_frbr_uri', models.CharField(blank=True, max_length=1024, null=True)),
                ('work_frbr_uri', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nature', models.CharField(blank=True, max_length=1024, null=True)),
                ('author', models.CharField(blank=True, max_length=1024, null=True)),
                ('images', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.imageset')),
                ('jurisdicition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='countries_plus.country')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='languages_plus.language')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.locality')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='judgment',
            name='images',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.imageset'),
        ),
        migrations.AddField(
            model_name='judgment',
            name='judges',
            field=models.ManyToManyField(blank=True, to='africanlii.Judge'),
        ),
        migrations.AddField(
            model_name='judgment',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='africanlii.locality'),
        ),
    ]
