# Generated by Django 3.2.13 on 2022-05-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("africanlii", "0002_remove_legislation_toc_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="authoringbody",
            name="slug",
            field=models.SlugField(default="", editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="court",
            name="slug",
            field=models.SlugField(default="", editable=False, unique=True),
        ),
    ]
