# Generated by Django 3.2.12 on 2022-03-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('africanlii', '0002_auto_20220329_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='sourcefile',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='sourcefile',
            name='object_id',
        ),
        migrations.AddField(
            model_name='genericdocument',
            name='source_file',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='africanlii.sourcefile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judgment',
            name='source_file',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='africanlii.sourcefile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalinstrument',
            name='source_file',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='africanlii.sourcefile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legislation',
            name='source_file',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='africanlii.sourcefile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='mimetype',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='filename',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='mimetype',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
