# Generated by Django 3.2.12 on 2022-05-25 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("africanlii", "0002_remove_legislation_toc_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgment",
            name="case_number_numeric",
        ),
        migrations.RemoveField(
            model_name="judgment",
            name="case_number_string",
        ),
        migrations.RemoveField(
            model_name="judgment",
            name="case_number_year",
        ),
        migrations.RemoveField(
            model_name="judgment",
            name="matter_type",
        ),
        migrations.AddField(
            model_name="court",
            name="code",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CaseNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("string", models.CharField(blank=True, max_length=1024, null=True)),
                ("number", models.PositiveIntegerField(blank=True, null=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_numbers",
                        to="africanlii.judgment",
                    ),
                ),
                (
                    "matter_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="africanlii.mattertype",
                    ),
                ),
            ],
        ),
    ]
