# Generated by Django 3.2.13 on 2022-06-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("africanlii", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="judgment",
            old_name="court",
            new_name="author",
        ),
    ]
