# Generated by Django 3.2.12 on 2022-03-30 14:12

import africanlii.models.core_document_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africanlii', '0003_auto_20220330_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericdocument',
            name='source_file',
            field=models.FileField(upload_to=africanlii.models.core_document_model.source_file_location),
        ),
        migrations.AlterField(
            model_name='judgment',
            name='source_file',
            field=models.FileField(upload_to=africanlii.models.core_document_model.source_file_location),
        ),
        migrations.AlterField(
            model_name='legalinstrument',
            name='source_file',
            field=models.FileField(upload_to=africanlii.models.core_document_model.source_file_location),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='source_file',
            field=models.FileField(upload_to=africanlii.models.core_document_model.source_file_location),
        ),
    ]
