# Generated by Django 3.2.13 on 2022-05-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("africanlii", "0003_auto_20220525_1423"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authoringbody",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="court",
            name="slug",
        ),
    ]
