# Generated by Django 3.2.13 on 2022-06-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "peachjam",
            "0002_casenumber_judge_judgment_judgmentmediasummaryfile_mattertype",
        ),
        ("africanlii", "0003_rename_court_judgment_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="judgment",
            name="coredocument_ptr",
        ),
        migrations.RemoveField(
            model_name="judgment",
            name="judges",
        ),
        migrations.RemoveField(
            model_name="judgmentmediasummaryfile",
            name="document",
        ),
        migrations.DeleteModel(
            name="CaseNumber",
        ),
        migrations.DeleteModel(
            name="Judge",
        ),
        migrations.DeleteModel(
            name="Judgment",
        ),
        migrations.DeleteModel(
            name="JudgmentMediaSummaryFile",
        ),
        migrations.DeleteModel(
            name="MatterType",
        ),
    ]
