# Generated by Django 3.2.16 on 2023-02-14 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("countries_plus", "0005_auto_20160224_1804"),
        ("peachjam", "0051_backfill_extracted_citations"),
        ("africanlii", "0004_auto_20220630_0716"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ratification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, null=True, verbose_name="source URL"),
                ),
                (
                    "last_updated",
                    models.DateField(
                        blank=True, null=True, verbose_name="last updated"
                    ),
                ),
                (
                    "work",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratification",
                        to="peachjam.work",
                        verbose_name="work",
                    ),
                ),
            ],
            options={
                "verbose_name": "ratification",
                "verbose_name_plural": "ratifications",
            },
        ),
        migrations.CreateModel(
            name="RatificationCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ratification_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="ratification date"
                    ),
                ),
                (
                    "deposit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="deposit date"
                    ),
                ),
                (
                    "signature_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="signature date"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countries_plus.country",
                        verbose_name="country",
                    ),
                ),
                (
                    "ratification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="countries",
                        to="africanlii.ratification",
                        verbose_name="ratification",
                    ),
                ),
            ],
            options={
                "verbose_name": "ratification country",
                "verbose_name_plural": "ratification countries",
            },
        ),
        migrations.AddConstraint(
            model_name="ratificationcountry",
            constraint=models.UniqueConstraint(
                fields=("ratification", "country"), name="unique_ratification_country"
            ),
        ),
    ]
