# Generated by Django 3.2.12 on 2022-03-31 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('africanlii', '0004_auto_20220330_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgmentmediasummaryfile',
            name='judgment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_summaries', to='africanlii.judgment'),
        ),
    ]
