# Generated by Django 3.2.12 on 2022-03-31 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('africanlii', '0005_alter_judgmentmediasummaryfile_judgment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericdocument',
            name='source_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='africanlii.sourcefile'),
        ),
        migrations.AlterField(
            model_name='judgment',
            name='source_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='africanlii.sourcefile'),
        ),
        migrations.AlterField(
            model_name='legalinstrument',
            name='source_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='africanlii.sourcefile'),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='source_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='africanlii.sourcefile'),
        ),
    ]
