# Generated by Django 3.2.18 on 2023-05-14 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0073_peachjamsettings_pagerank_boost_value"),
        ("countries_plus", "0005_auto_20160224_1804"),
        ("africanlii", "0006_auto_20230510_0811"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="africanunionorgan",
            options={"ordering": ["author__name"]},
        ),
        migrations.AlterModelOptions(
            name="memberstate",
            options={"ordering": ["country__name"]},
        ),
        migrations.AlterModelOptions(
            name="regionaleconomiccommunity",
            options={
                "ordering": ["locality__name"],
                "verbose_name_plural": "Regional economic communities",
            },
        ),
        migrations.AlterField(
            model_name="africanunionorgan",
            name="author",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="au_organ",
                to="peachjam.author",
                verbose_name="author",
            ),
        ),
        migrations.AlterField(
            model_name="memberstate",
            name="country",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="member_state",
                to="countries_plus.country",
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="regionaleconomiccommunity",
            name="locality",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="regional_economic_community",
                to="peachjam.locality",
                verbose_name="locality",
            ),
        ),
    ]
