# Generated by Django 3.2.18 on 2023-05-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("africanlii", "0006_regional_economic_communities"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="regionaleconomiccommunity",
            options={"verbose_name_plural": "Regional economic communities"},
        ),
    ]
