# Generated by Django 3.2.18 on 2023-05-17 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0073_peachjamsettings_pagerank_boost_value"),
        ("africanlii", "0007_auto_20230514_1106"),
    ]

    operations = [
        migrations.CreateModel(
            name="AfricanUnionInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="au_institution",
                        to="peachjam.author",
                        verbose_name="author",
                    ),
                ),
            ],
            options={
                "ordering": ["author__name"],
            },
        ),
    ]
