# Generated by Django 4.2.14 on 2024-10-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("africanlii", "0008_africanunioninstitution"),
        ("peachjam", "0169_ratification_ratificationcountry_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
INSERT INTO
  peachjam_ratification (id, source_url, last_updated, work_id)
  SELECT id, source_url, last_updated, work_id FROM africanlii_ratification;

INSERT INTO
  peachjam_ratificationcountry (id, ratification_id, ratification_date, deposit_date, signature_date, country_id)
  SELECT id, ratification_id, ratification_date, deposit_date, signature_date, country_id FROM africanlii_ratificationcountry;
"""
        )
    ]
