# Generated by Django 4.2.14 on 2024-10-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("africanlii", "0008_africanunioninstitution"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="ratificationcountry",
                    name="country",
                ),
                migrations.RemoveField(
                    model_name="ratificationcountry",
                    name="ratification",
                ),
                migrations.DeleteModel(
                    name="Ratification",
                ),
                migrations.DeleteModel(
                    name="RatificationCountry",
                ),
            ],
        )
    ]
