# Generated by Django 4.2.14 on 2025-03-17 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_en", models.CharField(max_length=100, null=True, unique=True)),
                ("name_fr", models.CharField(max_length=100, null=True, unique=True)),
                ("name_pt", models.CharField(max_length=100, null=True, unique=True)),
                ("name_sw", models.CharField(max_length=100, null=True, unique=True)),
                (
                    "hidden",
                    models.BooleanField(
                        default=False, help_text="Is this feature hidden from users?"
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(blank=True, to="auth.permission"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "period",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annually", "Annually")],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_en", models.CharField(max_length=100, null=True, unique=True)),
                ("name_fr", models.CharField(max_length=100, null=True, unique=True)),
                ("name_pt", models.CharField(max_length=100, null=True, unique=True)),
                ("name_sw", models.CharField(max_length=100, null=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("description_pt", models.TextField(blank=True, null=True)),
                ("description_sw", models.TextField(blank=True, null=True)),
                (
                    "features",
                    models.ManyToManyField(blank=True, to="peachjam_subs.feature"),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pricing_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peachjam_subs.pricingplan",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peachjam_subs.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "pricing_plan")},
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="peachjam_subs.productoffering",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
