# Generated by Django 4.2.14 on 2025-03-17 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_subs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_product_offering",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="peachjam_subs.productoffering",
                        verbose_name="default product offering",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
