# Generated by Django 4.2.14 on 2025-03-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_subs", "0002_subscriptionsettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feature",
            options={"ordering": ("ordering",)},
        ),
        migrations.AddField(
            model_name="feature",
            name="ordering",
            field=models.IntegerField(default=0),
        ),
    ]
