# Generated by Django 4.2.14 on 2025-03-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("peachjam_subs", "0002_product_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "hidden",
                    models.BooleanField(
                        default=False, help_text="Is this feature hidden from users?"
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(blank=True, to="auth.permission"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="features",
            field=models.ManyToManyField(blank=True, to="peachjam_subs.feature"),
        ),
    ]
