# Generated by Django 4.2.14 on 2025-08-16 07:55

import django_fsm
from django.db import migrations, models
from django.utils import timezone


def backfill_status(apps, schema_editor):
    Subscription = apps.get_model("peachjam_subs", "Subscription")
    Subscription.objects.filter(status="xxx", active=True).update(
        status="active", active_at=timezone.now()
    )
    Subscription.objects.filter(status="xxx", active=False).update(
        status="closed", closed_at=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_subs", "0003_alter_feature_options_feature_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="active_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("closed", "Closed"),
                ],
                default="xxx",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_status, migrations.RunPython.noop),
    ]
