# Generated by Django 4.2.14 on 2025-08-16 07:55

import uuid

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_subs", "0004_subscription_status_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("closed", "Closed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="active",
        ),
    ]
