# Generated by Django 4.2.14 on 2025-08-16 10:09

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_subs", "0005_subscription_cleanup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("tier",)},
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="currency_symbol",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tier",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("closed", "Closed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
