# Generated by Django 4.2.14 on 2025-08-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "peachjam_subs",
            "0006_alter_product_options_pricingplan_currency_symbol_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="ends_on",
            field=models.DateField(
                blank=True, help_text="Date when the subscription ends", null=True
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="starts_on",
            field=models.DateField(
                blank=True,
                help_text="Date when the subscription becomes active",
                null=True,
            ),
        ),
    ]
