# Generated by Django 4.2.14 on 2025-08-28 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_subs", "0007_subscription_end_date_subscription_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="hidden",
        ),
        migrations.AddField(
            model_name="product",
            name="default_offering",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="peachjam_subs.productoffering",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="key_features",
            field=models.ManyToManyField(
                blank=True,
                help_text="These features are highlighted in the product listing.",
                related_name="+",
                to="peachjam_subs.feature",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionsettings",
            name="key_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="These products are highlighted in the product listing.",
                to="peachjam_subs.product",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionsettings",
            name="default_product_offering",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="peachjam_subs.productoffering",
                verbose_name="Default product offering",
            ),
        ),
    ]
