# Generated by Django 4.2.14 on 2025-08-28 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "peachjam_subs",
            "0008_remove_feature_hidden_product_default_offering_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productoffering",
            options={
                "permissions": [("can_subscribe", "Can subscribe to this offering")]
            },
        ),
        migrations.AlterModelOptions(
            name="subscriptionsettings",
            options={
                "verbose_name": "Subscription Settings",
                "verbose_name_plural": "Subscription Settings",
            },
        ),
    ]
