# Generated by Django 4.2.14 on 2025-08-29 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_subs", "0009_alter_productoffering_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_trial",
            field=models.BooleanField(
                default=False, help_text="Whether this is a trial subscription"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_replaces",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trial_subscriptions",
                to="peachjam_subs.subscription",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionsettings",
            name="trial_duration_days",
            field=models.IntegerField(
                default=14,
                help_text="Number of days for the trial period.",
                verbose_name="Trial duration (days)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionsettings",
            name="trial_product_offering",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this product offering is used for trials.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="peachjam_subs.productoffering",
                verbose_name="Trial product offering",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionsettings",
            name="default_product_offering",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="peachjam_subs.productoffering",
                verbose_name="Default product offering",
            ),
        ),
    ]
