# Generated by Django 4.2 on 2025-09-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "peachjam_subs",
            "0010_subscription_is_trial_subscription_trial_replaces_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="saved_document_limit",
            field=models.IntegerField(
                default=999999,
                help_text="The is the maximum number of documents a user can save.",
            ),
        ),
    ]
