# Generated by Django 4.2 on 2025-09-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "peachjam_subs",
            "0010_subscription_is_trial_subscription_trial_replaces_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="saved_document_limit",
            field=models.IntegerField(
                default=0,
                help_text="If set, this is the maximum number of documents a user can save. Leave blank for unlimited.",
            ),
        ),
    ]
