# Generated by Django 4.2 on 2025-09-09 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "peachjam_subs",
            "0010_subscription_is_trial_subscription_trial_replaces_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="saved_document_limit",
            field=models.IntegerField(
                blank=True,
                default=-1,
                help_text="If set, this is the maximum number of documents a user can save. Leave blank for unlimited.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="peachjam_subs.subscription",
                    ),
                ),
            ],
        ),
    ]
