# Generated by Django 4.2 on 2025-09-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_subs", "0011_product_saved_document_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="folder_limit",
            field=models.IntegerField(
                default=999999,
                help_text="The is the maximum number of folders a user can create.",
            ),
        ),
    ]
