# Generated by Django 4.2 on 2025-09-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_subs", "0012_product_folder_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="search_alert_limit",
            field=models.IntegerField(
                default=999999,
                help_text="The is the maximum number of search alerts a user can create.",
            ),
        ),
    ]
