# Generated by Django 4.2 on 2025-10-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_subs", "0013_product_search_alert_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="following_limit",
            field=models.IntegerField(
                default=999999,
                help_text="The is the maximum number of entities a user can follow.",
            ),
        ),
    ]
