# Generated by Django 4.2.14 on 2025-12-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_subs", "0014_product_following_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="document_chat_limit",
            field=models.IntegerField(
                default=999999,
                help_text="The is the maximum number of chats per month a user can create.",
            ),
        ),
    ]
