# Generated by Django 4.2.27 on 2026-01-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_subs", "0015_document_chat_limit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="name_fr",
        ),
        migrations.RemoveField(
            model_name="feature",
            name="name_pt",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_fr",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_pt",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name_fr",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name_pt",
        ),
    ]
