# Generated by Django 4.2.29 on 2026-03-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_subs", "0016_product_selectable_offerings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingplan",
            name="period",
            field=models.CharField(
                choices=[("annually", "Annually"), ("monthly", "Monthly")],
                max_length=50,
            ),
        ),
    ]
