# Generated by Django 5.1 on 2026-08-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peachjam_subs", "0017_alter_pricingplan_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="OffboardingFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("subscription-downgrade", "Subscription downgrade"),
                            ("account-deletion", "Account deletion"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("too-expensive", "Too expensive"),
                            ("not-using-enough", "Not using it enough"),
                            ("missing-feature", "Missing a feature"),
                            ("technical-issue", "Technical issue"),
                            ("switching-alternative", "Switching to an alternative"),
                            ("temporary-need", "Temporary need"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_product_offering",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_offboarding_feedback",
                        to="peachjam_subs.productoffering",
                    ),
                ),
                (
                    "requested_product_offering",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_offboarding_feedback",
                        to="peachjam_subs.productoffering",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offboarding_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
    ]
