# Generated by Django 5.1 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam_subs", "0018_offboardingfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="offboardingfeedback",
            name="confirmation_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="offboardingfeedback",
            constraint=models.UniqueConstraint(
                fields=("user", "event_type", "confirmation_token"),
                name="unique_offboarding_feedback_confirmation",
            ),
        ),
    ]
