# Generated by Django 4.2.30 on 2026-09-08 15:39

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import peachjam_subs.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peachjam_subs", "0019_offboardingfeedback_confirmation_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisional", "Provisional"),
                            ("active", "Active"),
                            ("closing", "Closing"),
                            ("closed", "Closed"),
                        ],
                        default="provisional",
                        max_length=20,
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(
                        choices=[("annually", "Annually"), ("monthly", "Monthly")],
                        max_length=50,
                    ),
                ),
                (
                    "privacy_mode",
                    models.CharField(
                        choices=[
                            ("managed-usage", "Managed usage"),
                            ("billing-only", "Private / billing only"),
                        ],
                        default="billing-only",
                        max_length=20,
                    ),
                ),
                (
                    "pending_privacy_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("managed-usage", "Managed usage"),
                            ("billing-only", "Private / billing only"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("privacy_change_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("closing_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("name", "pk"),
            },
        ),
        migrations.CreateModel(
            name="OrganisationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Administrator"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("ended", "Ended")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("pending_end_on", models.DateField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="peachjam_subs.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisation_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("user__last_name", "user__first_name", "pk"),
            },
        ),
        migrations.CreateModel(
            name="OrganisationSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisional", "Provisional"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("ended", "Ended"),
                        ],
                        default="provisional",
                        max_length=20,
                    ),
                ),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("pending_change_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="peachjam_subs.organisation",
                    ),
                ),
                (
                    "pending_product_offering",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pending_organisation_seats",
                        to="peachjam_subs.productoffering",
                    ),
                ),
                (
                    "product_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisation_seats",
                        to="peachjam_subs.productoffering",
                    ),
                ),
            ],
            options={
                "ordering": ("product_offering__product__tier", "pk"),
            },
        ),
        migrations.CreateModel(
            name="OrganisationSeatAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seat_assignments",
                        to="peachjam_subs.organisationmembership",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="peachjam_subs.organisationseat",
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organisation_seat_assignment",
                        to="peachjam_subs.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="OrganisationInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Administrator"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=peachjam_subs.models.organisation_invitation_expiry
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_membership",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_invitation",
                        to="peachjam_subs.organisationmembership",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_organisation_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="peachjam_subs.organisation",
                    ),
                ),
                (
                    "requested_product_offering",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisation_invitations",
                        to="peachjam_subs.productoffering",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrganisationAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("activated", "Activated"),
                            ("invitation-sent", "Invitation sent"),
                            ("invitation-accepted", "Invitation accepted"),
                            ("invitation-cancelled", "Invitation cancelled"),
                            ("invitation-expired", "Invitation expired"),
                            ("role-changed", "Role changed"),
                            ("ownership-transferred", "Ownership transferred"),
                            ("seat-assigned", "Subscription assigned"),
                            ("seat-released", "Subscription released"),
                            ("plan-changed", "Plan changed"),
                            ("member-removed", "Member removed"),
                            ("member-left", "Member left"),
                            ("privacy-changed", "Privacy changed"),
                            ("suspended", "Suspended"),
                            ("restored", "Restored"),
                            ("closure-requested", "Closure requested"),
                            ("closed", "Closed"),
                        ],
                        max_length=40,
                    ),
                ),
                ("message", models.CharField(max_length=1024)),
                ("event_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organisation_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="peachjam_subs.organisationinvitation",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="peachjam_subs.organisationmembership",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="peachjam_subs.organisation",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="peachjam_subs.organisationseat",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.AddConstraint(
            model_name="organisationseatassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("seat",),
                name="one_active_assignment_per_org_seat",
            ),
        ),
        migrations.AddConstraint(
            model_name="organisationseatassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("membership",),
                name="one_active_org_seat_per_membership",
            ),
        ),
        migrations.AddConstraint(
            model_name="organisationmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("user",),
                name="one_active_organisation_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="organisationmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "owner"), ("status", "active")),
                fields=("organisation",),
                name="one_active_owner_per_organisation",
            ),
        ),
        migrations.AddConstraint(
            model_name="organisationinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("organisation", "email"),
                name="one_pending_invitation_per_org_email",
            ),
        ),
        migrations.AddIndex(
            model_name="organisationauditevent",
            index=models.Index(
                fields=["organisation", "-created_at"],
                name="peachjam_su_organis_c4ae95_idx",
            ),
        ),
    ]
