# Generated by Django 4.2.30 on 2026-09-18 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "peachjam_subs",
            "0020_organisation_organisationmembership_organisationseat_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationSeatChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting-settlement", "Awaiting settlement"),
                            ("applied", "Applied"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="awaiting-settlement",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="OrganisationSeatChangeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("add", "Add seat"),
                            ("upgrade", "Upgrade seat"),
                            ("reassign", "Reassign seat"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
        migrations.RemoveConstraint(
            model_name="organisationinvitation",
            name="one_pending_invitation_per_org_email",
        ),
        migrations.AddField(
            model_name="organisationinvitation",
            name="reserved_seat",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reserved_invitation",
                to="peachjam_subs.organisationseat",
            ),
        ),
        migrations.AddField(
            model_name="organisationinvitation",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organisationauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("activated", "Activated"),
                    ("invitation-sent", "Invitation sent"),
                    ("invitation-accepted", "Invitation accepted"),
                    ("invitation-cancelled", "Invitation cancelled"),
                    ("invitation-expired", "Invitation expired"),
                    ("role-changed", "Role changed"),
                    ("ownership-transferred", "Ownership transferred"),
                    ("seat-assigned", "Subscription assigned"),
                    ("seat-released", "Subscription released"),
                    ("plan-changed", "Plan changed"),
                    ("seat-change-requested", "Seat change requested"),
                    ("seat-change-applied", "Seat change applied"),
                    ("seat-change-cancelled", "Seat change cancelled"),
                    ("member-removed", "Member removed"),
                    ("member-left", "Member left"),
                    ("privacy-changed", "Privacy changed"),
                    ("suspended", "Suspended"),
                    ("restored", "Restored"),
                    ("closure-requested", "Closure requested"),
                    ("closed", "Closed"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="organisationinvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("awaiting-payment", "Awaiting payment"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="organisationinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["awaiting-payment", "pending"])),
                fields=("organisation", "email"),
                name="one_pending_invitation_per_org_email",
            ),
        ),
        migrations.AddField(
            model_name="organisationseatchangeitem",
            name="change",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="peachjam_subs.organisationseatchange",
            ),
        ),
        migrations.AddField(
            model_name="organisationseatchangeitem",
            name="previous_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outgoing_organisation_seat_change_items",
                to="peachjam_subs.organisationmembership",
            ),
        ),
        migrations.AddField(
            model_name="organisationseatchangeitem",
            name="previous_offering",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="previous_organisation_seat_change_items",
                to="peachjam_subs.productoffering",
            ),
        ),
        migrations.AddField(
            model_name="organisationseatchangeitem",
            name="requested_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_organisation_seat_change_items",
                to="peachjam_subs.organisationmembership",
            ),
        ),
        migrations.AddField(
            model_name="organisationseatchangeitem",
            name="requested_offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requested_organisation_seat_change_items",
                to="peachjam_subs.productoffering",
            ),
        ),
        migrations.AddField(
            model_name="organisationseatchangeitem",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pending_change_items",
                to="peachjam_subs.organisationseat",
            ),
        ),
        migrations.AddField(
            model_name="organisationseatchange",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seat_changes",
                to="peachjam_subs.organisation",
            ),
        ),
        migrations.AddField(
            model_name="organisationseatchange",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_organisation_seat_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="organisationseatchangeitem",
            constraint=models.UniqueConstraint(
                fields=("change", "seat"), name="one_item_per_seat_change"
            ),
        ),
        migrations.AddConstraint(
            model_name="organisationseatchange",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "awaiting-settlement")),
                fields=("organisation",),
                name="one_awaiting_org_seat_change",
            ),
        ),
    ]
