# Generated by Django 4.2 on 2026-10-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "peachjam_subs",
            "0021_organisationseatchange_organisationseatchangeitem_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("activated", "Activated"),
                    ("invitation-sent", "Invitation sent"),
                    ("invitation-accepted", "Invitation accepted"),
                    ("invitation-cancelled", "Invitation cancelled"),
                    ("invitation-expired", "Invitation expired"),
                    ("member-added", "Member added"),
                    ("role-changed", "Role changed"),
                    ("ownership-transferred", "Ownership transferred"),
                    ("seat-assigned", "Subscription assigned"),
                    ("seat-released", "Subscription released"),
                    ("plan-changed", "Plan changed"),
                    ("seat-change-requested", "Seat change requested"),
                    ("seat-change-applied", "Seat change applied"),
                    ("seat-change-cancelled", "Seat change cancelled"),
                    ("member-removed", "Member removed"),
                    ("member-left", "Member left"),
                    ("privacy-changed", "Privacy changed"),
                    ("suspended", "Suspended"),
                    ("restored", "Restored"),
                    ("closure-requested", "Closure requested"),
                    ("closed", "Closed"),
                ],
                max_length=40,
            ),
        ),
    ]
