from django.urls import include, path, re_path
from django.views.decorators.cache import cache_page

from peachjam.urls import CACHE_DURATION
from peachjam.views import (
    AnnotationDeleteView,
    AnnotationDetailView,
    AnnotationEditView,
    AnnotationListView,
    ComparePortionsView,
    DocumentAttachmentView,
    DocumentCitationsView,
    DocumentDetailViewResolver,
    DocumentMediaView,
    DocumentPopupView,
    DocumentProblemView,
    DocumentProvisionCitationView,
    DocumentPublicationView,
    DocumentSocialImageView,
    DocumentSourcePDFView,
    DocumentSourceView,
    DocumentSummaryView,
    DocumentTextContentView,
    PartnerLogoView,
)

urlpatterns = [
    # document detail views
    re_path(
        r"^(?P<frbr_uri>akn/.*)/source$",
        cache_page(CACHE_DURATION)(DocumentSourceView.as_view()),
        name="document_source",
    ),
    re_path(
        r"^(?P<frbr_uri>akn/.*)/publication$",
        cache_page(CACHE_DURATION)(DocumentPublicationView.as_view()),
        name="document_publication",
    ),
    re_path(
        r"^(?P<frbr_uri>akn/.*)/source.pdf$",
        cache_page(CACHE_DURATION)(DocumentSourcePDFView.as_view()),
        name="document_source_pdf",
    ),
    re_path(
        r"^(?P<frbr_uri>akn/.*)/media/(?P<filename>.+)$",
        cache_page(CACHE_DURATION)(DocumentMediaView.as_view()),
        name="document_media",
    ),
    re_path(
        r"^(?P<frbr_uri>akn/.*)/attachment/(?P<filename>.+)$",
        cache_page(CACHE_DURATION)(DocumentAttachmentView.as_view()),
        name="document_attachment",
    ),
    re_path(
        r"^(?P<frbr_uri>akn/.+?)/provision(?:/(?P<provision_eid>.+))?$",
        cache_page(CACHE_DURATION)(DocumentProvisionCitationView.as_view()),
        name="document_citation_context",
    ),
    re_path(
        r"^(?P<frbr_uri>akn/.*)/citations$",
        cache_page(CACHE_DURATION)(DocumentCitationsView.as_view()),
        name="document_citations",
    ),
    re_path(
        r"^(?P<frbr_uri>akn/.*)/social-image.png$",
        cache_page(CACHE_DURATION)(DocumentSocialImageView.as_view()),
        name="document_social_image",
    ),
    re_path(
        r"^(?P<frbr_uri>akn/?.*)$",
        DocumentDetailViewResolver.as_view(),
        name="document_detail",
    ),
    # law-widget support services
    path(
        "p/<str:partner>/e/popup/<path:frbr_uri>",
        cache_page(CACHE_DURATION)(DocumentPopupView.as_view()),
    ),
    path(
        "document-problem/",
        DocumentProblemView.as_view(),
        name="document_problem",
    ),
    # Annotations
    path(
        "document/<int:document_pk>/annotations/",
        include(
            [
                path(
                    "",
                    AnnotationListView.as_view(),
                    name="annotation_list",
                ),
                path(
                    "<int:pk>/",
                    AnnotationDetailView.as_view(),
                    name="annotation_detail",
                ),
                path(
                    "<int:pk>/edit",
                    AnnotationEditView.as_view(),
                    name="annotation_edit",
                ),
                path(
                    "<int:pk>/delete",
                    AnnotationDeleteView.as_view(),
                    name="annotation_delete",
                ),
            ]
        ),
    ),
    path(
        "document/<int:pk>/summary",
        DocumentSummaryView.as_view(),
        name="document_summary",
    ),
    path(
        "document/<int:pk>/text",
        DocumentTextContentView.as_view(),
        name="document_text_content",
    ),
    path(
        "partners/<int:pk>/logo/<int:logo_pk>",
        PartnerLogoView.as_view(),
        name="partner_logo",
    ),
    path(
        "compare",
        ComparePortionsView.as_view(),
        name="compare_portions",
    ),
]
