from django.urls import path

from peachjam.views import (
    FolderCreateView,
    FolderDeleteView,
    FolderDownloadView,
    FolderListView,
    FolderUpdateView,
    SavedDocumentButtonBulkView,
    SavedDocumentButtonView,
    SavedDocumentCreateView,
    SavedDocumentDeleteView,
    SavedDocumentUpdateView,
)

urlpatterns = [
    path(
        "button/<int:doc_id>",
        SavedDocumentButtonView.as_view(),
        name="saved_document_button",
    ),
    path(
        "buttons/",
        SavedDocumentButtonBulkView.as_view(),
    ),
    path(
        "create",
        SavedDocumentCreateView.as_view(),
        name="saved_document_create",
    ),
    path(
        "<int:pk>/update",
        SavedDocumentUpdateView.as_view(),
        name="saved_document_update",
    ),
    path(
        "<int:pk>/delete",
        SavedDocumentDeleteView.as_view(),
        name="saved_document_delete",
    ),
    path(
        "folders/",
        FolderListView.as_view(),
        name="folder_list",
    ),
    path(
        "folders/create",
        FolderCreateView.as_view(),
        name="folder_create",
    ),
    path(
        "folders/<int:pk>/update",
        FolderUpdateView.as_view(),
        name="folder_update",
    ),
    path(
        "folders/<int:pk>/delete",
        FolderDeleteView.as_view(),
        name="folder_delete",
    ),
    path(
        "folders/<int:pk>/download",
        FolderDownloadView.as_view(),
        name="folder_download",
    ),
]
