# Generated by Django 3.2.25 on 2024-04-26 17:17

import os

from django.db import migrations


def forwards(apps, schema_editor):
    from django.conf import settings
    from django_elasticsearch_dsl.registries import registry

    if settings.ELASTICSEARCH_DSL_AUTOSYNC and os.environ.get("ELASTICSEARCH_HOST"):
        for ix in registry.get_indices():
            if not ix._mapping:
                continue
            print(f"Adding provisions mapping for {ix._name}")
            ix.connection.indices.put_mapping(
                index=ix._name,
                body={
                    "properties": {"provisions": ix._mapping["provisions"].to_dict()}
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam", "0125_judgment_auto_assign_title"),
    ]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop)]
