# Generated by Django 3.2.25 on 2024-05-08 14:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peachjam_search", "0001_es_mapping_add_provisions"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchTrace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_id",
                    models.CharField(editable=False, max_length=1024, null=True),
                ),
                ("ip_address", models.CharField(max_length=1024, null=True)),
                ("user_agent", models.CharField(max_length=2048, null=True)),
                ("search", models.CharField(max_length=2048)),
                ("field_searches", models.JSONField(null=True)),
                ("n_results", models.IntegerField()),
                ("page", models.IntegerField()),
                ("filters", models.JSONField(null=True)),
                ("ordering", models.CharField(max_length=1024, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "previous_search",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peachjam_search.searchtrace",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SearchClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frbr_uri", models.CharField(max_length=2048)),
                ("portion", models.CharField(max_length=2048, null=True)),
                ("position", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "search_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peachjam_search.searchtrace",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
