# Generated by Django 3.2.25 on 2024-05-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_search", "0002_searchclick_searchtrace"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchtrace",
            name="config_version",
            field=models.CharField(default="2024-05-01", max_length=50),
            preserve_default=False,
        ),
    ]
