# Generated by Django 3.2.25 on 2024-07-19 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_search", "0003_searchtrace_config_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchclick",
            name="search_trace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clicks",
                to="peachjam_search.searchtrace",
            ),
        ),
        migrations.AlterField(
            model_name="searchtrace",
            name="previous_search",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_searches",
                to="peachjam_search.searchtrace",
            ),
        ),
    ]
