# Generated by Django 4.2.15 on 2024-11-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_search", "0010_alter_savedsearch_filters"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedsearch",
            old_name="last_alert",
            new_name="last_alerted_at",
        ),
        migrations.AlterField(
            model_name="savedsearch",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
