# Generated by Django 4.2.15 on 2025-02-14 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "peachjam_search",
            "0011_rename_last_alert_savedsearch_last_alerted_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback",
                    models.CharField(max_length=4096, verbose_name="feedback"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="email address",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "search_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_clicks",
                        to="peachjam_search.searchtrace",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
