# Generated by Django 4.2.14 on 2025-03-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_search", "0012_searchfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchtrace",
            name="mode",
            field=models.CharField(default="text", max_length=20),
        ),
    ]
