# Generated by Django 4.2.14 on 2025-03-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_search", "0013_searchtrace_mode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchtrace",
            options={
                "ordering": ("-created_at",),
                "permissions": [
                    ("can_debug_search", "Can debug search"),
                    ("can_download_search", "Can download search results"),
                ],
            },
        ),
    ]
