# Generated by Django 4.2.15 on 2025-04-07 14:14
import os

from django.db import migrations


def forwards(apps, schema_editor):
    from django.conf import settings
    from django_elasticsearch_dsl.registries import registry

    if not settings.DEBUG and os.environ.get("ELASTICSEARCH_HOST"):
        for ix in registry.get_indices():
            if not ix._mapping:
                continue
            ix.connection.indices.put_mapping(
                index=ix._name,
                body={
                    "properties": {
                        "case_action": ix._mapping["case_action"].to_dict(),
                        "division": ix._mapping["division"].to_dict(),
                    }
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_search", "0014_alter_searchtrace_options"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
