# Generated by Django 4.2.15 on 2025-04-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_search", "0014_alter_searchtrace_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchtrace",
            options={
                "ordering": ("-created_at",),
                "permissions": [
                    ("can_debug_search", "Can debug search"),
                    ("can_download_search", "Can download search results"),
                    ("can_semantic_search", "Can use semantic search"),
                ],
            },
        ),
        migrations.AlterField(
            model_name="savedsearch",
            name="last_alerted_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
