# Generated by Django 4.2.15 on 2025-07-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_search", "0016_alter_searchtrace_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedsearch",
            name="q",
            field=models.CharField(blank=True, max_length=4098, null=True),
        ),
    ]
