# Generated by Django 4.2.15 on 2025-07-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_search", "0017_alter_savedsearch_q"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedsearch",
            name="a",
            field=models.CharField(blank=True, max_length=4098, null=True),
        ),
        migrations.AddConstraint(
            model_name="savedsearch",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("q__isnull", False), ("a__isnull", False), _connector="OR"
                ),
                name="at_least_one_field_not_null",
            ),
        ),
    ]
