# Generated by Django 4.2.15 on 2025-11-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_search", "0020_es_mapping_add_frbr_uri_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchtrace",
            options={
                "ordering": ("-created_at",),
                "permissions": [
                    ("can_debug_search", "Can debug search"),
                    ("can_download_search", "Can download search results"),
                ],
            },
        ),
        migrations.AlterField(
            model_name="searchtrace",
            name="suggestion",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
