# Generated by Django 4.2.14 on 2025-12-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_search", "0022_alter_searchtrace_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchtrace",
            options={
                "ordering": ("-created_at",),
                "permissions": [
                    ("can_debug_search", "Can debug search"),
                    ("can_download_search", "Can download search results"),
                    ("can_search_portions", "Can use portion search API"),
                ],
            },
        ),
    ]
