# Generated by Django 4.2.14 on 2025-12-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peachjam_search", "0023_alter_searchtrace_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchtrace",
            name="query_classification",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="searchtrace",
            name="query_classification_confidence",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="searchtrace",
            name="query_clean",
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="searchtrace",
            name="query_clean_n_chars",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="searchtrace",
            name="query_clean_n_words",
            field=models.IntegerField(null=True),
        ),
    ]
