# Generated by Django 4.2.14 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam_search", "0028_searchtrace_query_analysis_and_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchtrace",
            name="kind",
            field=models.CharField(
                choices=[("documents", "Documents"), ("portions", "Portions")],
                default="documents",
                max_length=20,
            ),
        ),
    ]
