# Generated by Django 4.2.14 on 2026-09-08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peachjam", "0225_judgment_blurb_judgment_held_judgment_issues_and_more"),
        ("peachjam_search", "0029_searchtrace_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchtrace",
            name="kind",
            field=models.CharField(
                choices=[
                    ("documents", "Documents"),
                    ("portions", "Portions"),
                    ("flynotes", "Legal topics"),
                ],
                default="documents",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SearchFlynoteResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("flynote_name", models.CharField(max_length=255)),
                ("flynote_path_labels", models.JSONField()),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "surface",
                    models.CharField(
                        choices=[
                            ("document_search_card", "Document search card"),
                            ("topics_page_branch", "Topics page branch"),
                            ("topics_page_match", "Topics page matching topic"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("direct_query", "Direct query match"),
                            ("document_support", "Document-supported match"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "selection_reason",
                    models.CharField(
                        choices=[
                            ("direct_name_match", "Direct name match"),
                            ("lexical_document_support", "Lexical document support"),
                            (
                                "strong_document_convergence",
                                "Strong document convergence",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flynote",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="peachjam.flynote",
                    ),
                ),
                (
                    "search_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flynote_results",
                        to="peachjam_search.searchtrace",
                    ),
                ),
            ],
            options={"ordering": ("position",)},
        ),
        migrations.CreateModel(
            name="SearchFlynoteClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flynote_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click",
                        to="peachjam_search.searchflynoteresult",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="searchflynoteresult",
            constraint=models.UniqueConstraint(
                fields=("search_trace", "surface", "position"),
                name="unique_search_flynote_result_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="searchflynoteresult",
            constraint=models.UniqueConstraint(
                fields=("search_trace", "surface", "flynote"),
                name="unique_search_flynote_result_flynote",
            ),
        ),
    ]
