# Generated by Django 4.2.14 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peachjam_search", "0030_searchflynoteresult_and_more")]

    operations = [
        migrations.AddField(
            model_name="searchtrace",
            name="elasticsearch_query",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="searchtrace",
            name="error_message",
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="searchtrace",
            name="error_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="searchtrace",
            name="status",
            field=models.CharField(
                choices=[("completed", "Completed"), ("timed_out", "Timed out")],
                default="completed",
                max_length=20,
            ),
        ),
    ]
