# Generated by Django 4.2.14 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peachjam_search", "0030_searchflynoteresult_and_more")]

    operations = [
        migrations.AddField(
            model_name="searchtrace",
            name="elasticsearch_query",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="searchtrace",
            name="error_message",
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="searchtrace",
            name="error_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="searchtrace",
            name="status",
            field=models.CharField(
                choices=[("completed", "Completed"), ("timed_out", "Timed out")],
                default="completed",
                max_length=20,
            ),
        ),
        # Django uses the model default while adding the non-null column but
        # does not retain it in PostgreSQL. Keep a database default as well,
        # so older application processes can still create a trace during a
        # rolling deployment.
        migrations.RunSQL(
            "ALTER TABLE peachjam_search_searchtrace "
            "ALTER COLUMN status SET DEFAULT 'completed'",
            "ALTER TABLE peachjam_search_searchtrace "
            "ALTER COLUMN status DROP DEFAULT",
        ),
    ]
