# Generated by Django 4.2.14 on 2026-09-10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("peachjam_search", "0031_searchtrace_timeout_details")]

    operations = [
        # Django uses the model default while adding the non-null column but
        # does not retain it in PostgreSQL. Keep a database default as well,
        # so older application processes can still create a trace during a
        # rolling deployment.
        migrations.RunSQL(
            "ALTER TABLE peachjam_search_searchtrace "
            "ALTER COLUMN status SET DEFAULT 'completed'",
            "ALTER TABLE peachjam_search_searchtrace "
            "ALTER COLUMN status DROP DEFAULT",
        ),
    ]
