# Generated by Django 4.2.14 on 2026-09-10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("peachjam_search", "0031_searchtrace_timeout_details")]

    operations = [
        migrations.CreateModel(
            name="SearchEntityResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity_type", models.CharField(max_length=30)),
                ("entity_id", models.PositiveIntegerField()),
                ("entity_label", models.CharField(max_length=255)),
                ("entity_url", models.CharField(max_length=2048)),
                ("match_type", models.CharField(max_length=30)),
                ("confidence", models.FloatField()),
                ("position", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "search_trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_results",
                        to="peachjam_search.searchtrace",
                    ),
                ),
            ],
            options={"ordering": ("position",)},
        ),
        migrations.CreateModel(
            name="SearchEntityClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click",
                        to="peachjam_search.searchentityresult",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="searchentityresult",
            constraint=models.UniqueConstraint(
                fields=("search_trace", "position"),
                name="unique_search_entity_result_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="searchentityresult",
            constraint=models.UniqueConstraint(
                fields=("search_trace", "entity_type", "entity_id"),
                name="unique_search_entity_result_entity",
            ),
        ),
    ]
