from liiweb.settings import *  # noqa

INSTALLED_APPS = ["tanzlii.apps.TanzLIIConfig"] + INSTALLED_APPS  # noqa


JAZZMIN_SETTINGS["site_title"] = "TanzLII"  # noqa
JAZZMIN_SETTINGS["site_header"] = "TanzLII"  # noqa
JAZZMIN_SETTINGS["site_brand"] = "tanzlii.org"  # noqa

COURT_CODE_MAPPINGS = {
    "court-of-appeal-arusha-registry": "",
    "court-of-appeal-bukoba-registry": "TZCA-court-of-appeal-bukoba-registry",
    "court-of-appeal-chake-chake-pemba-registry": "",
    "court-of-appeal-dar-es-salaam-registry": "TZCA-court-of-appeal-dar-es-salaam-registry",
    "court-of-appeal-dodoma-registry": "TZCA-court-of-appeal-dodoma-registry",
    "court-of-appeal-iringa-registry": "TZCA-court-of-appeal-iringa-registry",
    "court-of-appeal-kigoma-registry": "TZCA-court-of-appeal-kigoma-registry",
    "court-of-appeal-mbeya-registry": "TZCA-court-of-appeal-mbeya-registry",
    "court-of-appeal-moshi-registry": "TZCA-court-of-appeal-moshi-registry",
    "court-of-appeal-mtwara-registry": "TZCA-court-of-appeal-mtwara-registry",
    "court-of-appeal-musoma-registry": "TZCA-court-of-appeal-musoma-registry",
    "court-of-appeal-mwanza-registry": "TZCA-court-of-appeal-mwanza-registry",
    "court-of-appeal-shinyanga-registry": "",
    "court-of-appeal-songea-main-registry": "",
    "court-of-appeal-songea-registry": "TZCA-court-of-appeal-songea-registry",
    "court-of-appeal-sumbawanga-registry": "TZCA-court-of-appeal-sumbawanga-registry",
    "court-of-appeal-tabora-registry": "TZCA-court-of-appeal-tabora-registry",
    "court-of-appeal-tanga-registry": "",
    "court-of-appeal-tanga-registry-": "TZCA-court-of-appeal-tanga-registry",
    "court-of-appeal-vuga-registry": "",
    "court-of-appeal-zanzibar-registry": "",
    "high-court-arusha-registry": "TZHC-high-court-arusha-registry",
    "high-court-bukoba-registry": "TZHC-high-court-bukoba-registry",
    "high-court-chake-chake-pemba-registry": "TZHC-high-court-chake-chake-pemba-registry",
    "high-court-commercial-division-arusha": "TZHC-high-court-commercial-division-arusha",
    "high-court-commercial-division-dar-es-salaam": "TZHC-high-court-commercial-division-dar-es-salaam",
    "high-court-commercial-division-mwanza": "TZHC-high-court-commercial-division-mwanza",
    "high-court-dar-es-salaam-main-registry": "TZHC-high-court-dar-es-salaam-main-registry",
    "high-court-dar-es-salaam-zone-registry": "TZHC-high-court-dar-es-salaam-zone-registry",
    "high-court-dodoma-registry": "TZHC-high-court-dodoma-registry",
    "high-court-iringa-registry": "TZHC-high-court-iringa-registry",
    "high-court-kigoma-registry": "TZHC-high-court-kigoma-registry",
    "high-court-manyara-registry": "TZHC-high-court-manyara-registry",
    "high-court-mbeya-registry": "TZHC-high-court-mbeya-registry",
    "high-court-mediation-center": "TZHC-high-court-mediation-center",
    "high-court-morogoro-registry": "TZHC-high-court-morogoro-registry",
    "high-court-moshi-registry": "TZHC-high-court-moshi-registry",
    "high-court-mtwara-registry": "TZHC-high-court-mtwara-registry",
    "high-court-musoma-registry": "TZHC-high-court-musoma-registry",
    "high-court-mwanza-registry": "TZHC-high-court-mwanza-registry",
    "high-court-of-zanzibar": "",
    "high-court-shinyanga-registry": "TZHC-high-court-shinyanga-registry",
    "high-court-songea-main-registry": "TZHC-high-court-songea-main-registry",
    "high-court-songea-registry": "TZHC-high-court-songea-registry",
    "high-court-sumbawanga-registry": "TZHC-high-court-sumbawanga-registry",
    "high-court-tabora-registry": "TZHC-high-court-tabora-registry",
    "high-court-tanga-registry": "TZHC-high-court-tanga-registry",
    "high-court-vuga-registry": "TZHC-high-court-vuga-registry",
    "labour-court-of-tanzania": "",
    "one-stop-judicial-center-temeke": "TZHC-one-stop-judicial-center-temeke",
    "high-court-commercial-division": "",
    "high-court-corruption-and-economic-crimes-division": "",
    "high-court-labour-division": "",
    "high-court-land-division": "",
}
