name: Build

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile javascript and commit changes
    steps:
      - uses: actions/checkout@v3
        with:
          # use a token that has admin perms to bypass direct commits to master
          token: ${{ secrets.LA_ACTIONS_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline --ignore-scripts

      - name: Build
        run: npx webpack --mode production
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'peachjam/static/js/*app-prod.js peachjam/static/js/pdf.worker-prod.js --force'
          message: 'Update compiled javascript'
