name: Build l10n

on:
  push:
    branches:
      - l10n_main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile updated translations and commit changes
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext
          python -m pip install --upgrade pip setuptools wheel
          pip install .
          pip install psycopg2-binary==2.9.3

      - name: Compile messages
        run: python manage.py compilemessages

      - name: Push
        uses: EndBug/add-and-commit@v9
        with:
          add: '*/locale/*/LC_MESSAGES/*.mo'
          message: 'Update compiled translations'
